-- ============================================================
-- MedicHall — Supabase database setup (Step 1: Products + RFQ)
-- Run this once in Supabase Dashboard -> SQL Editor -> New query
-- ============================================================

-- 1) PRODUCTS ------------------------------------------------
create table if not exists public.products (
  id          bigint generated by default as identity primary key,
  ref         text unique not null,
  name        text not null,
  category    text not null,
  description text,
  image_url   text,
  is_active   boolean not null default true,
  created_at  timestamptz not null default now()
);

-- 2) PARTNERS ------------------------------------------------
create table if not exists public.partners (
  id         bigint generated by default as identity primary key,
  name       text not null,
  type       text,
  is_active  boolean not null default true,
  created_at timestamptz not null default now()
);

-- 3) RFQ REQUESTS (quotation requests from buyers) -----------
create table if not exists public.rfq_requests (
  id           bigint generated by default as identity primary key,
  product_ref  text,
  product_name text,
  email        text not null,
  company      text,
  message      text,
  created_at   timestamptz not null default now()
);

-- 4) ROW LEVEL SECURITY --------------------------------------
alter table public.products     enable row level security;
alter table public.partners     enable row level security;
alter table public.rfq_requests enable row level security;

-- Anyone can READ active products & partners (public catalog)
create policy "public read products" on public.products
  for select using (is_active = true);

create policy "public read partners" on public.partners
  for select using (is_active = true);

-- Anyone can SUBMIT an RFQ, but nobody can read them publicly.
-- (You will read them from the Supabase dashboard — Table Editor -> rfq_requests)
create policy "public insert rfq" on public.rfq_requests
  for insert with check (true);

-- 5) SEED DATA — your current catalog ------------------------
insert into public.products (ref, name, category, description, image_url, is_active) values
('MH-070','Laparotomy Pack','Medical Devices','Sterile, single-use surgical product manufactured under CE MDR and ISO 13485 quality systems. Custom configurations and private-label (OEM) production available on request.','https://medichall.com/images/products/70/643bdbd6621b41681644502-70.jpg',true),
('MH-069','Universal Pack','Medical Devices','Sterile, single-use surgical product manufactured under CE MDR and ISO 13485 quality systems. Custom configurations and private-label (OEM) production available on request.','https://medichall.com/images/products/69/643bdb6ca51851681644396-69.jpg',true),
('MH-057','C-Section Packs','Medical Devices','Sterile, single-use surgical product manufactured under CE MDR and ISO 13485 quality systems. Custom configurations and private-label (OEM) production available on request.','https://medichall.com/images/products/57/6436b001c21511681305601-57.jpg',true),
('MH-062','Laparoscopic Pack','Medical Devices','Sterile, single-use surgical product manufactured under CE MDR and ISO 13485 quality systems. Custom configurations and private-label (OEM) production available on request.','https://medichall.com/images/products/62/643bd82197cc91681643553-62.jpg',true),
('MH-071','By-Pass Pack','Medical Devices','Sterile, single-use surgical product manufactured under CE MDR and ISO 13485 quality systems. Custom configurations and private-label (OEM) production available on request.','https://medichall.com/images/products/71/643bdc6acb74e1681644650-71.jpg',true),
('MH-050','Angiography Pack','Medical Devices','Sterile, single-use surgical product manufactured under CE MDR and ISO 13485 quality systems. Custom configurations and private-label (OEM) production available on request.','https://medichall.com/images/products/50/6436ab1a5c3c11681304346-50.jpg',true),
('MH-056','Gynaecology Pack','Medical Devices','Sterile, single-use surgical product manufactured under CE MDR and ISO 13485 quality systems. Custom configurations and private-label (OEM) production available on request.','https://medichall.com/images/products/56/6436afa8370371681305512-56.jpg',true),
('MH-061','Cystoscopy Pack','Medical Devices','Sterile, single-use surgical product manufactured under CE MDR and ISO 13485 quality systems. Custom configurations and private-label (OEM) production available on request.','https://medichall.com/images/products/61/643bd7c4774821681643460-61.jpg',true),
('MH-060','T.U.R. Pack','Medical Devices','Sterile, single-use surgical product manufactured under CE MDR and ISO 13485 quality systems. Custom configurations and private-label (OEM) production available on request.','https://medichall.com/images/products/60/643bd7651135b1681643365-60.jpg',true),
('MH-054','Shoulder Arthroscopy Pack','Medical Devices','Sterile, single-use surgical product manufactured under CE MDR and ISO 13485 quality systems. Custom configurations and private-label (OEM) production available on request.','https://medichall.com/images/products/54/6436add1c5c1f1681305041-54.jpg',true),
('MH-053','Hip Pack','Medical Devices','Sterile, single-use surgical product manufactured under CE MDR and ISO 13485 quality systems. Custom configurations and private-label (OEM) production available on request.','https://medichall.com/images/products/53/6436ad7561c121681304949-53.jpg',true),
('MH-055','Extremity Pack','Medical Devices','Sterile, single-use surgical product manufactured under CE MDR and ISO 13485 quality systems. Custom configurations and private-label (OEM) production available on request.','https://medichall.com/images/products/55/6436aeb9444941681305273-55.jpg',true),
('MH-064','Chemotherapy Pack','Medical Devices','Sterile, single-use surgical product manufactured under CE MDR and ISO 13485 quality systems. Custom configurations and private-label (OEM) production available on request.','https://medichall.com/images/products/64/643bd926303b31681643814-64.jpg',true),
('MH-065','E.N.T Pack','Medical Devices','Sterile, single-use surgical product manufactured under CE MDR and ISO 13485 quality systems. Custom configurations and private-label (OEM) production available on request.','https://medichall.com/images/products/65/643bd97cade9c1681643900-65.jpg',true),
('MH-073','Thorax Pack','Medical Devices','Sterile, single-use surgical product manufactured under CE MDR and ISO 13485 quality systems. Custom configurations and private-label (OEM) production available on request.','https://medichall.com/images/products/73/643bdd1f273541681644831-73.jpg',true),
('MH-075','Sterile Gowns','Medical Devices','Sterile, single-use surgical product manufactured under CE MDR and ISO 13485 quality systems. Custom configurations and private-label (OEM) production available on request.','https://medichall.com/images/products/75/643bddd7537841681645015-75.jpg',true),
('MH-074','Non-Sterile Gowns','Medical Devices','Sterile, single-use surgical product manufactured under CE MDR and ISO 13485 quality systems. Custom configurations and private-label (OEM) production available on request.','https://medichall.com/images/products/74/643bdd766a21a1681644918-74.jpg',true),
('MH-076','Microscope Drapes','Medical Devices','Sterile, single-use surgical product manufactured under CE MDR and ISO 13485 quality systems. Custom configurations and private-label (OEM) production available on request.','https://medichall.com/images/products/76/643bde332f11e1681645107-76.jpg',true),
('MH-077','Camera Covers','Medical Devices','Sterile, single-use surgical product manufactured under CE MDR and ISO 13485 quality systems. Custom configurations and private-label (OEM) production available on request.','https://medichall.com/images/products/77/643bdea560bd51681645221-77.jpg',true),
('MH-044','Scopy / Fluoroscopy Drapes','Medical Devices','Sterile, single-use surgical product manufactured under CE MDR and ISO 13485 quality systems. Custom configurations and private-label (OEM) production available on request.','https://medichall.com/images/products/44/63f3c73fb717b1676920639-44.png',true),
('MH-068','Opthalmology Drape','Medical Devices','Sterile, single-use surgical product manufactured under CE MDR and ISO 13485 quality systems. Custom configurations and private-label (OEM) production available on request.','https://medichall.com/images/products/68/643bdafca474f1681644284-68.jpg',true),
('MH-040','Mayo Stand Cover','Medical Devices','Sterile, single-use surgical product manufactured under CE MDR and ISO 13485 quality systems. Custom configurations and private-label (OEM) production available on request.','https://medichall.com/images/products/40/63f3c552b37c11676920146-40.png',true),
('MH-043','Fluid Collection Pouches','Medical Devices','Sterile, single-use surgical product manufactured under CE MDR and ISO 13485 quality systems. Custom configurations and private-label (OEM) production available on request.','https://medichall.com/images/products/43/63f3c67494a3a1676920436-43.png',true),
('MH-085','Pleural (Chest) Drainage Systems','Medical Devices','Sterile, single-use surgical product manufactured under CE MDR and ISO 13485 quality systems. Custom configurations and private-label (OEM) production available on request.','https://medichall.com/images/products/85/647db70e38f371685960462-85.jpg',true),
('MH-086','ESU Pencil','Medical Devices','Sterile, single-use surgical product manufactured under CE MDR and ISO 13485 quality systems. Custom configurations and private-label (OEM) production available on request.','https://medichall.com/images/products/86/647db80328aa11685960707-86.jpg',true),
('MH-079','Sterilization Chemical Indicators','Sterilization','Sterilization assurance and CSSD product complying with relevant EN/ISO standards. Suitable for hospital central sterilization departments and device manufacturers.','https://medichall.com/images/products/79/647db07db8fbe1685958781-79.png',true),
('MH-082','Biological Indicators','Sterilization','Sterilization assurance and CSSD product complying with relevant EN/ISO standards. Suitable for hospital central sterilization departments and device manufacturers.','https://medichall.com/images/products/82/647db42b457f51685959723-82.png',true),
('MH-081','Autoclave Test Package (Bowie Dick / Helix)','Sterilization','Sterilization assurance and CSSD product complying with relevant EN/ISO standards. Suitable for hospital central sterilization departments and device manufacturers.','https://medichall.com/images/products/81/647db31adf0fa1685959450-81.jpg',true),
('MH-080','Autoclave Tapes','Sterilization','Sterilization assurance and CSSD product complying with relevant EN/ISO standards. Suitable for hospital central sterilization departments and device manufacturers.','https://medichall.com/images/products/80/647db19dc38831685959069-80.jpg',true),
('MH-078','Sterilization Reels, Pouches & Packaging','Sterilization','Sterilization assurance and CSSD product complying with relevant EN/ISO standards. Suitable for hospital central sterilization departments and device manufacturers.','https://medichall.com/images/products/78/643fbf87451d21681899399-78.jpg',true),
('MH-087','Washer Control Products','Sterilization','Sterilization assurance and CSSD product complying with relevant EN/ISO standards. Suitable for hospital central sterilization departments and device manufacturers.','https://medichall.com/images/products/87/647db8662e0811685960806-87.png',true),
('MH-083','Documentation Labels and Label Gun','Sterilization','Sterilization assurance and CSSD product complying with relevant EN/ISO standards. Suitable for hospital central sterilization departments and device manufacturers.','https://medichall.com/images/products/83/647db4c9cc4b01685959881-83.jpg',true),
('MH-084','Instrument Protector','Sterilization','Sterilization assurance and CSSD product complying with relevant EN/ISO standards. Suitable for hospital central sterilization departments and device manufacturers.','https://medichall.com/images/products/84/647db55f913ae1685960031-84.jpg',true),
('MH-088','Container Accessories (Seal / Filter)','Sterilization','Sterilization assurance and CSSD product complying with relevant EN/ISO standards. Suitable for hospital central sterilization departments and device manufacturers.','https://medichall.com/images/products/88/647db903ba6371685960963-88.jpg',true),
('MH-048','Vaccine Refrigerator','Cold Chain','Medical cold-chain equipment designed for safe storage of temperature-sensitive products, with monitoring and alarm options.','https://medichall.com/images/products/48/641dac8c39b951679666316-48.png',true),
('MH-049','Blood Bank Refrigerator','Cold Chain','Medical cold-chain equipment designed for safe storage of temperature-sensitive products, with monitoring and alarm options.',null,true),
('MH-042','OP-Tape','Raw Materials','Production input for medical device manufacturing lines. Technical specifications and samples available from the manufacturer.','https://medichall.com/images/products/42/63f3c5eaed2341676920298-42.png',true),
('MH-045','Double Sided Adhesive','Raw Materials','Production input for medical device manufacturing lines. Technical specifications and samples available from the manufacturer.','https://medichall.com/images/products/45/63f3c801124af1676920833-45.png',true)
on conflict (ref) do nothing;

insert into public.partners (name, type, is_active) values
('Grup A Medical','Medical device supplier',true),
('4A Medical','Medical device supplier',true),
('CoolerBox Company','Cold chain equipment',true),
('Medibant Medikal','Packaging & lamination',true),
('Telkar Çevre Sağlık','Service provider',true),
('MD Beans','Medical device supplier',true),
('Yaren Çörekoğlu','Supplier',true);
