-- DEPRECATED — DO NOT EXECUTE
--
-- This historical dashboard setup script previously duplicated the RFQ e-mail
-- trigger definitions and embedded a provider credential. The credential has
-- been removed from the working tree. The canonical, reproducible definitions
-- now live in:
--
--   supabase/migrations/202607090001_core_platform_baseline.sql
--
-- That migration reads the operator-managed Vault secret named
-- `medichall_resend_api_key` and becomes a safe no-op when the secret is not
-- configured. Never add a provider key, authorization header, or secret value
-- to this file. Existing installations must rotate any credential that ever
-- appeared in repository history before enabling the Vault-backed contract.
