-- ============================================================
-- MedicHall — Step 10: Buyer <-> Manufacturer chat on RFQs
-- Run ONCE in Supabase Dashboard -> SQL Editor
-- ============================================================

create table if not exists public.rfq_messages (
  id          bigint generated by default as identity primary key,
  rfq_id      bigint not null references public.rfq_requests(id) on delete cascade,
  sender_id   uuid not null references auth.users(id) on delete cascade,
  sender_role text not null default 'buyer',   -- 'buyer' | 'manufacturer'
  body        text not null,
  created_at  timestamptz not null default now()
);

alter table public.rfq_messages enable row level security;

-- Only the two participants of an RFQ (and the admin) can read its messages
create policy "participants read messages" on public.rfq_messages
  for select to authenticated using (
    exists (
      select 1 from public.rfq_requests r
      where r.id = rfq_id and (
        r.user_id = auth.uid()
        or r.company_id in (select id from public.companies where owner_id = auth.uid())
        or public.is_admin()
      )
    )
  );

-- Only participants can write, and only as themselves
create policy "participants send messages" on public.rfq_messages
  for insert to authenticated with check (
    sender_id = auth.uid()
    and exists (
      select 1 from public.rfq_requests r
      where r.id = rfq_id and (
        r.user_id = auth.uid()
        or r.company_id in (select id from public.companies where owner_id = auth.uid())
        or public.is_admin()
      )
    )
  );
