-- ============================================================
-- MedicHall — Step 3: DATABASE v2 (Manufacturer Portal foundation)
-- Run this ONCE in Supabase Dashboard -> SQL Editor
--
-- !! ONE THING TO EDIT BEFORE RUNNING !!
-- At the very bottom, replace "kaanakgun96@gmail.com" with the
-- email you use to log in to admin.html — otherwise your own
-- admin panel loses write access.
-- ============================================================

-- ------------------------------------------------------------
-- 1) ADMINS — who is allowed to manage everything
-- ------------------------------------------------------------
create table if not exists public.admins (
  user_id uuid primary key references auth.users(id) on delete cascade
);
alter table public.admins enable row level security;
-- (no policies on purpose: only the dashboard / this function can touch it)

create or replace function public.is_admin()
returns boolean
language sql stable security definer
set search_path = public
as $$
  select exists (select 1 from public.admins where user_id = auth.uid());
$$;

-- ------------------------------------------------------------
-- 2) COMPANIES — manufacturer profiles
-- ------------------------------------------------------------
create table if not exists public.companies (
  id             bigint generated by default as identity primary key,
  owner_id       uuid references auth.users(id) on delete set null,
  name           text not null,
  type           text,                      -- e.g. "Medical device manufacturer"
  description    text,
  website        text,
  contact_email  text,
  phone          text,
  country        text default 'Türkiye',
  city           text,
  certifications text,                      -- e.g. "CE MDR, ISO 13485"
  logo_url       text,
  is_approved    boolean not null default false,  -- YOU approve from admin panel
  is_active      boolean not null default true,
  created_at     timestamptz not null default now()
);
alter table public.companies enable row level security;

-- ------------------------------------------------------------
-- 3) OWNERSHIP LINKS — products & RFQs belong to companies
--    (company_id NULL = managed by MedicHall admin, like today)
-- ------------------------------------------------------------
alter table public.products
  add column if not exists company_id bigint references public.companies(id) on delete set null;

alter table public.rfq_requests
  add column if not exists company_id bigint references public.companies(id) on delete set null;

-- ------------------------------------------------------------
-- 4) SECURITY POLICIES v2
--    Replace the old "any logged-in user can manage everything"
--    rules with role-aware rules.
-- ------------------------------------------------------------

-- drop old broad policies (from Step 2)
drop policy if exists "admin manage products" on public.products;
drop policy if exists "admin manage partners" on public.partners;
drop policy if exists "admin read rfq"        on public.rfq_requests;
drop policy if exists "admin delete rfq"      on public.rfq_requests;

-- PRODUCTS ----------------------------------------------------
-- public can see active products; a company's products only show
-- once the company is approved & active
drop policy if exists "public read products" on public.products;
create policy "public read products" on public.products
  for select using (
    is_active = true
    and (
      company_id is null
      or exists (select 1 from public.companies c
                 where c.id = company_id and c.is_approved and c.is_active)
    )
  );

create policy "admin all products" on public.products
  for all to authenticated
  using (public.is_admin()) with check (public.is_admin());

create policy "owner manage own products" on public.products
  for all to authenticated
  using (company_id in (select id from public.companies where owner_id = auth.uid()))
  with check (company_id in (select id from public.companies where owner_id = auth.uid()));

-- PARTNERS (homepage strip) — admin only ----------------------
create policy "admin all partners" on public.partners
  for all to authenticated
  using (public.is_admin()) with check (public.is_admin());

-- COMPANIES ---------------------------------------------------
create policy "public read companies" on public.companies
  for select using (is_approved = true and is_active = true);

create policy "owner read own company" on public.companies
  for select to authenticated using (owner_id = auth.uid());

create policy "owner insert own company" on public.companies
  for insert to authenticated with check (owner_id = auth.uid());

create policy "owner update own company" on public.companies
  for update to authenticated
  using (owner_id = auth.uid()) with check (owner_id = auth.uid());
  -- note: owners cannot change is_approved in practice because the
  -- portal UI never sends it; approval is done from the admin panel.

create policy "admin all companies" on public.companies
  for all to authenticated
  using (public.is_admin()) with check (public.is_admin());

-- RFQ REQUESTS ------------------------------------------------
create policy "admin read rfq" on public.rfq_requests
  for select to authenticated using (public.is_admin());

create policy "admin delete rfq" on public.rfq_requests
  for delete to authenticated using (public.is_admin());

create policy "owner read own rfq" on public.rfq_requests
  for select to authenticated
  using (company_id in (select id from public.companies where owner_id = auth.uid()));

-- ------------------------------------------------------------
-- 5) MAKE *YOU* THE ADMIN  — EDIT THE EMAIL BELOW, THEN RUN
-- ------------------------------------------------------------
insert into public.admins (user_id)
select id from auth.users where email = 'kaanakgun96@gmail.com'
on conflict (user_id) do nothing;

-- ------------------------------------------------------------
-- 6) VERIFY (run these after; both should return 1 row)
-- ------------------------------------------------------------
-- select * from public.admins;
-- select count(*) from public.companies;
