-- ============================================================
-- MedicHall — Step 9: Buyer accounts & favorites
-- Run ONCE in Supabase Dashboard -> SQL Editor
-- ============================================================

-- 1) Buyer profiles
create table if not exists public.buyer_profiles (
  user_id      uuid primary key references auth.users(id) on delete cascade,
  full_name    text,
  company_name text,
  country      text,
  created_at   timestamptz not null default now()
);
alter table public.buyer_profiles enable row level security;

create policy "buyer manage own profile" on public.buyer_profiles
  for all to authenticated
  using (user_id = auth.uid()) with check (user_id = auth.uid());

create policy "admin read buyer profiles" on public.buyer_profiles
  for select to authenticated using (public.is_admin());

-- 2) Favorites (saved products)
create table if not exists public.favorites (
  id         bigint generated by default as identity primary key,
  user_id    uuid not null references auth.users(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (user_id, product_id)
);
alter table public.favorites enable row level security;

create policy "user manages own favorites" on public.favorites
  for all to authenticated
  using (user_id = auth.uid()) with check (user_id = auth.uid());

-- 3) Tie RFQs to the buyer account that sent them (when logged in)
alter table public.rfq_requests
  add column if not exists user_id uuid references auth.users(id) on delete set null;

create policy "buyer read own rfq" on public.rfq_requests
  for select to authenticated using (user_id = auth.uid());
