-- ============================================================
-- MedicHall — Step 8: Banner advertising system
-- Run ONCE in Supabase Dashboard -> SQL Editor
-- ============================================================

create table if not exists public.banners (
  id         bigint generated by default as identity primary key,
  title      text not null,              -- internal name, e.g. "4A Medical — spring campaign"
  image_url  text not null,
  link_url   text,                       -- where the banner clicks through to
  placement  text not null default 'home',   -- 'home' | 'catalog' | 'companies'
  is_active  boolean not null default true,
  ends_at    timestamptz,                -- optional end date; hidden automatically after
  created_at timestamptz not null default now()
);

alter table public.banners enable row level security;

-- everyone sees active banners; only the admin manages them
create policy "public read banners" on public.banners
  for select using (is_active = true);

create policy "admin all banners" on public.banners
  for all to authenticated
  using (public.is_admin()) with check (public.is_admin());
