-- ============================================================
-- MedicHall — Step 15: multiple PDF catalogs per company
-- Run ONCE in Supabase Dashboard -> SQL Editor
-- ============================================================

create table if not exists public.company_catalogs (
  id         bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id) on delete cascade,
  title      text not null default 'Product Catalog',
  file_url   text not null,
  thumb_url  text,                 -- first-page cover image (auto-generated)
  created_at timestamptz not null default now()
);

alter table public.company_catalogs enable row level security;

-- visitors see catalogs of approved companies
create policy "public read catalogs" on public.company_catalogs
  for select using (
    exists (select 1 from public.companies c
            where c.id = company_id and c.is_approved and c.is_active)
  );

-- owners manage their own catalogs
create policy "owner manage catalogs" on public.company_catalogs
  for all to authenticated
  using (company_id in (select id from public.companies where owner_id = auth.uid()))
  with check (company_id in (select id from public.companies where owner_id = auth.uid()));

-- admin manages all
create policy "admin all catalogs" on public.company_catalogs
  for all to authenticated
  using (public.is_admin()) with check (public.is_admin());

-- migrate existing single catalogs into the new table
insert into public.company_catalogs (company_id, title, file_url)
select id, 'Product Catalog', catalog_url
from public.companies
where catalog_url is not null
  and not exists (select 1 from public.company_catalogs cc
                  where cc.company_id = companies.id and cc.file_url = companies.catalog_url);
