-- ============================================================
-- MedicHall — Step 20: Smart RFQ v2
--  · structured request fields (quantity, Incoterm, destination…)
--  · multi-send groups (one request -> many manufacturers)
--  · structured offers from manufacturers + comparison
--  · e-mail to buyer when an offer arrives
-- Run ONCE in Supabase Dashboard -> SQL Editor
-- ============================================================

-- 1) Structured fields on requests
alter table public.rfq_requests
  add column if not exists quantity     text,
  add column if not exists incoterm     text,
  add column if not exists destination  text,
  add column if not exists target_price text,
  add column if not exists req_certs    text,
  add column if not exists group_id     uuid;

-- 2) Offers from manufacturers
create table if not exists public.rfq_offers (
  id          bigint generated by default as identity primary key,
  rfq_id      bigint not null references public.rfq_requests(id) on delete cascade,
  company_id  bigint not null references public.companies(id) on delete cascade,
  unit_price  numeric,
  currency    text not null default 'USD',
  moq         text,
  lead_time   text,
  valid_until date,
  notes       text,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),
  unique (rfq_id, company_id)
);

alter table public.rfq_offers enable row level security;

-- buyer sees offers on their own requests
drop policy if exists "buyer read offers" on public.rfq_offers;
create policy "buyer read offers" on public.rfq_offers
  for select to authenticated using (
    exists (select 1 from public.rfq_requests r
            where r.id = rfq_id and r.user_id = auth.uid())
  );

-- manufacturer manages the offer on requests addressed to their company
drop policy if exists "manufacturer manage own offers" on public.rfq_offers;
create policy "manufacturer manage own offers" on public.rfq_offers
  for all to authenticated
  using (company_id in (select id from public.companies where owner_id = auth.uid()))
  with check (
    company_id in (select id from public.companies where owner_id = auth.uid())
    and exists (select 1 from public.rfq_requests r
                where r.id = rfq_id and r.company_id = rfq_offers.company_id)
  );

-- admin oversight
drop policy if exists "admin all offers" on public.rfq_offers;
create policy "admin all offers" on public.rfq_offers
  for all to authenticated
  using (public.is_admin()) with check (public.is_admin());

-- keep updated_at fresh
create or replace function public.trg_offer_touch()
returns trigger language plpgsql as $$
begin new.updated_at := now(); return new; end $$;

drop trigger if exists offer_touch on public.rfq_offers;
create trigger offer_touch before update on public.rfq_offers
  for each row execute function public.trg_offer_touch();

-- 3) E-mail the buyer when an offer arrives
create or replace function public.trg_offer_created()
returns trigger
language plpgsql security definer
set search_path = public
as $$
declare
  v_to text; v_product text; v_company text;
begin
  select u.email, r.product_name into v_to, v_product
  from public.rfq_requests r
  left join auth.users u on u.id = r.user_id
  where r.id = new.rfq_id;

  if v_to is null then return new; end if;

  select name into v_company from public.companies where id = new.company_id;

  perform public.notify_email(
    v_to,
    'You received an offer — ' || coalesce(v_product, 'your inquiry'),
    '<div style="font-family:sans-serif;line-height:1.6">'
    || '<h2 style="color:#003E52">New offer received</h2>'
    || '<p><b>' || coalesce(v_company,'A manufacturer') || '</b> sent an offer for <b>'
    || coalesce(v_product, 'your inquiry') || '</b>.</p>'
    || '<p style="background:#EFF6F9;padding:12px;border-radius:8px">'
    || coalesce(new.unit_price::text || ' ' || new.currency || ' / unit', 'See details')
    || coalesce(' · MOQ: ' || new.moq, '')
    || coalesce(' · Lead time: ' || new.lead_time, '') || '</p>'
    || '<p><a href="' || public.mh_site_url() || '/portal#inbox" '
    || 'style="background:#4298CC;color:#fff;padding:10px 22px;border-radius:8px;text-decoration:none">Compare offers on MedicHall</a></p>'
    || '</div>'
  );
  return new;
end $$;

drop trigger if exists offer_created_email on public.rfq_offers;
create trigger offer_created_email
  after insert on public.rfq_offers
  for each row execute function public.trg_offer_created();
