-- MedicHall Document Intelligence v3
--
-- Additive large-document inspection, candidate-page selection, resumable
-- chunk extraction, deterministic merging, and processing observability.
-- Existing queue/status RPC signatures and legacy extraction columns remain
-- unchanged. No existing tender, document, evidence, or score is rewritten.

begin;

alter table public.tender_documents
  add column if not exists content_sha256 text,
  add column if not exists page_count integer,
  add column if not exists inspection_status text,
  add column if not exists inspection_version text,
  add column if not exists last_inspected_at timestamptz;

do $constraints$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'tender_documents_content_sha256_check'
  ) then
    alter table public.tender_documents
      add constraint tender_documents_content_sha256_check
      check (
        content_sha256 is null
        or content_sha256 ~ '^[a-f0-9]{64}$'
      );
  end if;
  if not exists (
    select 1 from pg_constraint
    where conname = 'tender_documents_page_count_check'
  ) then
    alter table public.tender_documents
      add constraint tender_documents_page_count_check
      check (page_count is null or page_count > 0);
  end if;
  if not exists (
    select 1 from pg_constraint
    where conname = 'tender_documents_inspection_status_check'
  ) then
    alter table public.tender_documents
      add constraint tender_documents_inspection_status_check
      check (
        inspection_status is null
        or inspection_status in ('completed', 'partial', 'failed')
      );
  end if;
end
$constraints$;

create index if not exists tender_documents_content_hash_idx
  on public.tender_documents(content_sha256)
  where content_sha256 is not null;

create table if not exists public.tender_document_inspections (
  id bigint generated by default as identity primary key,
  tender_id bigint not null references public.tenders(id) on delete cascade,
  document_id bigint references public.tender_documents(id) on delete cascade,
  source_document_key text not null,
  content_sha256 text not null check (
    content_sha256 ~ '^[a-f0-9]{64}$'
  ),
  inspection_version text not null,
  status text not null default 'completed' check (
    status in ('completed', 'partial', 'failed')
  ),
  page_count integer check (page_count is null or page_count > 0),
  scanned_page_count integer not null default 0 check (
    scanned_page_count >= 0
  ),
  inspection_metadata jsonb not null default '{}'::jsonb,
  document_outline jsonb not null default '[]'::jsonb,
  table_of_contents_pages integer[] not null default '{}',
  page_signals jsonb not null default '[]'::jsonb,
  ranked_page_ranges jsonb not null default '[]'::jsonb,
  config_snapshot jsonb not null default '{}'::jsonb,
  processing_duration_ms bigint check (
    processing_duration_ms is null or processing_duration_ms >= 0
  ),
  error_message text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (source_document_key, content_sha256, inspection_version)
);

create index if not exists tender_document_inspections_tender_idx
  on public.tender_document_inspections(
    tender_id,
    created_at desc
  );

create index if not exists tender_document_inspections_reuse_idx
  on public.tender_document_inspections(
    content_sha256,
    inspection_version,
    updated_at desc
  )
  where status in ('completed', 'partial');

create table if not exists public.tender_document_analysis_chunks (
  id bigint generated by default as identity primary key,
  job_id bigint not null
    references public.tender_document_analysis_jobs(id) on delete cascade,
  inspection_id bigint
    references public.tender_document_inspections(id) on delete set null,
  tender_id bigint not null references public.tenders(id) on delete cascade,
  document_id bigint references public.tender_documents(id) on delete cascade,
  source_document_key text not null,
  content_sha256 text not null check (
    content_sha256 ~ '^[a-f0-9]{64}$'
  ),
  chunk_index integer not null check (chunk_index >= 0),
  page_start integer,
  page_end integer,
  page_numbers integer[] not null default '{}',
  priority_score numeric not null default 0,
  selection_reasons text[] not null default '{}',
  input_hash text not null check (input_hash ~ '^[a-f0-9]{64}$'),
  status text not null default 'queued' check (
    status in ('queued', 'processing', 'completed', 'failed')
  ),
  attempt_count integer not null default 0 check (attempt_count >= 0),
  resume_count integer not null default 0 check (resume_count >= 0),
  lease_expires_at timestamptz,
  model_name text,
  extraction_version text not null,
  prompt_schema_version text not null,
  normalized_result jsonb not null default '{}'::jsonb,
  confidence_score integer check (
    confidence_score is null or confidence_score between 0 and 100
  ),
  provider_request_id text,
  provider_usage jsonb not null default '{}'::jsonb,
  input_tokens bigint not null default 0 check (input_tokens >= 0),
  output_tokens bigint not null default 0 check (output_tokens >= 0),
  estimated_cost_usd numeric(14, 6) not null default 0 check (
    estimated_cost_usd >= 0
  ),
  reused_from_chunk_id bigint
    references public.tender_document_analysis_chunks(id) on delete set null,
  error_code text,
  error_message text,
  started_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (
    (page_start is null and page_end is null)
    or (
      page_start is not null
      and page_end is not null
      and page_start > 0
      and page_end >= page_start
    )
  ),
  unique (job_id, source_document_key, input_hash)
);

create index if not exists tender_analysis_chunks_job_status_idx
  on public.tender_document_analysis_chunks(
    job_id,
    status,
    priority_score desc,
    chunk_index
  );

create index if not exists tender_analysis_chunks_reuse_idx
  on public.tender_document_analysis_chunks(
    input_hash,
    extraction_version,
    completed_at desc
  )
  where status = 'completed';

create index if not exists tender_analysis_chunks_expired_lease_idx
  on public.tender_document_analysis_chunks(lease_expires_at)
  where status = 'processing';

alter table public.tender_document_analysis_jobs
  add column if not exists total_pages integer not null default 0,
  add column if not exists selected_pages integer not null default 0,
  add column if not exists ignored_pages integer not null default 0,
  add column if not exists ai_pages_processed integer not null default 0,
  add column if not exists chunks_total integer not null default 0,
  add column if not exists chunks_completed integer not null default 0,
  add column if not exists chunks_failed integer not null default 0,
  add column if not exists chunks_reused integer not null default 0,
  add column if not exists resume_count integer not null default 0,
  add column if not exists estimated_ai_cost_usd numeric(14, 6)
    not null default 0,
  add column if not exists processing_statistics jsonb
    not null default '{}'::jsonb,
  add column if not exists v3_plan_hash text,
  add column if not exists v3_merge_result jsonb
    not null default '{}'::jsonb,
  add column if not exists last_resumed_at timestamptz;

do $constraints$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'tender_analysis_jobs_v3_counts_check'
  ) then
    alter table public.tender_document_analysis_jobs
      add constraint tender_analysis_jobs_v3_counts_check
      check (
        total_pages >= 0
        and selected_pages >= 0
        and ignored_pages >= 0
        and ai_pages_processed >= 0
        and chunks_total >= 0
        and chunks_completed >= 0
        and chunks_failed >= 0
        and chunks_reused >= 0
        and resume_count >= 0
        and estimated_ai_cost_usd >= 0
      );
  end if;
  if not exists (
    select 1 from pg_constraint
    where conname = 'tender_analysis_jobs_v3_plan_hash_check'
  ) then
    alter table public.tender_document_analysis_jobs
      add constraint tender_analysis_jobs_v3_plan_hash_check
      check (
        v3_plan_hash is null
        or v3_plan_hash ~ '^[a-f0-9]{64}$'
      );
  end if;
end
$constraints$;

alter table public.tenders
  add column if not exists document_extraction_v3 jsonb
    not null default '{}'::jsonb;

alter table public.tender_document_inspections enable row level security;
alter table public.tender_document_analysis_chunks enable row level security;

drop policy if exists "admins read document inspections"
  on public.tender_document_inspections;
create policy "admins read document inspections"
on public.tender_document_inspections for select
to authenticated
using (public.is_admin());

drop policy if exists "admins read document analysis chunks"
  on public.tender_document_analysis_chunks;
create policy "admins read document analysis chunks"
on public.tender_document_analysis_chunks for select
to authenticated
using (public.is_admin());

revoke all on public.tender_document_inspections
  from public, anon, authenticated;
revoke all on public.tender_document_analysis_chunks
  from public, anon, authenticated;
grant select on public.tender_document_inspections to authenticated;
grant select on public.tender_document_analysis_chunks to authenticated;
grant all on public.tender_document_inspections to service_role;
grant all on public.tender_document_analysis_chunks to service_role;
grant usage, select on sequence
  public.tender_document_inspections_id_seq to service_role;
grant usage, select on sequence
  public.tender_document_analysis_chunks_id_seq to service_role;

create or replace function public.claim_tender_document_analysis_chunk_v3(
  p_job_id bigint,
  p_chunk_id bigint,
  p_lease_seconds integer,
  p_max_attempts integer
)
returns public.tender_document_analysis_chunks
language plpgsql
security definer
set search_path = public
as $$
declare
  v_chunk public.tender_document_analysis_chunks;
begin
  if coalesce(auth.jwt() ->> 'role', '') <> 'service_role'
    and not public.is_admin()
  then
    raise exception 'Access denied';
  end if;

  if p_lease_seconds < 30 or p_lease_seconds > 1800
    or p_max_attempts < 1 or p_max_attempts > 10
  then
    raise exception 'Invalid chunk lease configuration';
  end if;

  update public.tender_document_analysis_chunks chunk
  set
    status = 'processing',
    attempt_count = chunk.attempt_count + 1,
    resume_count = chunk.resume_count + case
      when chunk.status = 'processing' then 1
      else 0
    end,
    lease_expires_at = now() + make_interval(secs => p_lease_seconds),
    started_at = coalesce(chunk.started_at, now()),
    error_code = null,
    error_message = null,
    updated_at = now()
  where chunk.id = p_chunk_id
    and chunk.job_id = p_job_id
    and chunk.attempt_count < p_max_attempts
    and (
      chunk.status in ('queued', 'failed')
      or (
        chunk.status = 'processing'
        and chunk.lease_expires_at < now()
      )
    )
  returning chunk.* into v_chunk;

  return v_chunk;
end;
$$;

revoke all on function public.claim_tender_document_analysis_chunk_v3(
  bigint,
  bigint,
  integer,
  integer
) from public, anon, authenticated;
grant execute on function public.claim_tender_document_analysis_chunk_v3(
  bigint,
  bigint,
  integer,
  integer
) to service_role;

update public.pipeline_versions
set is_repository_current = false
where component in ('document_parsing', 'ai_extraction')
  and is_repository_current;

insert into public.pipeline_versions (
  component,
  version_identifier,
  semantic_version,
  content_sha256,
  source_path,
  migration_path,
  is_repository_current,
  live_verification_status,
  metadata
)
values
  (
    'document_parsing',
    'document-chunking-v3.0.0',
    '3.0.0',
    '32622c0ccceadb0caee04d65848a31a297d3bb3b3f230637ad4ca3e3ca3ddd1b',
    'supabase/functions/_shared/pdf-processing-v3.ts',
    'supabase/migrations/202607230004_document_intelligence_v3.sql',
    true,
    'repository_only',
    '{"inspection_version":"document-inspection-v3.0.0","page_count_rejection":false,"supports_resumable_chunks":true,"related_source_hash":"8cc9093646608470a2377a733cbae3ff3499aad55485eb5de177e428e58439d4"}'::jsonb
  ),
  (
    'ai_extraction',
    'tender-extraction-v3.0.0',
    '3.0.0',
    '24a8ee04fb054e8ed1786f7bd2bbaf8b10743d722c93b993b886946bea735e6c',
    'supabase/functions/tender-document-engine/index.ts',
    'supabase/migrations/202607230004_document_intelligence_v3.sql',
    true,
    'repository_only',
    '{"prompt_schema":"medichall-tender-facts-v3","provider":"Anthropic","whole_large_pdf_sent":false,"deterministic_merge":true,"manifest_hash":"225ff44d2719b387c831bd5878e583679442715d0e2bd33b2f2ad4e5afa363ef"}'::jsonb
  )
on conflict (component, version_identifier) do update set
  semantic_version = excluded.semantic_version,
  content_sha256 = excluded.content_sha256,
  source_path = excluded.source_path,
  migration_path = excluded.migration_path,
  is_repository_current = excluded.is_repository_current,
  live_verification_status = excluded.live_verification_status,
  metadata = excluded.metadata;

commit;

-- Rollback:
--   1. Redeploy the preceding tender-document-engine bundle.
--   2. Stop creating v3 inspections/chunks and calling the claim RPC.
--   3. Mark the v3 parsing/extraction pipeline versions non-current and
--      restore their v2 predecessors as repository-current.
--   4. Keep the additive inspection/chunk/job columns and completed chunk
--      results for audit and resumability. Do not delete tender data,
--      evidence, scores, jobs, or migration history.
