-- Deterministic lot-level tender matching.
-- This is additive: legacy opportunity matches and Match Score v2 remain the
-- overall source of truth, while each extracted lot gets an auditable result.

begin;

create table if not exists public.tender_lot_matches (
  id bigint generated by default as identity primary key,
  company_id bigint not null
    references public.companies(id) on delete cascade,
  tender_id bigint not null
    references public.tenders(id) on delete cascade,
  lot_key text not null check (
    length(lot_key) between 1 and 300
  ),
  lot_number text,
  lot_title text not null,
  status text not null check (
    status in ('completed', 'failed', 'superseded')
  ),
  match_score integer check (
    match_score is null or match_score between 0 and 100
  ),
  recommendation text check (
    recommendation is null
    or recommendation in (
      'strong_match',
      'good_match',
      'possible_match',
      'weak_match',
      'not_recommended'
    )
  ),
  confidence_score integer check (
    confidence_score is null or confidence_score between 0 and 100
  ),
  best_company_product_id bigint
    references public.products(id) on delete set null,
  best_company_product_name text,
  score_components jsonb not null default '{}'::jsonb,
  matched_requirements jsonb not null default '[]'::jsonb,
  gaps jsonb not null default '[]'::jsonb,
  blockers jsonb not null default '[]'::jsonb,
  unknowns jsonb not null default '[]'::jsonb,
  tender_evidence jsonb not null default '[]'::jsonb,
  company_evidence jsonb not null default '[]'::jsonb,
  normalized_lot jsonb not null default '{}'::jsonb,
  input_hash text not null check (input_hash ~ '^[a-f0-9]{64}$'),
  calculation_version text not null,
  calculation_error text,
  trace_id uuid
    references public.pipeline_runs(trace_id) on delete set null,
  calculated_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (company_id, tender_id, lot_key, calculation_version),
  check (
    (
      status = 'completed'
      and match_score is not null
      and recommendation is not null
      and confidence_score is not null
      and calculation_error is null
    )
    or (
      status = 'failed'
      and match_score is null
      and recommendation is null
      and confidence_score is null
      and calculation_error is not null
    )
    or status = 'superseded'
  )
);

create index if not exists tender_lot_matches_company_tender_idx
  on public.tender_lot_matches (
    company_id,
    tender_id,
    calculation_version,
    match_score desc
  );

create index if not exists tender_lot_matches_tender_idx
  on public.tender_lot_matches (
    tender_id,
    calculation_version,
    lot_key
  );

drop trigger if exists tender_lot_matches_set_updated_at
  on public.tender_lot_matches;
create trigger tender_lot_matches_set_updated_at
before update on public.tender_lot_matches
for each row execute function public.set_updated_at();

alter table public.tender_lot_matches enable row level security;

drop policy if exists "owners and admins read tender lot matches"
  on public.tender_lot_matches;
create policy "owners and admins read tender lot matches"
on public.tender_lot_matches
for select to authenticated
using (
  public.is_admin()
  or exists (
    select 1
    from public.companies company
    where company.id = tender_lot_matches.company_id
      and company.owner_id = auth.uid()
  )
);

revoke all on table public.tender_lot_matches
from public, anon, authenticated;
grant select, insert, update on table public.tender_lot_matches
to service_role;
grant usage, select on sequence public.tender_lot_matches_id_seq
to service_role;

alter table public.opportunity_match_scores_v2
  add column if not exists lot_match_summary jsonb
    not null default '{}'::jsonb,
  add column if not exists lot_match_calculation_version text,
  add column if not exists lot_matches_calculated_at timestamptz;

comment on table public.tender_lot_matches is
  'Deterministic per-lot comparisons derived only from persisted extraction and company catalog data.';
comment on column public.tender_lot_matches.normalized_lot is
  'Private calculation input retained for reproducibility; accessible only to the service role and omitted from the authenticated read RPC.';
comment on column public.tender_lot_matches.input_hash is
  'SHA-256 of the calculation version, normalized lot, and company comparison input.';

create or replace function public.get_tender_lot_matches_v1(
  p_company_id bigint,
  p_tender_id bigint
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_lots jsonb;
  v_summary jsonb;
begin
  if not (
    public.is_admin()
    or coalesce(auth.jwt() ->> 'role', '') = 'service_role'
    or exists (
      select 1
      from public.companies company
      where company.id = p_company_id
        and company.owner_id = auth.uid()
    )
  ) then
    raise exception 'Access denied';
  end if;

  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'lot_key', lot_match.lot_key,
        'lot_number', lot_match.lot_number,
        'lot_title', lot_match.lot_title,
        'status', lot_match.status,
        'match_score', lot_match.match_score,
        'recommendation', lot_match.recommendation,
        'confidence_score', lot_match.confidence_score,
        'best_company_product_id', lot_match.best_company_product_id,
        'best_company_product_name', lot_match.best_company_product_name,
        'score_components', lot_match.score_components,
        'matched_requirements', lot_match.matched_requirements,
        'gaps', lot_match.gaps,
        'blockers', lot_match.blockers,
        'unknowns', lot_match.unknowns,
        'tender_evidence', lot_match.tender_evidence,
        'company_evidence', lot_match.company_evidence,
        'calculation_version', lot_match.calculation_version,
        'calculation_error', lot_match.calculation_error,
        'calculated_at', lot_match.calculated_at
      )
      order by
        (lot_match.lot_number is null),
        lot_match.lot_number,
        lot_match.lot_key
    ),
    '[]'::jsonb
  )
  into v_lots
  from public.tender_lot_matches lot_match
  where lot_match.company_id = p_company_id
    and lot_match.tender_id = p_tender_id
    and lot_match.calculation_version = 'lot-match-v1'
    and lot_match.status in ('completed', 'failed');

  select coalesce(score.lot_match_summary, '{}'::jsonb)
  into v_summary
  from public.opportunity_match_scores_v2 score
  where score.company_id = p_company_id
    and score.tender_id = p_tender_id;

  return jsonb_build_object(
    'company_id', p_company_id,
    'tender_id', p_tender_id,
    'calculation_version', 'lot-match-v1',
    'summary', coalesce(v_summary, '{}'::jsonb),
    'lots', v_lots
  );
end;
$$;

revoke all on function public.get_tender_lot_matches_v1(bigint, bigint)
from public, anon;
grant execute on function public.get_tender_lot_matches_v1(bigint, bigint)
to authenticated, service_role;

commit;

-- Rollback (manual, only if application readers no longer use the RPC):
-- begin;
-- drop function if exists public.get_tender_lot_matches_v1(bigint, bigint);
-- alter table public.opportunity_match_scores_v2
--   drop column if exists lot_matches_calculated_at,
--   drop column if exists lot_match_calculation_version,
--   drop column if exists lot_match_summary;
-- drop table if exists public.tender_lot_matches;
-- commit;
