begin;

create table if not exists public.tender_document_discovery_jobs (
  id bigint generated by default as identity primary key,
  tender_id bigint not null references public.tenders(id) on delete cascade,
  company_id bigint references public.companies(id) on delete set null,
  requested_by uuid references auth.users(id) on delete set null,
  status text not null default 'queued'
    check (status in ('queued','processing','completed','partial','failed')),
  source_url text,
  pages_scanned integer not null default 0,
  links_examined integer not null default 0,
  documents_found integer not null default 0,
  error_message text,
  started_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.tender_document_discovery_jobs enable row level security;

drop policy if exists "users read own discovery jobs"
on public.tender_document_discovery_jobs;

create policy "users read own discovery jobs"
on public.tender_document_discovery_jobs
for select to authenticated
using (
  public.is_admin()
  or requested_by = auth.uid()
  or exists (
    select 1 from public.companies c
    where c.id = company_id and c.owner_id = auth.uid()
  )
);

create or replace function public.queue_tender_document_discovery(
  p_tender_id bigint,
  p_company_id bigint
)
returns public.tender_document_discovery_jobs
language plpgsql
security definer
set search_path = public
as $$
declare
  v_tender public.tenders;
  v_job public.tender_document_discovery_jobs;
begin
  if not (
    public.is_admin()
    or exists (
      select 1 from public.companies c
      where c.id = p_company_id and c.owner_id = auth.uid()
    )
  ) then
    raise exception 'Access denied';
  end if;

  select * into v_tender from public.tenders where id = p_tender_id;
  if v_tender.id is null then raise exception 'Tender not found'; end if;
  if nullif(trim(v_tender.source_url), '') is null then
    raise exception 'Tender source URL is missing';
  end if;

  select * into v_job
  from public.tender_document_discovery_jobs
  where tender_id = p_tender_id
    and company_id = p_company_id
    and status in ('queued','processing')
  order by created_at desc
  limit 1;

  if v_job.id is not null then return v_job; end if;

  insert into public.tender_document_discovery_jobs (
    tender_id, company_id, requested_by, source_url
  )
  values (p_tender_id, p_company_id, auth.uid(), v_tender.source_url)
  returning * into v_job;

  return v_job;
end;
$$;

revoke all on function public.queue_tender_document_discovery(bigint,bigint) from public;
grant execute on function public.queue_tender_document_discovery(bigint,bigint) to authenticated;

create or replace function public.get_tender_document_discovery_status(
  p_tender_id bigint,
  p_company_id bigint
)
returns table (
  job_id bigint,
  status text,
  pages_scanned integer,
  links_examined integer,
  documents_found integer,
  error_message text,
  completed_at timestamptz
)
language sql
security definer
set search_path = public
as $$
  select j.id,j.status,j.pages_scanned,j.links_examined,j.documents_found,
         j.error_message,j.completed_at
  from public.tender_document_discovery_jobs j
  where j.tender_id = p_tender_id
    and j.company_id = p_company_id
    and (
      public.is_admin()
      or j.requested_by = auth.uid()
      or exists (
        select 1 from public.companies c
        where c.id = j.company_id and c.owner_id = auth.uid()
      )
    )
  order by j.created_at desc
  limit 1;
$$;

revoke all on function public.get_tender_document_discovery_status(bigint,bigint) from public;
grant execute on function public.get_tender_document_discovery_status(bigint,bigint) to authenticated;

commit;
