-- MedicHall Sprint 2 enterprise marketplace contracts.
-- Adds user-scoped company following without widening public company access.

begin;

create table if not exists public.company_follows (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  company_id bigint not null references public.companies(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (user_id, company_id)
);

create index if not exists company_follows_user_created_idx
  on public.company_follows(user_id, created_at desc);
create index if not exists company_follows_company_idx
  on public.company_follows(company_id);

alter table public.company_follows enable row level security;

drop policy if exists "users read own company follows"
  on public.company_follows;
create policy "users read own company follows"
on public.company_follows for select to authenticated
using (user_id = auth.uid());

-- Browser mutation is intentionally exposed only through the two RPCs below.
revoke all on table public.company_follows
  from public, anon, authenticated;
grant select on table public.company_follows to authenticated;
grant all on table public.company_follows to service_role;
grant usage, select on sequence public.company_follows_id_seq to service_role;

create or replace function public.follow_company(p_company_id bigint)
returns bigint
language plpgsql
security definer
set search_path = public, pg_temp
as $function$
declare
  v_user_id uuid := auth.uid();
begin
  if v_user_id is null then
    raise exception 'Authentication required' using errcode = '42501';
  end if;

  if not public.company_is_public(p_company_id) then
    raise exception 'Company is not available' using errcode = 'P0002';
  end if;

  insert into public.company_follows(user_id, company_id)
  values (v_user_id, p_company_id)
  on conflict (user_id, company_id) do nothing;

  return p_company_id;
end
$function$;

create or replace function public.unfollow_company(p_company_id bigint)
returns bigint
language plpgsql
security definer
set search_path = public, pg_temp
as $function$
declare
  v_user_id uuid := auth.uid();
begin
  if v_user_id is null then
    raise exception 'Authentication required' using errcode = '42501';
  end if;

  delete from public.company_follows
  where user_id = v_user_id
    and company_id = p_company_id;

  return p_company_id;
end
$function$;

create or replace function public.get_my_followed_company_ids()
returns table(company_id bigint)
language sql
stable
security invoker
set search_path = public, pg_temp
as $function$
  select follow.company_id
  from public.company_follows follow
  where follow.user_id = auth.uid()
  order by follow.created_at desc, follow.company_id;
$function$;

revoke all on function public.follow_company(bigint)
  from public, anon, authenticated;
revoke all on function public.unfollow_company(bigint)
  from public, anon, authenticated;
revoke all on function public.get_my_followed_company_ids()
  from public, anon, authenticated;
grant execute on function public.follow_company(bigint) to authenticated;
grant execute on function public.unfollow_company(bigint) to authenticated;
grant execute on function public.get_my_followed_company_ids()
  to authenticated;
grant execute on function public.follow_company(bigint),
  public.unfollow_company(bigint),
  public.get_my_followed_company_ids() to service_role;

-- Existing favorites already use a unique(user_id, product_id) contract and
-- owner-only RLS. Make the anonymous mutation denial explicit without changing
-- authenticated behavior.
revoke insert, update, delete on table public.favorites from anon;
grant select, insert, delete on table public.favorites to authenticated;

comment on table public.company_follows is
  'Private, user-scoped company follows. No public follower list or count.';
comment on function public.follow_company(bigint) is
  'Idempotently follows an approved, active public company for auth.uid().';
comment on function public.unfollow_company(bigint) is
  'Idempotently removes auth.uid() company follow state.';

do $verification$
begin
  if has_table_privilege('anon', 'public.company_follows', 'SELECT')
     or has_table_privilege('anon', 'public.company_follows', 'INSERT')
     or has_table_privilege('anon', 'public.company_follows', 'UPDATE')
     or has_table_privilege('anon', 'public.company_follows', 'DELETE') then
    raise exception 'Anonymous company-follow privilege remains';
  end if;

  if not has_table_privilege(
    'authenticated', 'public.company_follows', 'SELECT'
  ) or has_table_privilege(
    'authenticated', 'public.company_follows', 'INSERT'
  ) or has_table_privilege(
    'authenticated', 'public.company_follows', 'DELETE'
  ) then
    raise exception 'Company-follow table privilege contract is invalid';
  end if;

  if has_function_privilege(
    'anon', 'public.follow_company(bigint)', 'EXECUTE'
  ) or has_function_privilege(
    'anon', 'public.unfollow_company(bigint)', 'EXECUTE'
  ) or not has_function_privilege(
    'authenticated', 'public.follow_company(bigint)', 'EXECUTE'
  ) or not has_function_privilege(
    'authenticated', 'public.unfollow_company(bigint)', 'EXECUTE'
  ) or has_function_privilege(
    'anon', 'public.get_my_followed_company_ids()', 'EXECUTE'
  ) or not has_function_privilege(
    'authenticated', 'public.get_my_followed_company_ids()', 'EXECUTE'
  ) then
    raise exception 'Company-follow RPC privilege contract is invalid';
  end if;
end
$verification$;

notify pgrst, 'reload schema';

commit;

-- Rollback: drop the three functions, then drop public.company_follows. This is
-- destructive to follow state and must only be executed with explicit approval.
