-- MedicHall Match Engine v1 foundation
-- Run after existing companies, products, buyer_profiles and admin functions exist.

begin;

-- 1) Company matching preferences and normalized profile data
create table if not exists public.company_match_profiles (
  company_id bigint primary key references public.companies(id) on delete cascade,
  target_countries text[] not null default '{}',
  target_partner_types text[] not null default '{}',
  product_keywords text[] not null default '{}',
  cpv_codes text[] not null default '{}',
  certifications text[] not null default '{}',
  oem_available boolean not null default false,
  private_label_available boolean not null default false,
  min_match_score integer not null default 60 check (min_match_score between 0 and 100),
  profile_complete_score integer not null default 0 check (profile_complete_score between 0 and 100),
  last_indexed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- 2) Tender opportunities imported from TED or other approved sources
create table if not exists public.tenders (
  id bigint generated by default as identity primary key,
  source text not null default 'TED',
  source_notice_id text not null,
  title text not null,
  description text,
  buyer_name text,
  country_code text,
  country_name text,
  cpv_codes text[] not null default '{}',
  product_keywords text[] not null default '{}',
  publication_date date,
  deadline_at timestamptz,
  estimated_value numeric,
  currency text,
  source_url text,
  language_code text,
  raw_payload jsonb not null default '{}'::jsonb,
  status text not null default 'open' check (status in ('open','closed','cancelled','draft')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(source, source_notice_id)
);

-- 3) Distributor / partner candidates
create table if not exists public.distributor_candidates (
  id bigint generated by default as identity primary key,
  name text not null,
  website text,
  country_code text,
  country_name text,
  company_type text,
  product_categories text[] not null default '{}',
  product_keywords text[] not null default '{}',
  brands text[] not null default '{}',
  channels text[] not null default '{}',
  certifications text[] not null default '{}',
  contact_email text,
  contact_name text,
  linkedin_url text,
  source text,
  source_url text,
  verification_status text not null default 'unverified'
    check (verification_status in ('unverified','reviewed','verified','rejected')),
  is_active boolean not null default true,
  raw_payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- 4) Unified opportunity matches
create table if not exists public.opportunity_matches (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id) on delete cascade,
  opportunity_type text not null check (opportunity_type in ('tender','distributor')),
  tender_id bigint references public.tenders(id) on delete cascade,
  distributor_id bigint references public.distributor_candidates(id) on delete cascade,
  match_score integer not null check (match_score between 0 and 100),
  confidence_score integer check (confidence_score between 0 and 100),
  keyword_score integer not null default 0 check (keyword_score between 0 and 100),
  geography_score integer not null default 0 check (geography_score between 0 and 100),
  certification_score integer not null default 0 check (certification_score between 0 and 100),
  category_score integer not null default 0 check (category_score between 0 and 100),
  reasons jsonb not null default '[]'::jsonb,
  risks jsonb not null default '[]'::jsonb,
  ai_summary text,
  status text not null default 'new'
    check (status in ('new','viewed','saved','contacted','dismissed','applied')),
  generated_by text not null default 'rules-v1',
  generated_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (
    (opportunity_type = 'tender' and tender_id is not null and distributor_id is null)
    or
    (opportunity_type = 'distributor' and distributor_id is not null and tender_id is null)
  )
);

create unique index if not exists opportunity_matches_company_tender_uidx
  on public.opportunity_matches(company_id, tender_id)
  where tender_id is not null;

create unique index if not exists opportunity_matches_company_distributor_uidx
  on public.opportunity_matches(company_id, distributor_id)
  where distributor_id is not null;

create index if not exists tenders_open_deadline_idx
  on public.tenders(status, deadline_at);
create index if not exists tenders_country_idx
  on public.tenders(country_code);
create index if not exists distributor_candidates_country_idx
  on public.distributor_candidates(country_code)
  where is_active = true;
create index if not exists opportunity_matches_company_score_idx
  on public.opportunity_matches(company_id, match_score desc, generated_at desc);

-- 5) Basic rule-based scoring helper. AI enrichment can update the same row later.
create or replace function public.calculate_keyword_overlap_score(
  profile_keywords text[],
  opportunity_keywords text[]
) returns integer
language sql
immutable
as $$
  select case
    when coalesce(array_length(profile_keywords, 1), 0) = 0
      or coalesce(array_length(opportunity_keywords, 1), 0) = 0 then 0
    else least(
      100,
      round(
        100.0 * (
          select count(*)
          from (
            select distinct lower(trim(x)) as keyword
            from unnest(profile_keywords) x
            intersect
            select distinct lower(trim(y)) as keyword
            from unnest(opportunity_keywords) y
          ) overlap_keywords
        ) / greatest(
          1,
          (select count(distinct lower(trim(x))) from unnest(profile_keywords) x)
        )
      )::integer
    )
  end;
$$;

-- 6) Timestamps
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists company_match_profiles_set_updated_at on public.company_match_profiles;
create trigger company_match_profiles_set_updated_at
before update on public.company_match_profiles
for each row execute function public.set_updated_at();

drop trigger if exists tenders_set_updated_at on public.tenders;
create trigger tenders_set_updated_at
before update on public.tenders
for each row execute function public.set_updated_at();

drop trigger if exists distributor_candidates_set_updated_at on public.distributor_candidates;
create trigger distributor_candidates_set_updated_at
before update on public.distributor_candidates
for each row execute function public.set_updated_at();

drop trigger if exists opportunity_matches_set_updated_at on public.opportunity_matches;
create trigger opportunity_matches_set_updated_at
before update on public.opportunity_matches
for each row execute function public.set_updated_at();

-- 7) RLS
alter table public.company_match_profiles enable row level security;
alter table public.tenders enable row level security;
alter table public.distributor_candidates enable row level security;
alter table public.opportunity_matches enable row level security;

-- Company owners manage their own matching profile.
drop policy if exists "owner manage own match profile" on public.company_match_profiles;
create policy "owner manage own match profile"
on public.company_match_profiles
for all to authenticated
using (
  company_id in (select id from public.companies where owner_id = auth.uid())
)
with check (
  company_id in (select id from public.companies where owner_id = auth.uid())
);

-- Admins can manage all matching profiles.
drop policy if exists "admin manage match profiles" on public.company_match_profiles;
create policy "admin manage match profiles"
on public.company_match_profiles
for all to authenticated
using (public.is_admin())
with check (public.is_admin());

-- Authenticated members can read open tenders and active distributor candidates.
drop policy if exists "members read open tenders" on public.tenders;
create policy "members read open tenders"
on public.tenders
for select to authenticated
using (status = 'open');

drop policy if exists "members read active distributors" on public.distributor_candidates;
create policy "members read active distributors"
on public.distributor_candidates
for select to authenticated
using (is_active = true and verification_status in ('reviewed','verified'));

-- Admin-only write access for imported opportunities.
drop policy if exists "admin manage tenders" on public.tenders;
create policy "admin manage tenders"
on public.tenders
for all to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "admin manage distributors" on public.distributor_candidates;
create policy "admin manage distributors"
on public.distributor_candidates
for all to authenticated
using (public.is_admin())
with check (public.is_admin());

-- Company owners can view and update workflow status of their matches.
drop policy if exists "owner read own opportunity matches" on public.opportunity_matches;
create policy "owner read own opportunity matches"
on public.opportunity_matches
for select to authenticated
using (
  company_id in (select id from public.companies where owner_id = auth.uid())
);

drop policy if exists "owner update own opportunity matches" on public.opportunity_matches;
create policy "owner update own opportunity matches"
on public.opportunity_matches
for update to authenticated
using (
  company_id in (select id from public.companies where owner_id = auth.uid())
)
with check (
  company_id in (select id from public.companies where owner_id = auth.uid())
);

drop policy if exists "admin manage opportunity matches" on public.opportunity_matches;
create policy "admin manage opportunity matches"
on public.opportunity_matches
for all to authenticated
using (public.is_admin())
with check (public.is_admin());

commit;
