begin;

-- Company registration must commit independently of email delivery. The
-- trigger records one durable outbox item; a cron-authenticated Edge Function
-- claims and delivers due items with provider-level idempotency.
create table if not exists public.company_admin_notification_outbox (
  id bigint generated by default as identity primary key,
  company_id bigint not null
    references public.companies(id) on delete cascade,
  event_type text not null default 'company_registered'
    check (event_type = 'company_registered'),
  status text not null default 'pending'
    check (status in ('pending', 'processing', 'retry', 'sent', 'failed')),
  attempt_count integer not null default 0
    check (attempt_count >= 0),
  max_attempts integer not null default 6
    check (max_attempts between 1 and 12),
  next_attempt_at timestamptz not null default now(),
  lease_expires_at timestamptz,
  provider_message_id text,
  last_error_code text,
  last_error_redacted text,
  sent_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (company_id, event_type),
  check (
    (status = 'sent' and provider_message_id is not null and sent_at is not null)
    or status <> 'sent'
  )
);

create index if not exists company_admin_notification_due_idx
  on public.company_admin_notification_outbox (
    next_attempt_at,
    lease_expires_at,
    id
  )
  where status in ('pending', 'retry', 'processing');

alter table public.company_admin_notification_outbox enable row level security;
revoke all on table public.company_admin_notification_outbox
  from public, anon, authenticated;
grant select, insert, update, delete
  on table public.company_admin_notification_outbox to service_role;
grant usage, select
  on sequence public.company_admin_notification_outbox_id_seq to service_role;

create or replace function public.enqueue_company_admin_notification()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $function$
begin
  insert into public.company_admin_notification_outbox (
    company_id,
    event_type
  )
  values (
    new.id,
    'company_registered'
  )
  on conflict (company_id, event_type) do nothing;

  return new;
exception
  when others then
    -- Email infrastructure must never roll back company registration. Keep the
    -- warning free of company, user, email, and provider credential data.
    raise warning
      'Company admin notification enqueue failed (SQLSTATE %)',
      sqlstate;
    return new;
end;
$function$;

revoke all on function public.enqueue_company_admin_notification()
  from public, anon, authenticated;

drop trigger if exists company_admin_notification_enqueue on public.companies;
create trigger company_admin_notification_enqueue
after insert on public.companies
for each row execute function public.enqueue_company_admin_notification();

-- Queue recent registrations, including the registration that prompted this
-- audit. The unique key makes this safe on retries and repeat migrations.
insert into public.company_admin_notification_outbox (
  company_id,
  event_type,
  next_attempt_at
)
select
  company.id,
  'company_registered',
  now()
from public.companies company
where company.created_at >= now() - interval '7 days'
on conflict (company_id, event_type) do nothing;

create or replace function public.claim_company_admin_notifications(
  p_limit integer default 20,
  p_lease_seconds integer default 120
)
returns table (
  outbox_id bigint,
  company_id bigint,
  company_name text,
  company_type text,
  company_country text,
  company_created_at timestamptz,
  attempt_count integer,
  idempotency_key text
)
language plpgsql
security definer
set search_path = public, pg_temp
as $function$
begin
  update public.company_admin_notification_outbox queue
  set
    status = 'failed',
    lease_expires_at = null,
    last_error_code = 'retry_budget_exhausted',
    last_error_redacted = 'retry_budget_exhausted',
    updated_at = now()
  where queue.status = 'processing'
    and queue.lease_expires_at <= now()
    and queue.attempt_count >= queue.max_attempts;

  return query
  with candidates as (
    select queue.id
    from public.company_admin_notification_outbox queue
    where (
        (
          queue.status in ('pending', 'retry')
          and queue.next_attempt_at <= now()
        ) or (
          queue.status = 'processing'
          and queue.lease_expires_at <= now()
        )
      )
      and queue.attempt_count < queue.max_attempts
    order by queue.next_attempt_at, queue.id
    for update skip locked
    limit greatest(1, least(coalesce(p_limit, 20), 100))
  ), claimed as (
    update public.company_admin_notification_outbox queue
    set
      status = 'processing',
      attempt_count = queue.attempt_count + 1,
      lease_expires_at = now()
        + make_interval(secs => greatest(
            30,
            least(coalesce(p_lease_seconds, 120), 900)
          )),
      last_error_code = null,
      last_error_redacted = null,
      updated_at = now()
    from candidates
    where queue.id = candidates.id
    returning queue.*
  )
  select
    claimed.id,
    company.id,
    company.name,
    company.type,
    company.country,
    company.created_at,
    claimed.attempt_count,
    'company-registration/' || claimed.id::text
  from claimed
  join public.companies company on company.id = claimed.company_id
  order by claimed.id;
end;
$function$;

create or replace function public.complete_company_admin_notification(
  p_outbox_id bigint,
  p_provider_message_id text
)
returns boolean
language plpgsql
security definer
set search_path = public, pg_temp
as $function$
declare
  updated_count integer;
begin
  if nullif(btrim(p_provider_message_id), '') is null then
    return false;
  end if;

  update public.company_admin_notification_outbox queue
  set
    status = 'sent',
    provider_message_id = left(btrim(p_provider_message_id), 512),
    sent_at = now(),
    lease_expires_at = null,
    last_error_code = null,
    last_error_redacted = null,
    updated_at = now()
  where queue.id = p_outbox_id
    and queue.status = 'processing';

  get diagnostics updated_count = row_count;
  return updated_count = 1;
end;
$function$;

create or replace function public.retry_company_admin_notification(
  p_outbox_id bigint,
  p_error_code text,
  p_error_redacted text,
  p_retry_after_seconds integer default null
)
returns text
language plpgsql
security definer
set search_path = public, pg_temp
as $function$
declare
  next_status text;
begin
  update public.company_admin_notification_outbox queue
  set
    status = case
      when queue.attempt_count >= queue.max_attempts then 'failed'
      else 'retry'
    end,
    next_attempt_at = case
      when queue.attempt_count >= queue.max_attempts then queue.next_attempt_at
      else now() + make_interval(
        secs => greatest(
          60,
          least(
            coalesce(
              p_retry_after_seconds,
              case queue.attempt_count
                when 1 then 60
                when 2 then 300
                when 3 then 1800
                when 4 then 7200
                else 21600
              end
            ),
            21600
          )
        )
      )
    end,
    lease_expires_at = null,
    last_error_code = left(
      coalesce(nullif(btrim(p_error_code), ''), 'delivery_failed'),
      80
    ),
    last_error_redacted = left(
      coalesce(nullif(btrim(p_error_redacted), ''), 'delivery_failed'),
      240
    ),
    updated_at = now()
  where queue.id = p_outbox_id
    and queue.status = 'processing'
  returning queue.status into next_status;

  return next_status;
end;
$function$;

revoke all on function public.claim_company_admin_notifications(integer, integer)
  from public, anon, authenticated;
revoke all on function public.complete_company_admin_notification(bigint, text)
  from public, anon, authenticated;
revoke all on function public.retry_company_admin_notification(bigint, text, text, integer)
  from public, anon, authenticated;
grant execute on function public.claim_company_admin_notifications(integer, integer)
  to service_role;
grant execute on function public.complete_company_admin_notification(bigint, text)
  to service_role;
grant execute on function public.retry_company_admin_notification(bigint, text, text, integer)
  to service_role;

-- Replace the historical credential-bearing database function definition.
-- Legacy RFQ/message/offer notifications continue only when operators create
-- the Vault secret; fresh installs already use this same safe contract.
create or replace function public.notify_email(
  p_to text,
  p_subject text,
  p_html text
)
returns void
language plpgsql
security definer
set search_path = public, extensions, vault, pg_temp
as $function$
declare
  resend_api_key text;
begin
  if nullif(btrim(p_to), '') is null then
    return;
  end if;

  begin
    select decrypted_secret
    into resend_api_key
    from vault.decrypted_secrets
    where name = 'medichall_resend_api_key'
    limit 1;
  exception
    when undefined_table then
      return;
  end;

  if nullif(resend_api_key, '') is null then
    return;
  end if;

  perform net.http_post(
    url := 'https://api.resend.com/emails',
    headers := jsonb_build_object(
      'Authorization', 'Bearer ' || resend_api_key,
      'Content-Type', 'application/json'
    ),
    body := jsonb_build_object(
      'from', public.mh_email_from(),
      'to', jsonb_build_array(p_to),
      'subject', p_subject,
      'html', p_html
    )
  );
exception
  when undefined_function then
    return;
end;
$function$;

revoke all on function public.notify_email(text, text, text)
  from public, anon, authenticated;
grant execute on function public.notify_email(text, text, text)
  to service_role;

create or replace function public.dispatch_company_admin_notifications()
returns bigint
language plpgsql
security definer
set search_path = public, extensions, vault, pg_temp
as $function$
declare
  project_url text;
  cron_secret text;
  request_id bigint;
begin
  if not exists (
    select 1
    from public.company_admin_notification_outbox queue
    where (
        queue.status in ('pending', 'retry')
        and queue.next_attempt_at <= now()
      ) or (
        queue.status = 'processing'
        and queue.lease_expires_at <= now()
      )
  ) then
    return null;
  end if;

  select
    max(decrypted_secret) filter (where name = 'medichall_project_url'),
    max(decrypted_secret) filter (where name = 'medichall_cron_secret')
  into project_url, cron_secret
  from vault.decrypted_secrets;

  if nullif(btrim(project_url), '') is null
     or nullif(btrim(cron_secret), '') is null then
    return null;
  end if;

  select net.http_post(
    url := rtrim(project_url, '/')
      || '/functions/v1/company-admin-notification',
    headers := jsonb_build_object(
      'Content-Type', 'application/json',
      'x-cron-secret', cron_secret
    ),
    body := jsonb_build_object('action', 'process', 'limit', 20)
  ) into request_id;

  return request_id;
exception
  when undefined_table or undefined_function or insufficient_privilege then
    return null;
end;
$function$;

revoke all on function public.dispatch_company_admin_notifications()
  from public, anon, authenticated;
grant execute on function public.dispatch_company_admin_notifications()
  to service_role;

do $schedule$
declare
  existing_job bigint;
  scheduled_job bigint;
begin
  if exists (
    select 1
    from pg_extension
    where extname = 'pg_cron'
  ) then
    execute
      'select jobid from cron.job where jobname = $1 limit 1'
      into existing_job
      using 'medichall-company-admin-notification';
    if existing_job is not null then
      execute 'select cron.unschedule($1)' using existing_job;
    end if;
    execute
      'select cron.schedule($1, $2, $3)'
      into scheduled_job
      using
        'medichall-company-admin-notification',
        '*/2 * * * *',
        'select public.dispatch_company_admin_notifications();';
    raise notice 'Scheduled company admin notification job %', scheduled_job;
  else
    raise notice
      'pg_cron is unavailable; dispatch_company_admin_notifications remains callable by service role';
  end if;
exception
  when insufficient_privilege or undefined_table or invalid_schema_name then
    raise notice
      'Company admin notification automation was not scheduled: %',
      sqlerrm;
end
$schedule$;

notify pgrst, 'reload schema';

commit;
