-- MedicHall Two-Sided Matchmaking MVP v1
-- Roles: manufacturer, distributor, buyer
-- Run once in Supabase SQL Editor.

begin;

create extension if not exists pgcrypto;

create table if not exists public.matchmaking_profiles (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null unique references auth.users(id) on delete cascade,
  company_id bigint unique references public.companies(id) on delete set null,

  role text not null default 'manufacturer'
    check (role in ('manufacturer','distributor','buyer')),
  display_name text not null,
  country text,
  website text,
  description text,
  company_size text,

  offered_products text[] not null default '{}',
  interested_products text[] not null default '{}',
  product_categories text[] not null default '{}',

  target_countries text[] not null default '{}',
  served_countries text[] not null default '{}',
  preferred_supplier_countries text[] not null default '{}',

  sales_channels text[] not null default '{}',
  certifications text[] not null default '{}',
  required_certifications text[] not null default '{}',
  partner_types_sought text[] not null default '{}',

  annual_volume_min numeric,
  annual_volume_max numeric,
  average_order_value numeric,
  minimum_order_quantity numeric,

  oem_available boolean not null default false,
  private_label_available boolean not null default false,
  oem_interest boolean not null default false,
  private_label_interest boolean not null default false,
  tender_experience boolean not null default false,

  hospital_network_size integer,
  warehouse_capacity_text text,
  purchase_frequency text,
  profile_completeness integer not null default 0
    check (profile_completeness between 0 and 100),

  is_active boolean not null default true,
  last_matched_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.matchmaking_matches (
  id bigint generated by default as identity primary key,
  source_profile_id uuid not null
    references public.matchmaking_profiles(id) on delete cascade,
  target_profile_id uuid not null
    references public.matchmaking_profiles(id) on delete cascade,

  match_score integer not null default 0 check (match_score between 0 and 100),
  confidence_level text not null default 'low'
    check (confidence_level in ('low','medium','high')),

  product_score integer not null default 0 check (product_score between 0 and 100),
  geography_score integer not null default 0 check (geography_score between 0 and 100),
  partner_type_score integer not null default 0 check (partner_type_score between 0 and 100),
  certification_score integer not null default 0 check (certification_score between 0 and 100),
  commercial_score integer not null default 0 check (commercial_score between 0 and 100),

  reasons jsonb not null default '{}'::jsonb,
  risks jsonb not null default '{}'::jsonb,
  status text not null default 'new'
    check (status in ('new','viewed','saved','connection_requested','connected','dismissed')),
  generated_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  unique (source_profile_id, target_profile_id),
  check (source_profile_id <> target_profile_id)
);

create table if not exists public.business_connections (
  id bigint generated by default as identity primary key,
  requester_profile_id uuid not null
    references public.matchmaking_profiles(id) on delete cascade,
  recipient_profile_id uuid not null
    references public.matchmaking_profiles(id) on delete cascade,
  status text not null default 'pending'
    check (status in ('pending','accepted','declined','cancelled')),
  introduction_message text,
  created_at timestamptz not null default now(),
  responded_at timestamptz,
  updated_at timestamptz not null default now(),
  check (requester_profile_id <> recipient_profile_id)
);

create unique index if not exists business_connections_pair_unique
on public.business_connections (
  least(requester_profile_id::text, recipient_profile_id::text),
  greatest(requester_profile_id::text, recipient_profile_id::text)
)
where status in ('pending','accepted');

create table if not exists public.matchmaking_meeting_requests (
  id bigint generated by default as identity primary key,
  connection_id bigint references public.business_connections(id) on delete cascade,
  requester_profile_id uuid not null
    references public.matchmaking_profiles(id) on delete cascade,
  recipient_profile_id uuid not null
    references public.matchmaking_profiles(id) on delete cascade,
  proposed_start timestamptz,
  proposed_end timestamptz,
  timezone text,
  agenda text,
  meeting_url text,
  status text not null default 'pending'
    check (status in ('pending','accepted','declined','cancelled','completed')),
  created_at timestamptz not null default now(),
  responded_at timestamptz,
  updated_at timestamptz not null default now()
);

create index if not exists matchmaking_matches_source_score_idx
  on public.matchmaking_matches(source_profile_id, match_score desc);

create index if not exists matchmaking_profiles_role_country_idx
  on public.matchmaking_profiles(role, country)
  where is_active = true;

alter table public.matchmaking_profiles enable row level security;
alter table public.matchmaking_matches enable row level security;
alter table public.business_connections enable row level security;
alter table public.matchmaking_meeting_requests enable row level security;

drop policy if exists "authenticated view active matchmaking profiles"
on public.matchmaking_profiles;

create policy "authenticated view active matchmaking profiles"
on public.matchmaking_profiles
for select to authenticated
using (is_active = true or user_id = auth.uid());

drop policy if exists "users create own matchmaking profile"
on public.matchmaking_profiles;

create policy "users create own matchmaking profile"
on public.matchmaking_profiles
for insert to authenticated
with check (user_id = auth.uid());

drop policy if exists "users update own matchmaking profile"
on public.matchmaking_profiles;

create policy "users update own matchmaking profile"
on public.matchmaking_profiles
for update to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

drop policy if exists "users view own generated matches"
on public.matchmaking_matches;

create policy "users view own generated matches"
on public.matchmaking_matches
for select to authenticated
using (
  exists (
    select 1
    from public.matchmaking_profiles p
    where p.id = source_profile_id
      and p.user_id = auth.uid()
  )
);

drop policy if exists "participants view business connections"
on public.business_connections;

create policy "participants view business connections"
on public.business_connections
for select to authenticated
using (
  exists (
    select 1 from public.matchmaking_profiles p
    where p.user_id = auth.uid()
      and p.id in (requester_profile_id, recipient_profile_id)
  )
);

drop policy if exists "participants view meeting requests"
on public.matchmaking_meeting_requests;

create policy "participants view meeting requests"
on public.matchmaking_meeting_requests
for select to authenticated
using (
  exists (
    select 1 from public.matchmaking_profiles p
    where p.user_id = auth.uid()
      and p.id in (requester_profile_id, recipient_profile_id)
  )
);

create or replace function public.mm_normalize_array(values_in text[])
returns text[]
language sql
immutable
as $$
  select coalesce(array_agg(distinct lower(trim(v))) filter (where trim(v) <> ''), '{}'::text[])
  from unnest(coalesce(values_in, '{}'::text[])) v;
$$;

create or replace function public.mm_overlap_score(a text[], b text[])
returns integer
language sql
immutable
as $$
  with aa as (
    select unnest(public.mm_normalize_array(a)) value
  ),
  bb as (
    select unnest(public.mm_normalize_array(b)) value
  ),
  counts as (
    select
      (select count(*) from aa) a_count,
      (select count(*) from bb) b_count,
      (select count(*) from aa join bb using(value)) overlap_count
  )
  select case
    when a_count = 0 or b_count = 0 then 50
    else least(
      100,
      round(
        100.0 * overlap_count /
        greatest(1, least(a_count, b_count))
      )::integer
    )
  end
  from counts;
$$;

create or replace function public.mm_role_fit(source_role text, target_role text, sought text[])
returns integer
language sql
immutable
as $$
  select case
    when target_role = any(public.mm_normalize_array(sought)) then 100
    when coalesce(array_length(sought, 1), 0) = 0 then
      case
        when source_role = 'manufacturer' and target_role in ('distributor','buyer') then 80
        when source_role = 'distributor' and target_role in ('manufacturer','buyer') then 80
        when source_role = 'buyer' and target_role in ('manufacturer','distributor') then 80
        else 20
      end
    else 0
  end;
$$;

create or replace function public.mm_commercial_score(
  source_profile public.matchmaking_profiles,
  target_profile public.matchmaking_profiles
)
returns integer
language plpgsql
immutable
as $$
declare
  score integer := 50;
begin
  if source_profile.role = 'manufacturer' then
    if source_profile.minimum_order_quantity is not null
       and target_profile.annual_volume_max is not null then
      score := case
        when target_profile.annual_volume_max >= source_profile.minimum_order_quantity then 100
        else 20
      end;
    end if;

    if source_profile.private_label_available
       and target_profile.private_label_interest then
      score := least(100, score + 20);
    end if;

    if source_profile.oem_available
       and target_profile.oem_interest then
      score := least(100, score + 20);
    end if;
  elsif source_profile.role in ('buyer','distributor') then
    if target_profile.minimum_order_quantity is not null
       and source_profile.annual_volume_max is not null then
      score := case
        when source_profile.annual_volume_max >= target_profile.minimum_order_quantity then 100
        else 20
      end;
    end if;
  end if;

  return greatest(0, least(100, score));
end;
$$;

create or replace function public.refresh_matchmaking_matches(p_profile_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  source_profile public.matchmaking_profiles;
  target_profile public.matchmaking_profiles;
  product_value integer;
  geography_value integer;
  role_value integer;
  certification_value integer;
  commercial_value integer;
  total_value integer;
  processed integer := 0;
begin
  select *
  into source_profile
  from public.matchmaking_profiles
  where id = p_profile_id
    and user_id = auth.uid();

  if source_profile.id is null then
    raise exception 'Matchmaking profile not found or access denied';
  end if;

  for target_profile in
    select *
    from public.matchmaking_profiles
    where is_active = true
      and id <> source_profile.id
  loop
    if source_profile.role = 'manufacturer' then
      product_value := public.mm_overlap_score(
        source_profile.offered_products || source_profile.product_categories,
        target_profile.interested_products || target_profile.product_categories
      );
    else
      product_value := public.mm_overlap_score(
        source_profile.interested_products || source_profile.product_categories,
        target_profile.offered_products || target_profile.product_categories
      );
    end if;

    geography_value := greatest(
      public.mm_overlap_score(
        source_profile.target_countries,
        target_profile.served_countries || array[target_profile.country]
      ),
      public.mm_overlap_score(
        source_profile.served_countries || array[source_profile.country],
        target_profile.target_countries
      )
    );

    role_value := public.mm_role_fit(
      source_profile.role,
      target_profile.role,
      source_profile.partner_types_sought
    );

    if source_profile.role = 'manufacturer' then
      certification_value := public.mm_overlap_score(
        source_profile.certifications,
        target_profile.required_certifications
      );
    else
      certification_value := public.mm_overlap_score(
        source_profile.required_certifications,
        target_profile.certifications
      );
    end if;

    commercial_value := public.mm_commercial_score(source_profile, target_profile);

    total_value := round(
      product_value * 0.40 +
      geography_value * 0.20 +
      role_value * 0.15 +
      certification_value * 0.10 +
      commercial_value * 0.15
    )::integer;

    insert into public.matchmaking_matches (
      source_profile_id,
      target_profile_id,
      match_score,
      confidence_level,
      product_score,
      geography_score,
      partner_type_score,
      certification_score,
      commercial_score,
      reasons,
      risks,
      generated_at,
      updated_at
    )
    values (
      source_profile.id,
      target_profile.id,
      total_value,
      case
        when source_profile.profile_completeness >= 75
         and target_profile.profile_completeness >= 75 then 'high'
        when source_profile.profile_completeness >= 45
         and target_profile.profile_completeness >= 45 then 'medium'
        else 'low'
      end,
      product_value,
      geography_value,
      role_value,
      certification_value,
      commercial_value,
      jsonb_strip_nulls(jsonb_build_object(
        'products', case when product_value >= 70 then 'Product needs and portfolio overlap' end,
        'geography', case when geography_value >= 70 then 'Target and served markets overlap' end,
        'partner_type', case when role_value >= 70 then 'Requested partner type matches' end,
        'certifications', case when certification_value >= 70 then 'Certification requirements align' end,
        'commercial', case when commercial_value >= 70 then 'Commercial capacity and preferences align' end
      )),
      jsonb_strip_nulls(jsonb_build_object(
        'profile_data', case
          when source_profile.profile_completeness < 60
            or target_profile.profile_completeness < 60
          then 'One or both profiles are incomplete'
        end,
        'products', case when product_value < 35 then 'Low confirmed product overlap' end,
        'geography', case when geography_value < 35 then 'Limited confirmed market overlap' end
      )),
      now(),
      now()
    )
    on conflict (source_profile_id, target_profile_id)
    do update set
      match_score = excluded.match_score,
      confidence_level = excluded.confidence_level,
      product_score = excluded.product_score,
      geography_score = excluded.geography_score,
      partner_type_score = excluded.partner_type_score,
      certification_score = excluded.certification_score,
      commercial_score = excluded.commercial_score,
      reasons = excluded.reasons,
      risks = excluded.risks,
      generated_at = excluded.generated_at,
      updated_at = excluded.updated_at;

    processed := processed + 1;
  end loop;

  update public.matchmaking_profiles
  set last_matched_at = now(), updated_at = now()
  where id = source_profile.id;

  return jsonb_build_object(
    'profile_id', source_profile.id,
    'profiles_processed', processed,
    'generated_at', now()
  );
end;
$$;

revoke all on function public.refresh_matchmaking_matches(uuid) from public;
grant execute on function public.refresh_matchmaking_matches(uuid) to authenticated;

create or replace function public.request_business_connection(
  p_recipient_profile_id uuid,
  p_message text default null
)
returns public.business_connections
language plpgsql
security definer
set search_path = public
as $$
declare
  requester public.matchmaking_profiles;
  connection_row public.business_connections;
begin
  select * into requester
  from public.matchmaking_profiles
  where user_id = auth.uid();

  if requester.id is null then
    raise exception 'Create your matchmaking profile first';
  end if;

  if requester.id = p_recipient_profile_id then
    raise exception 'You cannot connect with your own profile';
  end if;

  insert into public.business_connections (
    requester_profile_id,
    recipient_profile_id,
    introduction_message
  )
  values (
    requester.id,
    p_recipient_profile_id,
    nullif(trim(p_message), '')
  )
  returning * into connection_row;

  update public.matchmaking_matches
  set status = 'connection_requested', updated_at = now()
  where source_profile_id = requester.id
    and target_profile_id = p_recipient_profile_id;

  return connection_row;
end;
$$;

revoke all on function public.request_business_connection(uuid,text) from public;
grant execute on function public.request_business_connection(uuid,text) to authenticated;

create or replace function public.respond_business_connection(
  p_connection_id bigint,
  p_status text
)
returns public.business_connections
language plpgsql
security definer
set search_path = public
as $$
declare
  connection_row public.business_connections;
  current_profile public.matchmaking_profiles;
begin
  if p_status not in ('accepted','declined') then
    raise exception 'Invalid response';
  end if;

  select * into current_profile
  from public.matchmaking_profiles
  where user_id = auth.uid();

  update public.business_connections c
  set
    status = p_status,
    responded_at = now(),
    updated_at = now()
  where c.id = p_connection_id
    and c.recipient_profile_id = current_profile.id
    and c.status = 'pending'
  returning * into connection_row;

  if connection_row.id is null then
    raise exception 'Connection request not found or access denied';
  end if;

  if p_status = 'accepted' then
    update public.matchmaking_matches
    set status = 'connected', updated_at = now()
    where
      (source_profile_id = connection_row.requester_profile_id
       and target_profile_id = connection_row.recipient_profile_id)
      or
      (source_profile_id = connection_row.recipient_profile_id
       and target_profile_id = connection_row.requester_profile_id);
  end if;

  return connection_row;
end;
$$;

revoke all on function public.respond_business_connection(bigint,text) from public;
grant execute on function public.respond_business_connection(bigint,text) to authenticated;

create or replace function public.request_matchmaking_meeting(
  p_recipient_profile_id uuid,
  p_start timestamptz,
  p_end timestamptz,
  p_timezone text,
  p_agenda text default null
)
returns public.matchmaking_meeting_requests
language plpgsql
security definer
set search_path = public
as $$
declare
  requester public.matchmaking_profiles;
  accepted_connection public.business_connections;
  meeting_row public.matchmaking_meeting_requests;
begin
  select * into requester
  from public.matchmaking_profiles
  where user_id = auth.uid();

  select * into accepted_connection
  from public.business_connections
  where status = 'accepted'
    and (
      (requester_profile_id = requester.id and recipient_profile_id = p_recipient_profile_id)
      or
      (recipient_profile_id = requester.id and requester_profile_id = p_recipient_profile_id)
    )
  order by created_at desc
  limit 1;

  if accepted_connection.id is null then
    raise exception 'An accepted connection is required before requesting a meeting';
  end if;

  if p_start is null or p_end is null or p_end <= p_start then
    raise exception 'Invalid meeting time';
  end if;

  insert into public.matchmaking_meeting_requests (
    connection_id,
    requester_profile_id,
    recipient_profile_id,
    proposed_start,
    proposed_end,
    timezone,
    agenda
  )
  values (
    accepted_connection.id,
    requester.id,
    p_recipient_profile_id,
    p_start,
    p_end,
    p_timezone,
    nullif(trim(p_agenda), '')
  )
  returning * into meeting_row;

  return meeting_row;
end;
$$;

revoke all on function public.request_matchmaking_meeting(uuid,timestamptz,timestamptz,text,text) from public;
grant execute on function public.request_matchmaking_meeting(uuid,timestamptz,timestamptz,text,text) to authenticated;

commit;
