-- MedicHall Tender Automation v1
-- Adds TED resolution and safe archive preprocessing.
-- Run after 202607100007_tender_attachment_discovery.sql.

begin;

alter table public.tenders
  add column if not exists procurement_documents_url text,
  add column if not exists ted_resolution_status text not null default 'not_started',
  add column if not exists ted_resolved_at timestamptz,
  add column if not exists ted_resolution_notes text;

alter table public.tender_documents
  add column if not exists parent_document_id bigint
    references public.tender_documents(id) on delete cascade,
  add column if not exists storage_path text,
  add column if not exists sha256 text,
  add column if not exists archive_processing_status text not null default 'not_applicable',
  add column if not exists extracted_from_archive boolean not null default false,
  add column if not exists original_archive_path text;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'tender_documents_archive_status_check'
  ) then
    alter table public.tender_documents
      add constraint tender_documents_archive_status_check
      check (
        archive_processing_status in (
          'not_applicable','pending','processing','completed','partial','failed'
        )
      );
  end if;
end
$$;

create table if not exists public.tender_archive_jobs (
  id bigint generated by default as identity primary key,
  tender_id bigint not null references public.tenders(id) on delete cascade,
  archive_document_id bigint not null
    references public.tender_documents(id) on delete cascade,
  company_id bigint references public.companies(id) on delete set null,
  requested_by uuid references auth.users(id) on delete set null,
  status text not null default 'queued'
    check (status in ('queued','processing','completed','partial','failed')),
  files_examined integer not null default 0,
  files_created integer not null default 0,
  compressed_bytes bigint not null default 0,
  extracted_bytes bigint not null default 0,
  skipped_files jsonb not null default '[]'::jsonb,
  error_message text,
  started_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (archive_document_id, status)
);

create index if not exists tender_archive_jobs_tender_idx
  on public.tender_archive_jobs(tender_id, created_at desc);

alter table public.tender_archive_jobs enable row level security;

drop policy if exists "users read own archive jobs" on public.tender_archive_jobs;
create policy "users read own archive jobs"
on public.tender_archive_jobs for select to authenticated
using (
  public.is_admin()
  or requested_by = auth.uid()
  or exists (
    select 1 from public.companies c
    where c.id = company_id and c.owner_id = auth.uid()
  )
);

-- Public procurement documents can be fetched by Claude through stable URLs.
insert into storage.buckets (id, name, public, file_size_limit)
values ('tender-documents', 'tender-documents', true, 104857600)
on conflict (id) do update set
  public = true,
  file_size_limit = 104857600;

drop policy if exists "public read tender document storage" on storage.objects;
create policy "public read tender document storage"
on storage.objects for select
using (bucket_id = 'tender-documents');

create or replace function public.queue_tender_archive_jobs(
  p_tender_id bigint,
  p_company_id bigint
)
returns setof public.tender_archive_jobs
language plpgsql
security definer
set search_path = public
as $$
declare
  v_archive public.tender_documents;
  v_job public.tender_archive_jobs;
begin
  if not (
    public.is_admin()
    or exists (
      select 1 from public.companies c
      where c.id = p_company_id and c.owner_id = auth.uid()
    )
  ) then
    raise exception 'Access denied';
  end if;

  for v_archive in
    select *
    from public.tender_documents
    where tender_id = p_tender_id
      and is_active = true
      and (
        lower(coalesce(mime_type,'')) = 'application/zip'
        or lower(coalesce(file_name,'')) like '%.zip'
        or lower(file_url) like '%.zip%'
      )
      and archive_processing_status not in ('processing','completed')
  loop
    select *
    into v_job
    from public.tender_archive_jobs
    where archive_document_id = v_archive.id
      and status in ('queued','processing')
    order by created_at desc
    limit 1;

    if v_job.id is null then
      insert into public.tender_archive_jobs (
        tender_id, archive_document_id, company_id, requested_by
      )
      values (
        p_tender_id, v_archive.id, p_company_id, auth.uid()
      )
      returning * into v_job;

      update public.tender_documents
      set archive_processing_status = 'pending', updated_at = now()
      where id = v_archive.id;
    end if;

    return next v_job;
  end loop;

  return;
end;
$$;

revoke all on function public.queue_tender_archive_jobs(bigint,bigint) from public;
grant execute on function public.queue_tender_archive_jobs(bigint,bigint)
to authenticated;

create or replace function public.get_tender_archive_status(
  p_tender_id bigint,
  p_company_id bigint
)
returns table (
  pending_count bigint,
  processing_count bigint,
  completed_count bigint,
  failed_count bigint,
  files_created bigint,
  last_error text
)
language sql
security definer
set search_path = public
as $$
  select
    count(*) filter (where j.status='queued'),
    count(*) filter (where j.status='processing'),
    count(*) filter (where j.status in ('completed','partial')),
    count(*) filter (where j.status='failed'),
    coalesce(sum(j.files_created),0),
    (
      select j2.error_message
      from public.tender_archive_jobs j2
      where j2.tender_id=p_tender_id
        and j2.company_id=p_company_id
        and j2.error_message is not null
      order by j2.created_at desc limit 1
    )
  from public.tender_archive_jobs j
  where j.tender_id=p_tender_id
    and j.company_id=p_company_id
    and (
      public.is_admin()
      or j.requested_by=auth.uid()
      or exists (
        select 1 from public.companies c
        where c.id=j.company_id and c.owner_id=auth.uid()
      )
    );
$$;

revoke all on function public.get_tender_archive_status(bigint,bigint) from public;
grant execute on function public.get_tender_archive_status(bigint,bigint)
to authenticated;

commit;
