-- MedicHall Tender Document Engine v1
-- Run after 202607100005_explainable_match_engine.sql

begin;

create table if not exists public.tender_documents (
  id bigint generated by default as identity primary key,
  tender_id bigint not null references public.tenders(id) on delete cascade,
  title text,
  file_name text,
  file_url text not null,
  mime_type text,
  file_size_bytes bigint,
  source_page_url text,
  document_type text not null default 'other',
  language_code text,
  is_active boolean not null default true,
  discovered_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (tender_id, file_url)
);

create table if not exists public.tender_document_analysis_jobs (
  id bigint generated by default as identity primary key,
  tender_id bigint not null references public.tenders(id) on delete cascade,
  requested_by uuid references auth.users(id) on delete set null,
  company_id bigint references public.companies(id) on delete set null,
  status text not null default 'queued',
  attempt_count integer not null default 0,
  selected_document_ids bigint[] not null default '{}',
  model_name text,
  error_code text,
  error_message text,
  started_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.tender_document_evidence (
  id bigint generated by default as identity primary key,
  tender_id bigint not null references public.tenders(id) on delete cascade,
  document_id bigint references public.tender_documents(id) on delete cascade,
  job_id bigint references public.tender_document_analysis_jobs(id) on delete cascade,
  evidence_type text not null,
  product_name text,
  field_name text,
  extracted_value text,
  quantity_value numeric,
  quantity_unit text,
  lot_number text,
  page_number integer,
  sheet_name text,
  cell_range text,
  source_quote text,
  confidence_score integer not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists tender_documents_tender_idx
  on public.tender_documents(tender_id);

create index if not exists tender_analysis_jobs_tender_status_idx
  on public.tender_document_analysis_jobs(tender_id, status, created_at desc);

create index if not exists tender_document_evidence_tender_idx
  on public.tender_document_evidence(tender_id, evidence_type);

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'tender_analysis_jobs_status_check'
  ) then
    alter table public.tender_document_analysis_jobs
      add constraint tender_analysis_jobs_status_check
      check (status in ('queued','processing','completed','partial','failed'));
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'tender_documents_type_check'
  ) then
    alter table public.tender_documents
      add constraint tender_documents_type_check
      check (document_type in (
        'technical_specification',
        'price_schedule',
        'boq',
        'contract_notice',
        'administrative',
        'lot_document',
        'other'
      ));
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'tender_document_evidence_confidence_check'
  ) then
    alter table public.tender_document_evidence
      add constraint tender_document_evidence_confidence_check
      check (confidence_score between 0 and 100);
  end if;
end
$$;

alter table public.tender_documents enable row level security;
alter table public.tender_document_analysis_jobs enable row level security;
alter table public.tender_document_evidence enable row level security;

drop policy if exists "authenticated read tender documents" on public.tender_documents;
create policy "authenticated read tender documents"
on public.tender_documents for select
to authenticated
using (is_active = true);

drop policy if exists "admin manage tender documents" on public.tender_documents;
create policy "admin manage tender documents"
on public.tender_documents for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "users read own analysis jobs" on public.tender_document_analysis_jobs;
create policy "users read own analysis jobs"
on public.tender_document_analysis_jobs for select
to authenticated
using (
  requested_by = auth.uid()
  or public.is_admin()
  or exists (
    select 1 from public.companies c
    where c.id = company_id and c.owner_id = auth.uid()
  )
);

drop policy if exists "users read evidence for accessible jobs" on public.tender_document_evidence;
create policy "users read evidence for accessible jobs"
on public.tender_document_evidence for select
to authenticated
using (
  public.is_admin()
  or exists (
    select 1
    from public.tender_document_analysis_jobs j
    left join public.companies c on c.id = j.company_id
    where j.id = job_id
      and (j.requested_by = auth.uid() or c.owner_id = auth.uid())
  )
);

create or replace function public.queue_tender_document_analysis(
  p_tender_id bigint,
  p_company_id bigint
)
returns public.tender_document_analysis_jobs
language plpgsql
security definer
set search_path = public
as $$
declare
  v_job public.tender_document_analysis_jobs;
  v_document_ids bigint[];
begin
  if not (
    public.is_admin()
    or exists (
      select 1 from public.companies c
      where c.id = p_company_id and c.owner_id = auth.uid()
    )
  ) then
    raise exception 'Access denied';
  end if;

  if not exists (select 1 from public.tenders where id = p_tender_id) then
    raise exception 'Tender not found';
  end if;

  select coalesce(array_agg(id order by id), '{}'::bigint[])
  into v_document_ids
  from (
    select id
    from public.tender_documents
    where tender_id = p_tender_id
      and is_active = true
      and lower(coalesce(mime_type, '')) in (
        'application/pdf',
        'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        'application/msword',
        'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        'application/vnd.ms-excel',
        'text/csv',
        'text/plain'
      )
    order by
      case document_type
        when 'technical_specification' then 1
        when 'boq' then 2
        when 'price_schedule' then 3
        when 'lot_document' then 4
        else 9
      end,
      id
    limit 6
  ) selected;

  if coalesce(array_length(v_document_ids, 1), 0) = 0 then
    raise exception 'No supported tender documents are registered';
  end if;

  if exists (
    select 1 from public.tender_document_analysis_jobs
    where tender_id = p_tender_id
      and company_id = p_company_id
      and status in ('queued','processing')
  ) then
    select *
    into v_job
    from public.tender_document_analysis_jobs
    where tender_id = p_tender_id
      and company_id = p_company_id
      and status in ('queued','processing')
    order by created_at desc
    limit 1;

    return v_job;
  end if;

  insert into public.tender_document_analysis_jobs (
    tender_id,
    requested_by,
    company_id,
    status,
    selected_document_ids
  )
  values (
    p_tender_id,
    auth.uid(),
    p_company_id,
    'queued',
    v_document_ids
  )
  returning * into v_job;

  update public.tenders
  set
    document_analysis_status = 'queued',
    updated_at = now()
  where id = p_tender_id;

  return v_job;
end;
$$;

revoke all on function public.queue_tender_document_analysis(bigint, bigint) from public;
grant execute on function public.queue_tender_document_analysis(bigint, bigint) to authenticated;

create or replace function public.get_tender_document_analysis_status(
  p_tender_id bigint,
  p_company_id bigint
)
returns table (
  job_id bigint,
  status text,
  error_message text,
  created_at timestamptz,
  started_at timestamptz,
  completed_at timestamptz
)
language sql
security definer
set search_path = public
as $$
  select
    j.id,
    j.status,
    j.error_message,
    j.created_at,
    j.started_at,
    j.completed_at
  from public.tender_document_analysis_jobs j
  where j.tender_id = p_tender_id
    and j.company_id = p_company_id
    and (
      public.is_admin()
      or j.requested_by = auth.uid()
      or exists (
        select 1 from public.companies c
        where c.id = j.company_id and c.owner_id = auth.uid()
      )
    )
  order by j.created_at desc
  limit 1;
$$;

revoke all on function public.get_tender_document_analysis_status(bigint, bigint) from public;
grant execute on function public.get_tender_document_analysis_status(bigint, bigint) to authenticated;

commit;
