-- MedicHall Medical Product Taxonomy v1
-- Forward-only, deterministic taxonomy and semantic-normalization foundation.

begin;

do $preflight$
begin
  if to_regclass('public.products') is null
     or to_regclass('public.companies') is null
     or to_regclass('public.matchmaking_profiles') is null
     or to_regclass('public.matchmaking_matches') is null
     or to_regclass('public.tenders') is null
     or to_regclass('public.opportunity_matches') is null
     or to_regprocedure('public.is_admin()') is null
     or to_regprocedure('public.set_updated_at()') is null then
    raise exception 'Medical taxonomy preflight failed: required production objects are missing';
  end if;
end
$preflight$;

create or replace function public.normalize_medical_product_term(p_value text)
returns text
language sql
immutable
parallel safe
set search_path = public, pg_temp
as $function$
  select trim(regexp_replace(
    regexp_replace(lower(coalesce(p_value, '')), '([a-z0-9])[-_/]+([a-z0-9])', '\1 \2', 'g'),
    '[^a-z0-9]+', ' ', 'g'
  ));
$function$;

create or replace function public.medical_product_term_similarity(
  p_left text,
  p_right text
)
returns numeric
language sql
immutable
parallel safe
set search_path = public, pg_temp
as $function$
  with left_tokens as (
    select distinct token
    from unnest(string_to_array(public.normalize_medical_product_term(p_left), ' ')) token
    where length(token) > 1
  ),
  right_tokens as (
    select distinct token
    from unnest(string_to_array(public.normalize_medical_product_term(p_right), ' ')) token
    where length(token) > 1
  ),
  union_tokens as (
    select token from left_tokens union select token from right_tokens
  ),
  intersect_tokens as (
    select token from left_tokens intersect select token from right_tokens
  )
  select case
    when (select count(*) from union_tokens) = 0 then 0::numeric
    else round(
      (select count(*)::numeric from intersect_tokens)
      / (select count(*)::numeric from union_tokens),
      4
    )
  end;
$function$;

create table public.medical_product_taxonomy (
  id bigint generated by default as identity primary key,
  parent_id bigint references public.medical_product_taxonomy(id)
    on delete restrict,
  hierarchy_level smallint not null check (hierarchy_level between 1 and 3),
  node_type text not null check (
    node_type in ('family', 'category', 'product_type')
  ),
  canonical_name text not null check (length(trim(canonical_name)) between 2 and 160),
  normalized_name text generated always as (
    public.normalize_medical_product_term(canonical_name)
  ) stored,
  slug text not null unique check (
    slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'
  ),
  description text check (description is null or length(description) <= 1200),
  taxonomy_version text not null default 'medical-taxonomy-v1',
  is_active boolean not null default true,
  sort_order integer not null default 0,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (parent_id, normalized_name),
  check (
    (hierarchy_level = 1 and node_type = 'family' and parent_id is null)
    or (hierarchy_level = 2 and node_type = 'category' and parent_id is not null)
    or (hierarchy_level = 3 and node_type = 'product_type' and parent_id is not null)
  )
);

create index medical_product_taxonomy_parent_sort_idx
  on public.medical_product_taxonomy(parent_id, sort_order, canonical_name)
  where is_active;
create index medical_product_taxonomy_normalized_idx
  on public.medical_product_taxonomy(normalized_name)
  where is_active;

create or replace function public.validate_medical_product_taxonomy_parent()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $function$
declare
  parent_level smallint;
begin
  if new.parent_id is null then return new; end if;
  if new.parent_id = new.id then
    raise exception 'A taxonomy node cannot be its own parent'
      using errcode = '23514';
  end if;
  select hierarchy_level into parent_level
  from public.medical_product_taxonomy
  where id = new.parent_id and is_active;
  if parent_level is null or parent_level <> new.hierarchy_level - 1 then
    raise exception 'Taxonomy parent must be the active level immediately above the node'
      using errcode = '23514';
  end if;
  return new;
end;
$function$;

create trigger validate_medical_product_taxonomy_parent
before insert or update of parent_id, hierarchy_level
on public.medical_product_taxonomy
for each row execute function public.validate_medical_product_taxonomy_parent();

create trigger medical_product_taxonomy_set_updated_at
before update on public.medical_product_taxonomy
for each row execute function public.set_updated_at();

create table public.medical_product_aliases (
  id bigint generated by default as identity primary key,
  taxonomy_id bigint not null references public.medical_product_taxonomy(id)
    on delete cascade,
  alias_text text not null check (length(trim(alias_text)) between 2 and 240),
  normalized_alias text generated always as (
    public.normalize_medical_product_term(alias_text)
  ) stored,
  language_code text not null default 'en' check (
    language_code ~ '^[a-z]{2,3}(?:-[A-Z]{2})?$'
  ),
  source text not null default 'admin' check (
    source in ('seed', 'catalog', 'admin', 'approved_custom', 'approved_semantic')
  ),
  confidence numeric(5,4) not null default 1 check (confidence between 0 and 1),
  verification_status text not null default 'approved' check (
    verification_status in ('approved', 'pending', 'rejected')
  ),
  is_active boolean not null default true,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (normalized_alias, language_code)
);

create index medical_product_aliases_taxonomy_idx
  on public.medical_product_aliases(taxonomy_id, normalized_alias)
  where is_active and verification_status = 'approved';
create trigger medical_product_aliases_set_updated_at
before update on public.medical_product_aliases
for each row execute function public.set_updated_at();

create table public.product_taxonomy_mappings (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  taxonomy_id bigint not null references public.medical_product_taxonomy(id)
    on delete restrict,
  mapping_source text not null check (
    mapping_source in (
      'seed_catalog', 'admin', 'owner_selected', 'deterministic_alias',
      'semantic_suggested', 'legacy_normalized_category'
    )
  ),
  confidence numeric(5,4) not null check (confidence between 0 and 1),
  status text not null default 'approved' check (
    status in ('approved', 'review_required', 'rejected')
  ),
  source_text text check (source_text is null or length(source_text) <= 500),
  is_primary boolean not null default true,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (product_id, taxonomy_id)
);

create unique index product_taxonomy_mappings_primary_unique
  on public.product_taxonomy_mappings(product_id)
  where is_primary and status = 'approved';
create index product_taxonomy_mappings_taxonomy_idx
  on public.product_taxonomy_mappings(taxonomy_id, product_id)
  where status = 'approved';
create trigger product_taxonomy_mappings_set_updated_at
before update on public.product_taxonomy_mappings
for each row execute function public.set_updated_at();

create table public.matchmaking_taxonomy_interests (
  id uuid primary key default gen_random_uuid(),
  profile_id uuid not null references public.matchmaking_profiles(id)
    on delete cascade,
  interest_kind text not null check (interest_kind in ('offered', 'interested')),
  taxonomy_id bigint references public.medical_product_taxonomy(id)
    on delete restrict,
  custom_term text check (custom_term is null or length(trim(custom_term)) between 2 and 240),
  normalized_custom_term text generated always as (
    public.normalize_medical_product_term(custom_term)
  ) stored,
  selection_scope text not null check (
    selection_scope in ('family', 'category', 'product_type', 'custom')
  ),
  resolution_status text not null default 'mapped' check (
    resolution_status in ('mapped', 'custom', 'review_required', 'semantic_suggested')
  ),
  mapping_source text not null default 'user_selected' check (
    mapping_source in (
      'user_selected', 'legacy_backfill', 'deterministic_alias',
      'semantic_suggested', 'custom'
    )
  ),
  confidence numeric(5,4) check (confidence is null or confidence between 0 and 1),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (
    (taxonomy_id is not null and custom_term is null and selection_scope <> 'custom')
    or (taxonomy_id is null and custom_term is not null and selection_scope = 'custom')
  )
);

create unique index matchmaking_taxonomy_mapped_unique
  on public.matchmaking_taxonomy_interests(profile_id, interest_kind, taxonomy_id)
  where taxonomy_id is not null;
create unique index matchmaking_taxonomy_custom_unique
  on public.matchmaking_taxonomy_interests(
    profile_id, interest_kind, normalized_custom_term
  ) where taxonomy_id is null;
create index matchmaking_taxonomy_profile_kind_idx
  on public.matchmaking_taxonomy_interests(profile_id, interest_kind);
create trigger matchmaking_taxonomy_interests_set_updated_at
before update on public.matchmaking_taxonomy_interests
for each row execute function public.set_updated_at();

create table public.tender_taxonomy_mappings (
  id bigint generated by default as identity primary key,
  tender_id bigint not null references public.tenders(id) on delete cascade,
  lot_key text not null default '',
  source_term text not null check (length(trim(source_term)) between 2 and 1000),
  normalized_source_term text generated always as (
    public.normalize_medical_product_term(source_term)
  ) stored,
  taxonomy_id bigint not null references public.medical_product_taxonomy(id)
    on delete restrict,
  mapping_source text not null check (
    mapping_source in ('deterministic_name', 'verified_alias', 'admin', 'semantic_suggested')
  ),
  confidence numeric(5,4) not null check (confidence between 0 and 1),
  status text not null default 'approved' check (
    status in ('approved', 'review_required', 'rejected')
  ),
  evidence jsonb not null default '{}'::jsonb check (jsonb_typeof(evidence) = 'object'),
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (tender_id, lot_key, normalized_source_term, taxonomy_id)
);

create index tender_taxonomy_tender_lot_idx
  on public.tender_taxonomy_mappings(tender_id, lot_key, taxonomy_id)
  where status = 'approved';
create index tender_taxonomy_taxonomy_idx
  on public.tender_taxonomy_mappings(taxonomy_id, tender_id)
  where status = 'approved';
create trigger tender_taxonomy_mappings_set_updated_at
before update on public.tender_taxonomy_mappings
for each row execute function public.set_updated_at();

create table public.medical_product_taxonomy_review_queue (
  id bigint generated by default as identity primary key,
  normalized_term text not null check (length(normalized_term) between 2 and 240),
  sample_term text not null check (length(trim(sample_term)) between 2 and 500),
  source_context text not null check (
    source_context in ('matchmaking_custom', 'product', 'tender', 'semantic_suggestion')
  ),
  company_id bigint references public.companies(id) on delete cascade,
  product_id bigint references public.products(id) on delete cascade,
  tender_id bigint references public.tenders(id) on delete cascade,
  suggested_taxonomy_id bigint references public.medical_product_taxonomy(id)
    on delete set null,
  confidence numeric(5,4) check (confidence is null or confidence between 0 and 1),
  status text not null default 'pending' check (
    status in ('pending', 'approved', 'rejected', 'keep_custom')
  ),
  occurrence_count integer not null default 1 check (occurrence_count > 0),
  metadata jsonb not null default '{}'::jsonb check (jsonb_typeof(metadata) = 'object'),
  reviewed_by uuid references auth.users(id) on delete set null,
  reviewed_at timestamptz,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  unique (normalized_term, source_context, company_id)
);

create index medical_product_taxonomy_review_status_idx
  on public.medical_product_taxonomy_review_queue(status, last_seen_at desc);

-- Seed the catalog-derived v1 hierarchy. Families without current products are
-- deliberately broad expansion points and are never assigned automatically.
insert into public.medical_product_taxonomy
  (hierarchy_level, node_type, canonical_name, slug, description, sort_order)
values
  (1, 'family', 'Equipment Covers', 'equipment-covers', 'Sterile and non-sterile protective covers and drapes for medical equipment.', 10),
  (1, 'family', 'Surgical Drapes & Packs', 'surgical-drapes-packs', 'Procedure-specific surgical drapes, packs and sterile-field systems.', 20),
  (1, 'family', 'Surgical Gowns & Apparel', 'surgical-gowns-apparel', 'Protective surgical gowns and medical apparel.', 30),
  (1, 'family', 'Sterilization Products', 'sterilization-products', 'Sterilization monitoring, packaging and process-control products.', 40),
  (1, 'family', 'Infection Prevention & Hygiene', 'infection-prevention-hygiene', 'Products for infection prevention, disinfection and hygienic care.', 50),
  (1, 'family', 'Wound Care', 'wound-care', 'Dressings, closure and wound-management products.', 60),
  (1, 'family', 'Drainage & Fluid Management', 'drainage-fluid-management', 'Drainage systems, collection pouches and fluid-management consumables.', 70),
  (1, 'family', 'Respiratory & Anesthesia', 'respiratory-anesthesia', 'Respiratory, airway and anesthesia products.', 80),
  (1, 'family', 'Diagnostic Products', 'diagnostic-products', 'Diagnostic devices, tests and related consumables.', 90),
  (1, 'family', 'Patient Care', 'patient-care', 'Products used in routine patient support and care.', 100),
  (1, 'family', 'Surgical Instruments & Accessories', 'surgical-instruments-accessories', 'Surgical instruments and powered/electrosurgical accessories.', 110),
  (1, 'family', 'Other Medical Consumables', 'other-medical-consumables', 'Medical consumables that require more specific classification before matching.', 120)
on conflict (slug) do nothing;

insert into public.medical_product_taxonomy
  (parent_id, hierarchy_level, node_type, canonical_name, slug, description, sort_order)
values
  ((select id from public.medical_product_taxonomy where slug='equipment-covers'), 2, 'category', 'Ultrasound Probe Covers', 'ultrasound-probe-covers', 'Protective covers and sheaths for ultrasound probes and transducers.', 10),
  ((select id from public.medical_product_taxonomy where slug='equipment-covers'), 2, 'category', 'C-Arm Covers', 'c-arm-covers', 'Protective covers and drapes for C-arm and fluoroscopy equipment.', 20),
  ((select id from public.medical_product_taxonomy where slug='equipment-covers'), 2, 'category', 'Camera Covers', 'camera-covers', 'Protective sterile covers and sleeves for surgical and endoscopic cameras.', 30),
  ((select id from public.medical_product_taxonomy where slug='equipment-covers'), 2, 'category', 'Microscope Drapes', 'microscope-drapes', 'Sterile drapes and covers for surgical microscopes.', 40),
  ((select id from public.medical_product_taxonomy where slug='equipment-covers'), 2, 'category', 'Endoscope Covers', 'endoscope-covers', 'Protective covers and sheaths for endoscopes.', 50),
  ((select id from public.medical_product_taxonomy where slug='equipment-covers'), 2, 'category', 'Mayo Stand Covers', 'mayo-stand-covers', 'Sterile protective covers for Mayo instrument stands.', 60),
  ((select id from public.medical_product_taxonomy where slug='surgical-drapes-packs'), 2, 'category', 'General Surgical Drapes', 'general-surgical-drapes', 'General and specialty sterile surgical drapes.', 10),
  ((select id from public.medical_product_taxonomy where slug='surgical-drapes-packs'), 2, 'category', 'General Procedure Packs', 'general-procedure-packs', 'Universal, laparotomy and general-surgery procedure packs.', 20),
  ((select id from public.medical_product_taxonomy where slug='surgical-drapes-packs'), 2, 'category', 'Cardiovascular Procedure Packs', 'cardiovascular-procedure-packs', 'Angiography, bypass and thoracic procedure packs.', 30),
  ((select id from public.medical_product_taxonomy where slug='surgical-drapes-packs'), 2, 'category', 'Obstetric & Gynaecology Packs', 'obstetric-gynaecology-packs', 'Cesarean, gynaecology and related procedure packs.', 40),
  ((select id from public.medical_product_taxonomy where slug='surgical-drapes-packs'), 2, 'category', 'Endoscopy & Urology Packs', 'endoscopy-urology-packs', 'Laparoscopy, cystoscopy and transurethral procedure packs.', 50),
  ((select id from public.medical_product_taxonomy where slug='surgical-drapes-packs'), 2, 'category', 'Orthopedic Procedure Packs', 'orthopedic-procedure-packs', 'Hip, extremity and arthroscopy procedure packs.', 60),
  ((select id from public.medical_product_taxonomy where slug='surgical-drapes-packs'), 2, 'category', 'Specialty Procedure Packs', 'specialty-procedure-packs', 'ENT, chemotherapy, ophthalmology and other specialty packs.', 70),
  ((select id from public.medical_product_taxonomy where slug='surgical-gowns-apparel'), 2, 'category', 'Sterile Surgical Gowns', 'sterile-surgical-gowns', 'Sterile protective gowns for surgical use.', 10),
  ((select id from public.medical_product_taxonomy where slug='surgical-gowns-apparel'), 2, 'category', 'Non-Sterile Medical Gowns', 'non-sterile-medical-gowns', 'Non-sterile protective gowns and apparel.', 20),
  ((select id from public.medical_product_taxonomy where slug='sterilization-products'), 2, 'category', 'Sterilization Indicators', 'sterilization-indicators', 'Chemical and biological sterilization indicators.', 10),
  ((select id from public.medical_product_taxonomy where slug='sterilization-products'), 2, 'category', 'Sterilization Test Packs', 'sterilization-test-packs', 'Bowie-Dick, Helix and other sterilization test packages.', 20),
  ((select id from public.medical_product_taxonomy where slug='sterilization-products'), 2, 'category', 'Sterilization Packaging', 'sterilization-packaging', 'Sterilization reels, pouches and packaging materials.', 30),
  ((select id from public.medical_product_taxonomy where slug='sterilization-products'), 2, 'category', 'Sterilization Process Accessories', 'sterilization-process-accessories', 'Autoclave tapes, labels, seals, filters and instrument protection.', 40),
  ((select id from public.medical_product_taxonomy where slug='sterilization-products'), 2, 'category', 'Washer Control Products', 'washer-control-products', 'Monitoring and control products for washer-disinfectors.', 50),
  ((select id from public.medical_product_taxonomy where slug='drainage-fluid-management'), 2, 'category', 'Chest Drainage Systems', 'chest-drainage-systems', 'Pleural and chest drainage systems.', 10),
  ((select id from public.medical_product_taxonomy where slug='drainage-fluid-management'), 2, 'category', 'Fluid Collection Pouches', 'fluid-collection-pouches', 'Surgical fluid collection and drainage pouches.', 20),
  ((select id from public.medical_product_taxonomy where slug='surgical-instruments-accessories'), 2, 'category', 'Electrosurgical Accessories', 'electrosurgical-accessories', 'Electrosurgical pencils and compatible accessories.', 10),
  ((select id from public.medical_product_taxonomy where slug='other-medical-consumables'), 2, 'category', 'Medical Adhesive Products', 'medical-adhesive-products', 'Medical tapes and double-sided adhesive components.', 10),
  ((select id from public.medical_product_taxonomy where slug='infection-prevention-hygiene'), 2, 'category', 'Disinfectants & Antiseptics', 'disinfectants-antiseptics', 'Products for disinfection and antisepsis.', 10),
  ((select id from public.medical_product_taxonomy where slug='wound-care'), 2, 'category', 'Dressings & Bandages', 'dressings-bandages', 'Wound dressings and bandage materials.', 10),
  ((select id from public.medical_product_taxonomy where slug='respiratory-anesthesia'), 2, 'category', 'Anesthesia Equipment', 'anesthesia-equipment', 'Anesthesia machines and related equipment.', 10),
  ((select id from public.medical_product_taxonomy where slug='respiratory-anesthesia'), 2, 'category', 'Respiratory Ventilation', 'respiratory-ventilation', 'Pulmonary ventilators and respiratory equipment.', 20),
  ((select id from public.medical_product_taxonomy where slug='diagnostic-products'), 2, 'category', 'Medical Imaging Equipment', 'medical-imaging-equipment', 'X-ray and other diagnostic imaging systems.', 10),
  ((select id from public.medical_product_taxonomy where slug='patient-care'), 2, 'category', 'Patient Support Products', 'patient-support-products', 'General patient support and care products.', 10)
on conflict (slug) do nothing;

insert into public.medical_product_aliases
  (taxonomy_id, alias_text, source, confidence)
values
  ((select id from public.medical_product_taxonomy where slug='ultrasound-probe-covers'), 'Ultrasound Probe Cover', 'seed', 1),
  ((select id from public.medical_product_taxonomy where slug='ultrasound-probe-covers'), 'Ultrasound Transducer Cover', 'seed', 1),
  ((select id from public.medical_product_taxonomy where slug='ultrasound-probe-covers'), 'Ultrasound Transducer Sheath', 'seed', 1),
  ((select id from public.medical_product_taxonomy where slug='ultrasound-probe-covers'), 'Probe Sheath', 'seed', .98),
  ((select id from public.medical_product_taxonomy where slug='ultrasound-probe-covers'), 'Ultrasound Sheath', 'seed', .98),
  ((select id from public.medical_product_taxonomy where slug='ultrasound-probe-covers'), 'Sterile Probe Cover', 'seed', .98),
  ((select id from public.medical_product_taxonomy where slug='ultrasound-probe-covers'), 'Sterile Ultrasound Transducer Sleeve', 'seed', .98),
  ((select id from public.medical_product_taxonomy where slug='ultrasound-probe-covers'), 'Protective sterile sheath for ultrasound transducer', 'seed', .98),
  ((select id from public.medical_product_taxonomy where slug='c-arm-covers'), 'C-Arm Cover', 'seed', 1),
  ((select id from public.medical_product_taxonomy where slug='c-arm-covers'), 'C Arm Drape', 'seed', 1),
  ((select id from public.medical_product_taxonomy where slug='c-arm-covers'), 'C-Arm Protective Cover', 'seed', 1),
  ((select id from public.medical_product_taxonomy where slug='c-arm-covers'), 'Sterile C-Arm Equipment Drape', 'seed', 1),
  ((select id from public.medical_product_taxonomy where slug='c-arm-covers'), 'Sterile C-Arm Drapes', 'seed', .98),
  ((select id from public.medical_product_taxonomy where slug='c-arm-covers'), 'Scopy / Fluoroscopy Drapes', 'catalog', 1),
  ((select id from public.medical_product_taxonomy where slug='camera-covers'), 'Camera Cover', 'seed', 1),
  ((select id from public.medical_product_taxonomy where slug='camera-covers'), 'Camera Covers', 'catalog', 1),
  ((select id from public.medical_product_taxonomy where slug='camera-covers'), 'Sterile Camera Drape', 'seed', 1),
  ((select id from public.medical_product_taxonomy where slug='camera-covers'), 'Camera Sleeve', 'seed', .98),
  ((select id from public.medical_product_taxonomy where slug='camera-covers'), 'Surgical Camera Sleeves', 'seed', .98),
  ((select id from public.medical_product_taxonomy where slug='camera-covers'), 'Endoscopic Camera Cover', 'seed', .98),
  ((select id from public.medical_product_taxonomy where slug='general-surgical-drapes'), 'Sterile Surgical Drapes', 'seed', .98),
  ((select id from public.medical_product_taxonomy where slug='general-surgical-drapes'), 'Surgical Drapes', 'seed', .98),
  ((select id from public.medical_product_taxonomy where slug='general-surgical-drapes'), 'Surgical Coverage Material', 'seed', .96),
  ((select id from public.medical_product_taxonomy where slug='sterilization-test-packs'), 'Bowie & Dick Test', 'seed', 1),
  ((select id from public.medical_product_taxonomy where slug='sterilization-test-packs'), 'Bowie Dick Test Pack', 'seed', 1),
  ((select id from public.medical_product_taxonomy where slug='sterilization-indicators'), 'Sterilisation Indicators', 'seed', 1),
  ((select id from public.medical_product_taxonomy where slug='disinfectants-antiseptics'), 'Disinfectants', 'seed', 1),
  ((select id from public.medical_product_taxonomy where slug='dressings-bandages'), 'Dressing Materials', 'seed', .98),
  ((select id from public.medical_product_taxonomy where slug='dressings-bandages'), 'Bandage Materials', 'seed', .98)
on conflict (normalized_alias, language_code) do nothing;

-- Exact, catalog-reviewed mappings. Commercial names and legacy categories are
-- intentionally preserved unchanged.
with catalog_map(product_name, taxonomy_slug) as (
  values
    ('Angiography Pack', 'cardiovascular-procedure-packs'),
    ('By-Pass Pack', 'cardiovascular-procedure-packs'),
    ('C-Section Packs', 'obstetric-gynaecology-packs'),
    ('Camera Covers', 'camera-covers'),
    ('Chemotherapy Pack', 'specialty-procedure-packs'),
    ('Cystoscopy Pack', 'endoscopy-urology-packs'),
    ('E.N.T Pack', 'specialty-procedure-packs'),
    ('ESU Pencil', 'electrosurgical-accessories'),
    ('Extremity Pack', 'orthopedic-procedure-packs'),
    ('General Surgery Pack', 'general-procedure-packs'),
    ('Gynaecology Pack', 'obstetric-gynaecology-packs'),
    ('Hip Pack', 'orthopedic-procedure-packs'),
    ('Laparoscopic Pack', 'endoscopy-urology-packs'),
    ('Laparotomy Pack', 'general-procedure-packs'),
    ('Microscope Drapes', 'microscope-drapes'),
    ('Non-Sterile Gowns', 'non-sterile-medical-gowns'),
    ('Ophthalmology Drape', 'general-surgical-drapes'),
    ('Pleural (Chest) Drainage Systems', 'chest-drainage-systems'),
    ('Shoulder Arthroscopy Pack', 'orthopedic-procedure-packs'),
    ('Sterile Gowns', 'sterile-surgical-gowns'),
    ('T.U.R. Pack', 'endoscopy-urology-packs'),
    ('Thorax Pack', 'cardiovascular-procedure-packs'),
    ('Ultrasound Probe Cover', 'ultrasound-probe-covers'),
    ('Universal Pack', 'general-procedure-packs'),
    ('Double Sided Adhesive', 'medical-adhesive-products'),
    ('Fluid Collection Pouches', 'fluid-collection-pouches'),
    ('Mayo Stand Cover', 'mayo-stand-covers'),
    ('OP-Tape', 'medical-adhesive-products'),
    ('Scopy / Fluoroscopy Drapes', 'c-arm-covers'),
    ('Autoclave Tapes', 'sterilization-process-accessories'),
    ('Autoclave Test Package (Bowie Dick / Helix)', 'sterilization-test-packs'),
    ('Biological Indicators', 'sterilization-indicators'),
    ('Container Accessories (Seal / Filter)', 'sterilization-process-accessories'),
    ('Documentation Labels and Label Gun', 'sterilization-process-accessories'),
    ('Instrument Protector', 'sterilization-process-accessories'),
    ('Sterilization Chemical Indicators', 'sterilization-indicators'),
    ('Sterilization Reels, Pouches & Packaging', 'sterilization-packaging'),
    ('Washer Control Products', 'washer-control-products')
)
insert into public.product_taxonomy_mappings (
  product_id, taxonomy_id, mapping_source, confidence, status, source_text
)
select product.id, taxonomy.id, 'seed_catalog', 1, 'approved', product.name
from catalog_map mapping
join public.products product on product.name = mapping.product_name
join public.medical_product_taxonomy taxonomy on taxonomy.slug = mapping.taxonomy_slug
where product.is_active
on conflict (product_id, taxonomy_id) do nothing;

-- Deterministic high-confidence backfill of existing matchmaking phrases.
with legacy_terms as (
  select profile.id as profile_id, 'offered'::text as interest_kind, term
  from public.matchmaking_profiles profile, unnest(profile.offered_products) term
  union all
  select profile.id, 'interested', term
  from public.matchmaking_profiles profile, unnest(profile.interested_products) term
), resolved as (
  select distinct on (legacy.profile_id, legacy.interest_kind, normalized.normalized_term)
    legacy.profile_id,
    legacy.interest_kind,
    alias.taxonomy_id,
    taxonomy.node_type,
    legacy.term,
    alias.confidence,
    normalized.normalized_term
  from legacy_terms legacy
  cross join lateral (
    select public.normalize_medical_product_term(legacy.term) as normalized_term
  ) normalized
  join public.medical_product_aliases alias
    on alias.normalized_alias = normalized.normalized_term
   and alias.is_active and alias.verification_status = 'approved'
   and alias.confidence >= .95
  join public.medical_product_taxonomy taxonomy
    on taxonomy.id = alias.taxonomy_id and taxonomy.is_active
  order by legacy.profile_id, legacy.interest_kind, normalized.normalized_term,
    alias.confidence desc, alias.id
)
insert into public.matchmaking_taxonomy_interests (
  profile_id, interest_kind, taxonomy_id, selection_scope,
  resolution_status, mapping_source, confidence
)
select profile_id, interest_kind, taxonomy_id, node_type,
  'mapped', 'legacy_backfill', confidence
from resolved
on conflict do nothing;

-- Unmapped historical phrases enter review without being reclassified.
with legacy_terms as (
  select profile.company_id, term
  from public.matchmaking_profiles profile,
    unnest(profile.offered_products || profile.interested_products || profile.product_categories) term
), unresolved as (
  select company_id,
    public.normalize_medical_product_term(term) normalized_term,
    min(term) sample_term,
    count(*)::integer occurrence_count
  from legacy_terms legacy
  where length(public.normalize_medical_product_term(term)) >= 2
    and not exists (
      select 1 from public.medical_product_taxonomy taxonomy
      where taxonomy.normalized_name = public.normalize_medical_product_term(term)
        and taxonomy.is_active
    )
    and not exists (
      select 1 from public.medical_product_aliases alias
      where alias.normalized_alias = public.normalize_medical_product_term(term)
        and alias.is_active and alias.verification_status = 'approved'
    )
  group by company_id, public.normalize_medical_product_term(term)
)
insert into public.medical_product_taxonomy_review_queue (
  normalized_term, sample_term, source_context, company_id, occurrence_count,
  metadata
)
select normalized_term, sample_term, 'matchmaking_custom', company_id,
  occurrence_count, jsonb_build_object('source', 'legacy_backfill')
from unresolved
on conflict (normalized_term, source_context, company_id) do update
set occurrence_count = greatest(
  public.medical_product_taxonomy_review_queue.occurrence_count,
  excluded.occurrence_count
), last_seen_at = now();

-- Public taxonomy search and deterministic resolver.
create or replace function public.search_medical_product_taxonomy_v1(
  p_query text default null,
  p_limit integer default 40
)
returns table (
  id bigint,
  parent_id bigint,
  hierarchy_level smallint,
  node_type text,
  canonical_name text,
  slug text,
  description text,
  aliases jsonb,
  match_quality numeric
)
language sql
stable
security definer
set search_path = public, pg_temp
as $function$
  with candidates as (
    select taxonomy.*,
      greatest(
        case when nullif(public.normalize_medical_product_term(p_query), '') is null then 1
             when taxonomy.normalized_name = public.normalize_medical_product_term(p_query) then 1
             when taxonomy.normalized_name like '%' || public.normalize_medical_product_term(p_query) || '%' then .9
             else public.medical_product_term_similarity(p_query, taxonomy.canonical_name)
        end,
        coalesce((
          select max(case
            when alias.normalized_alias = public.normalize_medical_product_term(p_query) then alias.confidence
            when alias.normalized_alias like '%' || public.normalize_medical_product_term(p_query) || '%' then alias.confidence * .9
            else public.medical_product_term_similarity(p_query, alias.alias_text) * alias.confidence
          end)
          from public.medical_product_aliases alias
          where alias.taxonomy_id = taxonomy.id
            and alias.is_active and alias.verification_status = 'approved'
        ), 0)
      )::numeric as quality
    from public.medical_product_taxonomy taxonomy
    where taxonomy.is_active
  )
  select candidate.id, candidate.parent_id, candidate.hierarchy_level,
    candidate.node_type, candidate.canonical_name, candidate.slug,
    candidate.description,
    coalesce((
      select jsonb_agg(alias.alias_text order by alias.alias_text)
      from public.medical_product_aliases alias
      where alias.taxonomy_id = candidate.id
        and alias.is_active and alias.verification_status = 'approved'
    ), '[]'::jsonb),
    round(candidate.quality, 4)
  from candidates candidate
  where nullif(public.normalize_medical_product_term(p_query), '') is null
     or candidate.quality >= .2
  order by candidate.quality desc, candidate.hierarchy_level, candidate.sort_order,
    candidate.canonical_name
  limit greatest(1, least(coalesce(p_limit, 40), 100));
$function$;

create or replace function public.resolve_medical_product_term_v1(
  p_term text,
  p_limit integer default 5
)
returns jsonb
language plpgsql
stable
security definer
set search_path = public, pg_temp
as $function$
declare
  normalized_term text := public.normalize_medical_product_term(p_term);
  candidates jsonb := '[]'::jsonb;
  best record;
  resolution text := 'unmapped';
begin
  if length(normalized_term) < 2 or length(coalesce(p_term, '')) > 500 then
    raise exception 'Use a product description between 2 and 500 characters'
      using errcode = '22023';
  end if;

  select * into best
  from public.search_medical_product_taxonomy_v1(p_term, greatest(1, least(p_limit, 10)))
  order by match_quality desc, hierarchy_level desc
  limit 1;

  select coalesce(jsonb_agg(jsonb_build_object(
    'canonical_taxonomy_id', candidate.id,
    'canonical_name', candidate.canonical_name,
    'parent_id', candidate.parent_id,
    'node_type', candidate.node_type,
    'confidence', candidate.match_quality,
    'source_text', p_term,
    'source', case
      when candidate.match_quality = 1 then 'exact_or_verified_alias'
      else 'deterministic_normalized_name'
    end
  ) order by candidate.match_quality desc), '[]'::jsonb)
  into candidates
  from public.search_medical_product_taxonomy_v1(
    p_term, greatest(1, least(p_limit, 10))
  ) candidate;

  resolution := case
    when best.match_quality >= .95 then 'high_confidence'
    when best.match_quality >= .65 then 'medium_confidence'
    else 'unmapped'
  end;

  return jsonb_build_object(
    'source_text', p_term,
    'normalized_source_text', normalized_term,
    'resolution', resolution,
    'recommended', case when resolution = 'unmapped' then null else
      jsonb_build_object(
        'canonical_taxonomy_id', best.id,
        'canonical_name', best.canonical_name,
        'node_type', best.node_type,
        'confidence', best.match_quality,
        'reasoning', case
          when best.match_quality = 1 then 'Exact canonical name or approved alias.'
          else 'Deterministic normalized-term similarity; user confirmation required.'
        end,
        'source_text', p_term
      ) end,
    'alternatives', candidates,
    'semantic_provider_used', false
  );
end;
$function$;

create or replace function public.save_matchmaking_taxonomy_interests_v1(
  p_profile_id uuid,
  p_interests jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $function$
declare
  item jsonb;
  profile public.matchmaking_profiles%rowtype;
  taxonomy public.medical_product_taxonomy%rowtype;
  safe_kind text;
  safe_custom text;
  inserted_count integer := 0;
begin
  if auth.uid() is null then
    raise exception 'Authentication required' using errcode = '42501';
  end if;
  select * into profile from public.matchmaking_profiles
  where id = p_profile_id and user_id = auth.uid();
  if profile.id is null then
    raise exception 'Matchmaking profile not found or access denied'
      using errcode = '42501';
  end if;
  if jsonb_typeof(p_interests) <> 'array' or jsonb_array_length(p_interests) > 40 then
    raise exception 'Provide an array of at most 40 taxonomy interests'
      using errcode = '22023';
  end if;

  delete from public.matchmaking_taxonomy_interests
  where profile_id = p_profile_id;

  for item in select value from jsonb_array_elements(p_interests)
  loop
    safe_kind := item ->> 'interest_kind';
    if safe_kind not in ('offered', 'interested') then
      raise exception 'Each taxonomy interest needs offered or interested kind'
        using errcode = '22023';
    end if;
    if nullif(item ->> 'taxonomy_id', '') is not null then
      select * into taxonomy from public.medical_product_taxonomy
      where id = (item ->> 'taxonomy_id')::bigint and is_active;
      if taxonomy.id is null then
        raise exception 'Selected taxonomy node is unavailable'
          using errcode = '22023';
      end if;
      insert into public.matchmaking_taxonomy_interests (
        profile_id, interest_kind, taxonomy_id, selection_scope,
        resolution_status, mapping_source, confidence
      ) values (
        p_profile_id, safe_kind, taxonomy.id, taxonomy.node_type,
        'mapped', 'user_selected', 1
      ) on conflict do nothing;
    else
      safe_custom := trim(coalesce(item ->> 'custom_term', ''));
      if length(safe_custom) not between 2 and 240 then
        raise exception 'Custom product descriptions must be 2 to 240 characters'
          using errcode = '22023';
      end if;
      insert into public.matchmaking_taxonomy_interests (
        profile_id, interest_kind, custom_term, selection_scope,
        resolution_status, mapping_source
      ) values (
        p_profile_id, safe_kind, safe_custom, 'custom', 'custom', 'custom'
      ) on conflict do nothing;
      insert into public.medical_product_taxonomy_review_queue (
        normalized_term, sample_term, source_context, company_id, metadata
      ) values (
        public.normalize_medical_product_term(safe_custom), safe_custom,
        'matchmaking_custom', profile.company_id,
        jsonb_build_object('profile_id', profile.id)
      ) on conflict (normalized_term, source_context, company_id) do update
      set occurrence_count = public.medical_product_taxonomy_review_queue.occurrence_count + 1,
          last_seen_at = now(), sample_term = excluded.sample_term;
    end if;
    inserted_count := inserted_count + 1;
  end loop;

  return jsonb_build_object(
    'profile_id', p_profile_id,
    'saved_count', inserted_count,
    'provider_calls', 0
  );
end;
$function$;

create or replace function public.get_matchmaking_taxonomy_interests_v1(
  p_profile_id uuid
)
returns jsonb
language plpgsql
stable
security definer
set search_path = public, pg_temp
as $function$
declare
  result jsonb;
begin
  if not exists (
    select 1 from public.matchmaking_profiles profile
    where profile.id = p_profile_id and profile.user_id = auth.uid()
  ) and not public.is_admin() then
    raise exception 'Matchmaking profile not found or access denied'
      using errcode = '42501';
  end if;
  select coalesce(jsonb_agg(
    to_jsonb(interest) || jsonb_build_object(
      'canonical_name', taxonomy.canonical_name,
      'parent_id', taxonomy.parent_id,
      'node_type', taxonomy.node_type
    ) order by interest.interest_kind, taxonomy.hierarchy_level,
      taxonomy.canonical_name, interest.custom_term
  ), '[]'::jsonb)
  into result
  from public.matchmaking_taxonomy_interests interest
  left join public.medical_product_taxonomy taxonomy
    on taxonomy.id = interest.taxonomy_id
  where interest.profile_id = p_profile_id;
  return result;
end;
$function$;

create or replace function public.set_product_taxonomy_mapping_v1(
  p_product_id bigint,
  p_taxonomy_id bigint,
  p_source_text text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $function$
declare
  product public.products%rowtype;
  taxonomy public.medical_product_taxonomy%rowtype;
begin
  select * into product from public.products where id = p_product_id;
  if product.id is null then raise exception 'Product not found' using errcode='P0002'; end if;
  if not public.is_admin() and not exists (
    select 1 from public.companies company
    where company.id = product.company_id and company.owner_id = auth.uid()
  ) then
    raise exception 'Product mapping access denied' using errcode='42501';
  end if;
  select * into taxonomy from public.medical_product_taxonomy
  where id = p_taxonomy_id and is_active;
  if taxonomy.id is null then
    raise exception 'Selected taxonomy node is unavailable' using errcode='22023';
  end if;
  update public.product_taxonomy_mappings
  set is_primary = false, updated_at = now()
  where product_id = p_product_id and is_primary;
  insert into public.product_taxonomy_mappings (
    product_id, taxonomy_id, mapping_source, confidence, status,
    source_text, is_primary, created_by
  ) values (
    p_product_id, p_taxonomy_id,
    case when public.is_admin() then 'admin' else 'owner_selected' end,
    1, 'approved', left(coalesce(p_source_text, product.name), 500), true,
    auth.uid()
  ) on conflict (product_id, taxonomy_id) do update
  set mapping_source = excluded.mapping_source,
      confidence = 1,
      status = 'approved',
      source_text = excluded.source_text,
      is_primary = true,
      updated_at = now();
  return jsonb_build_object(
    'product_id', p_product_id,
    'taxonomy_id', p_taxonomy_id,
    'canonical_name', taxonomy.canonical_name
  );
end;
$function$;

create or replace function public.medical_taxonomy_pair_score_v1(
  p_offered_taxonomy_id bigint,
  p_interested_taxonomy_id bigint
)
returns integer
language sql
stable
set search_path = public, pg_temp
as $function$
  with recursive offered_path as (
    select id, parent_id, hierarchy_level from public.medical_product_taxonomy
    where id = p_offered_taxonomy_id and is_active
    union all
    select parent.id, parent.parent_id, parent.hierarchy_level
    from public.medical_product_taxonomy parent
    join offered_path child on child.parent_id = parent.id
    where parent.is_active
  ), interested_path as (
    select id, parent_id, hierarchy_level from public.medical_product_taxonomy
    where id = p_interested_taxonomy_id and is_active
    union all
    select parent.id, parent.parent_id, parent.hierarchy_level
    from public.medical_product_taxonomy parent
    join interested_path child on child.parent_id = parent.id
    where parent.is_active
  )
  select case
    when p_offered_taxonomy_id = p_interested_taxonomy_id then 100
    when exists (select 1 from offered_path where id = p_interested_taxonomy_id)
      or exists (select 1 from interested_path where id = p_offered_taxonomy_id) then 75
    when exists (
      select 1 from public.medical_product_taxonomy offered
      join public.medical_product_taxonomy interested
        on offered.parent_id = interested.parent_id
      where offered.id = p_offered_taxonomy_id
        and interested.id = p_interested_taxonomy_id
        and offered.parent_id is not null
    ) then 25
    when exists (
      select 1 from offered_path offered
      join interested_path interested on interested.id = offered.id
      where offered.hierarchy_level = 1
    ) then 10
    else 0
  end;
$function$;

create or replace function public.clear_product_taxonomy_mapping_v1(
  p_product_id bigint
)
returns boolean
language plpgsql
security definer
set search_path = public, pg_temp
as $function$
declare product public.products%rowtype;
begin
  select * into product from public.products where id=p_product_id;
  if product.id is null then raise exception 'Product not found' using errcode='P0002'; end if;
  if not public.is_admin() and not exists(select 1 from public.companies company
    where company.id=product.company_id and company.owner_id=auth.uid()) then
    raise exception 'Product mapping access denied' using errcode='42501';
  end if;
  update public.product_taxonomy_mappings set is_primary=false,
    status='review_required',updated_at=now()
  where product_id=p_product_id and is_primary and status='approved';
  return found;
end;
$function$;

create or replace function public.queue_product_taxonomy_review_v1(
  p_product_id bigint,
  p_term text
)
returns bigint
language plpgsql
security definer
set search_path = public, pg_temp
as $function$
declare product public.products%rowtype; review_id bigint; safe_term text:=trim(coalesce(p_term,''));
begin
  select * into product from public.products where id=p_product_id;
  if product.id is null then raise exception 'Product not found' using errcode='P0002'; end if;
  if not public.is_admin() and not exists(select 1 from public.companies company
    where company.id=product.company_id and company.owner_id=auth.uid()) then
    raise exception 'Product review access denied' using errcode='42501';
  end if;
  if length(safe_term) not between 2 and 240 then
    raise exception 'Custom product description must be 2 to 240 characters' using errcode='22023';
  end if;
  insert into public.medical_product_taxonomy_review_queue(
    normalized_term,sample_term,source_context,company_id,product_id,metadata
  ) values(public.normalize_medical_product_term(safe_term),safe_term,'product',
    product.company_id,product.id,jsonb_build_object('source','product_form'))
  on conflict(normalized_term,source_context,company_id) do update set
    occurrence_count=public.medical_product_taxonomy_review_queue.occurrence_count+1,
    last_seen_at=now(),sample_term=excluded.sample_term,product_id=excluded.product_id
  returning id into review_id;
  return review_id;
end;
$function$;

create or replace function public.mm_taxonomy_product_compatibility_v1(
  p_source_profile_id uuid,
  p_target_profile_id uuid
)
returns jsonb
language plpgsql
stable
security definer
set search_path = public, pg_temp
as $function$
declare
  source_profile public.matchmaking_profiles%rowtype;
  target_profile public.matchmaking_profiles%rowtype;
  offered_profile uuid;
  interested_profile uuid;
  best_score integer := 0;
  evidence jsonb := '[]'::jsonb;
  offered_count integer := 0;
  interested_count integer := 0;
begin
  select * into source_profile from public.matchmaking_profiles
  where id = p_source_profile_id and is_active;
  select * into target_profile from public.matchmaking_profiles
  where id = p_target_profile_id and is_active;
  if source_profile.id is null or target_profile.id is null then
    return jsonb_build_object('available', false, 'score', 0, 'matches', '[]'::jsonb);
  end if;
  if source_profile.role = 'manufacturer' then
    offered_profile := source_profile.id;
    interested_profile := target_profile.id;
  else
    offered_profile := target_profile.id;
    interested_profile := source_profile.id;
  end if;

  with offered as (
    select interest.taxonomy_id, taxonomy.canonical_name,
      'profile'::text source, interest.mapping_source
    from public.matchmaking_taxonomy_interests interest
    join public.medical_product_taxonomy taxonomy
      on taxonomy.id = interest.taxonomy_id and taxonomy.is_active
    where interest.profile_id = offered_profile
      and interest.interest_kind = 'offered'
      and interest.resolution_status = 'mapped'
    union
    select mapping.taxonomy_id, taxonomy.canonical_name,
      'company_product', mapping.mapping_source
    from public.matchmaking_profiles profile
    join public.products product on product.company_id = profile.company_id
      and product.is_active
    join public.product_taxonomy_mappings mapping on mapping.product_id = product.id
      and mapping.status = 'approved' and mapping.is_primary
    join public.medical_product_taxonomy taxonomy
      on taxonomy.id = mapping.taxonomy_id and taxonomy.is_active
    where profile.id = offered_profile
  ), interested as (
    select interest.taxonomy_id, taxonomy.canonical_name,
      interest.selection_scope, interest.mapping_source
    from public.matchmaking_taxonomy_interests interest
    join public.medical_product_taxonomy taxonomy
      on taxonomy.id = interest.taxonomy_id and taxonomy.is_active
    where interest.profile_id = interested_profile
      and interest.interest_kind = 'interested'
      and interest.resolution_status = 'mapped'
  ), pairs as (
    select offered.taxonomy_id offered_id,
      offered.canonical_name offered_name,
      interested.taxonomy_id interested_id,
      interested.canonical_name interested_name,
      interested.selection_scope,
      offered.source,
      public.medical_taxonomy_pair_score_v1(
        offered.taxonomy_id, interested.taxonomy_id
      ) pair_score
    from offered cross join interested
  ), ranked as (
    select *, row_number() over (
      partition by offered_id order by pair_score desc, interested_id
    ) rank_for_offer
    from pairs where pair_score > 0
  )
  select
    coalesce((select max(pair_score) from pairs), 0),
    coalesce((select count(*) from offered), 0),
    coalesce((select count(*) from interested), 0),
    coalesce((select jsonb_agg(jsonb_build_object(
      'offered_taxonomy_id', offered_id,
      'offered_name', offered_name,
      'interested_taxonomy_id', interested_id,
      'interested_name', interested_name,
      'relationship', case pair_score
        when 100 then 'exact_category'
        when 75 then 'broad_family'
        when 25 then 'related_sibling'
        else 'same_family_weak'
      end,
      'score', pair_score,
      'source', source
    ) order by pair_score desc, offered_name) from ranked
      where rank_for_offer = 1 and pair_score >= 25), '[]'::jsonb)
  into best_score, offered_count, interested_count, evidence;

  return jsonb_build_object(
    'available', offered_count > 0 and interested_count > 0,
    'score', best_score,
    'offered_count', offered_count,
    'interested_count', interested_count,
    'matches', evidence,
    'summary', case
      when best_score = 100 then 'Exact medical-product taxonomy categories align.'
      when best_score = 75 then 'A broad product-family interest includes the supplied category.'
      when best_score >= 25 then 'Related product categories need qualification.'
      when offered_count = 0 or interested_count = 0 then 'Structured product taxonomy data is incomplete.'
      else 'The selected product families do not overlap.'
    end,
    'scoring', jsonb_build_object(
      'exact_category', 100,
      'parent_or_child', 75,
      'sibling_category', 25,
      'same_family_distant', 10,
      'unrelated_family', 0
    )
  );
end;
$function$;

-- Preserve the established 40/20/15/15/10 weighting while replacing only the
-- product dimension with taxonomy evidence when structured mappings exist.
create or replace function public.refresh_matchmaking_matches(p_profile_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $function$
declare
  source_profile public.matchmaking_profiles;
  target_profile public.matchmaking_profiles;
  taxonomy_result jsonb;
  taxonomy_value integer;
  legacy_product_value integer;
  product_value integer;
  geography_value integer;
  role_value integer;
  certification_value integer;
  commercial_value integer;
  total_value integer;
  processed integer := 0;
begin
  select * into source_profile
  from public.matchmaking_profiles
  where id = p_profile_id and user_id = auth.uid();
  if source_profile.id is null then
    raise exception 'Matchmaking profile not found or access denied';
  end if;

  for target_profile in
    select * from public.matchmaking_profiles
    where is_active = true and id <> source_profile.id
  loop
    if source_profile.role = 'manufacturer' then
      legacy_product_value := public.mm_overlap_score(
        source_profile.offered_products || source_profile.product_categories,
        target_profile.interested_products || target_profile.product_categories
      );
    else
      legacy_product_value := public.mm_overlap_score(
        source_profile.interested_products || source_profile.product_categories,
        target_profile.offered_products || target_profile.product_categories
      );
    end if;
    taxonomy_result := public.mm_taxonomy_product_compatibility_v1(
      source_profile.id, target_profile.id
    );
    taxonomy_value := coalesce((taxonomy_result ->> 'score')::integer, 0);
    product_value := case
      when coalesce((taxonomy_result ->> 'available')::boolean, false)
        then greatest(taxonomy_value, legacy_product_value)
      else legacy_product_value
    end;

    geography_value := greatest(
      public.mm_overlap_score(source_profile.target_countries,
        target_profile.served_countries || array[target_profile.country]),
      public.mm_overlap_score(source_profile.served_countries || array[source_profile.country],
        target_profile.target_countries)
    );
    role_value := public.mm_role_fit(source_profile.role, target_profile.role,
      source_profile.partner_types_sought);
    if source_profile.role = 'manufacturer' then
      certification_value := public.mm_overlap_score(
        source_profile.certifications, target_profile.required_certifications);
    else
      certification_value := public.mm_overlap_score(
        source_profile.required_certifications, target_profile.certifications);
    end if;
    commercial_value := public.mm_commercial_score(source_profile, target_profile);
    total_value := round(product_value * .40 + geography_value * .20
      + role_value * .15 + certification_value * .10
      + commercial_value * .15)::integer;

    insert into public.matchmaking_matches (
      source_profile_id, target_profile_id, match_score, confidence_level,
      product_score, geography_score, partner_type_score, certification_score,
      commercial_score, reasons, risks, generated_at, updated_at
    ) values (
      source_profile.id, target_profile.id, total_value,
      case when source_profile.profile_completeness >= 75
             and target_profile.profile_completeness >= 75 then 'high'
           when source_profile.profile_completeness >= 45
             and target_profile.profile_completeness >= 45 then 'medium'
           else 'low' end,
      product_value, geography_value, role_value, certification_value,
      commercial_value,
      jsonb_strip_nulls(jsonb_build_object(
        'products', case
          when taxonomy_value >= 75 then taxonomy_result ->> 'summary'
          when product_value >= 70 then 'Product needs and portfolio overlap'
        end,
        'taxonomy', case
          when coalesce((taxonomy_result ->> 'available')::boolean, false)
            then taxonomy_result
        end,
        'geography', case when geography_value >= 70 then 'Target and served markets overlap' end,
        'partner_type', case when role_value >= 70 then 'Requested partner type matches' end,
        'certifications', case when certification_value >= 70 then 'Certification requirements align' end,
        'commercial', case when commercial_value >= 70 then 'Commercial capacity and preferences align' end
      )),
      jsonb_strip_nulls(jsonb_build_object(
        'profile_data', case when source_profile.profile_completeness < 60
          or target_profile.profile_completeness < 60 then 'One or both profiles are incomplete' end,
        'products', case when product_value < 35 then 'Low confirmed product overlap' end,
        'geography', case when geography_value < 35 then 'Limited confirmed market overlap' end
      )), now(), now()
    )
    on conflict (source_profile_id, target_profile_id) do update set
      match_score = excluded.match_score,
      confidence_level = excluded.confidence_level,
      product_score = excluded.product_score,
      geography_score = excluded.geography_score,
      partner_type_score = excluded.partner_type_score,
      certification_score = excluded.certification_score,
      commercial_score = excluded.commercial_score,
      reasons = excluded.reasons,
      risks = excluded.risks,
      generated_at = excluded.generated_at,
      updated_at = excluded.updated_at;
    processed := processed + 1;
  end loop;
  update public.matchmaking_profiles set last_matched_at=now(), updated_at=now()
  where id=source_profile.id;
  return jsonb_build_object('profile_id', source_profile.id,
    'profiles_processed', processed, 'generated_at', now(),
    'taxonomy_version', 'medical-taxonomy-v1');
end;
$function$;

create or replace function public.mm_build_match_explanation(
  p_match_score integer,
  p_confidence_level text,
  p_product_score integer,
  p_geography_score integer,
  p_partner_type_score integer,
  p_certification_score integer,
  p_commercial_score integer,
  p_reasons jsonb,
  p_risks jsonb
)
returns jsonb
language sql
immutable
set search_path = public, pg_temp
as $function$
  with components(key, reason_key, risk_key, label, score, weight) as (
    values
      ('product', 'products', 'products', 'Product compatibility', coalesce(p_product_score,0), 40),
      ('geography', 'geography', 'geography', 'Market compatibility', coalesce(p_geography_score,0), 20),
      ('partner_type', 'partner_type', 'partner_type', 'Company role compatibility', coalesce(p_partner_type_score,0), 15),
      ('commercial', 'commercial', 'commercial', 'Business relevance', coalesce(p_commercial_score,0), 15),
      ('certification', 'certifications', 'certifications', 'Certification compatibility', coalesce(p_certification_score,0), 10)
  ), explained as (
    select key,label,score,weight,round(score*weight/100.0,1) weighted_points,
      nullif(trim(coalesce(p_reasons->>reason_key,'')),'') reason,
      nullif(trim(coalesce(p_risks->>risk_key,'')),'') risk
    from components
  ), supported as (select * from explained where reason is not null),
  top_drivers as (
    select coalesce(jsonb_agg(jsonb_build_object(
      'key',key,'label',label,'score',score,'weight_percent',weight,
      'weighted_points',weighted_points,'reason',reason,'evidence_status','supported'
    ) order by weighted_points desc,weight desc,label),'[]'::jsonb) value
    from (select * from supported order by weighted_points desc,weight desc,label limit 3) top_three
  ), all_components as (
    select jsonb_agg(jsonb_build_object(
      'key',key,'label',label,'score',score,'weight_percent',weight,
      'weighted_points',weighted_points,
      'evidence_status',case when reason is not null then 'supported'
        when risk is not null then 'risk' else 'unknown' end,
      'reason',coalesce(reason,risk,'No explicit structured profile evidence is available for this component.')
    ) order by weight desc,label) value from explained
  )
  select jsonb_build_object(
    'version',3,
    'summary',case when (select count(*) from supported)=0 then
      'Directional score only; complete both profiles before relying on this match.'
      when coalesce(p_match_score,0)>=85 then 'Strong fit across the supported structured profile evidence.'
      when coalesce(p_match_score,0)>=70 then 'Promising fit with points that should be validated together.'
      when coalesce(p_match_score,0)>=50 then 'Possible fit; review the evidence gaps before engaging.'
      else 'Limited supported fit; review the risks before engaging.' end,
    'score',coalesce(p_match_score,0),'confidence',coalesce(p_confidence_level,'low'),
    'confidence_note',case coalesce(p_confidence_level,'low')
      when 'high' then 'Both profiles contain enough structured fields for a higher-confidence signal.'
      when 'medium' then 'The score uses partial profile data and must be validated in conversation.'
      else 'Profile evidence is limited; this score is directional, not a guarantee.' end,
    'top_reasons',(select value from top_drivers),
    'components',(select value from all_components),
    'product_evidence',coalesce(p_reasons->'taxonomy','{}'::jsonb),
    'source_reasons',coalesce(p_reasons,'{}'::jsonb),
    'risk_signals',coalesce(p_risks,'{}'::jsonb),
    'method',jsonb_build_object('product_weight_percent',40,
      'geography_weight_percent',20,'partner_type_weight_percent',15,
      'commercial_weight_percent',15,'certification_weight_percent',10,
      'taxonomy_version','medical-taxonomy-v1',
      'unknown_is_not_positive_evidence',true)
  );
$function$;

-- Tender terms are mapped only by exact canonical names or approved aliases.
-- This function never invokes AI and never invents taxonomy nodes.
create or replace function public.refresh_tender_taxonomy_mappings_v1(
  p_tender_id bigint
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $function$
declare
  tender public.tenders%rowtype;
  item jsonb;
  safe_source_term text;
  safe_lot_key text;
  matched_taxonomy_id bigint;
  matched_confidence numeric;
  matched_source text;
  inserted_count integer := 0;
begin
  if not public.is_admin()
     and coalesce(auth.jwt()->>'role','') <> 'service_role' then
    raise exception 'Taxonomy tender mapping access denied' using errcode='42501';
  end if;
  select * into tender from public.tenders where id=p_tender_id;
  if tender.id is null then raise exception 'Tender not found' using errcode='P0002'; end if;

  for item in select value from jsonb_array_elements(coalesce(tender.extracted_products,'[]'::jsonb))
  loop
    safe_source_term := trim(coalesce(
      case when jsonb_typeof(item)='object' then item->>'normalized_product_name' end,
      case when jsonb_typeof(item)='object' then item->>'product_name' end,
      case when jsonb_typeof(item)='string' then item#>>'{}' end,
      ''
    ));
    safe_lot_key := left(coalesce(case when jsonb_typeof(item)='object' then item->>'lot_number' end,''),160);
    if length(safe_source_term) < 2 then continue; end if;

    select taxonomy.id, 1::numeric, 'deterministic_name'
    into matched_taxonomy_id, matched_confidence, matched_source
    from public.medical_product_taxonomy taxonomy
    where taxonomy.is_active
      and taxonomy.normalized_name=public.normalize_medical_product_term(safe_source_term)
    limit 1;
    if matched_taxonomy_id is null then
      select alias.taxonomy_id, alias.confidence, 'verified_alias'
      into matched_taxonomy_id, matched_confidence, matched_source
      from public.medical_product_aliases alias
      join public.medical_product_taxonomy taxonomy
        on taxonomy.id=alias.taxonomy_id and taxonomy.is_active
      where alias.is_active and alias.verification_status='approved'
        and alias.confidence>=.95
        and alias.normalized_alias=public.normalize_medical_product_term(safe_source_term)
      order by alias.confidence desc limit 1;
    end if;
    if matched_taxonomy_id is not null then
      insert into public.tender_taxonomy_mappings(
        tender_id,lot_key,source_term,taxonomy_id,mapping_source,
        confidence,status,evidence,created_by
      ) values (
        p_tender_id,safe_lot_key,left(safe_source_term,1000),matched_taxonomy_id,
        matched_source,matched_confidence,'approved',
        jsonb_build_object('deterministic',true,'provider_calls',0),auth.uid()
      ) on conflict (tender_id,lot_key,normalized_source_term,taxonomy_id)
      do update set confidence=excluded.confidence,status='approved',
        evidence=excluded.evidence,updated_at=now();
      inserted_count:=inserted_count+1;
    end if;
    matched_taxonomy_id:=null; matched_confidence:=null; matched_source:=null;
  end loop;
  return jsonb_build_object('tender_id',p_tender_id,'mapped_terms',inserted_count,
    'provider_calls',0,'taxonomy_version','medical-taxonomy-v1');
end;
$function$;

create or replace function public.get_tender_taxonomy_compatibility_v1(
  p_company_id bigint,
  p_tender_id bigint
)
returns jsonb
language plpgsql
stable
security definer
set search_path = public, pg_temp
as $function$
declare result jsonb;
begin
  if not public.is_admin() and not exists (
    select 1 from public.companies company
    where company.id=p_company_id and company.owner_id=auth.uid()
  ) then raise exception 'Access denied' using errcode='42501'; end if;
  with product_nodes as (
    select product.id product_id,product.name product_name,mapping.taxonomy_id
    from public.products product join public.product_taxonomy_mappings mapping
      on mapping.product_id=product.id and mapping.status='approved' and mapping.is_primary
    where product.company_id=p_company_id and product.is_active
  ), pairs as (
    select product.product_id,product.product_name,tender.lot_key,
      tender.source_term,tender.taxonomy_id tender_taxonomy_id,
      taxonomy.canonical_name,
      public.medical_taxonomy_pair_score_v1(product.taxonomy_id,tender.taxonomy_id) score
    from product_nodes product join public.tender_taxonomy_mappings tender
      on tender.tender_id=p_tender_id and tender.status='approved'
    join public.medical_product_taxonomy taxonomy on taxonomy.id=tender.taxonomy_id
  )
  select jsonb_build_object(
    'version',1,'taxonomy_version','medical-taxonomy-v1',
    'score',coalesce(max(score),0),
    'status',case when coalesce(max(score),0)=100 then 'exact_category'
      when coalesce(max(score),0)>=75 then 'broad_family'
      when coalesce(max(score),0)>=25 then 'review_required' else 'not_supported' end,
    'matches',coalesce(jsonb_agg(jsonb_build_object(
      'product_id',product_id,'product_name',product_name,'lot_key',lot_key,
      'source_term',source_term,'taxonomy_id',tender_taxonomy_id,
      'canonical_name',canonical_name,'score',score
    ) order by score desc,product_name) filter(where score>=25),'[]'::jsonb),
    'provider_calls',0
  ) into result from pairs;
  return coalesce(result,jsonb_build_object('version',1,'score',0,
    'status','not_supported','matches','[]'::jsonb,'provider_calls',0));
end;
$function$;

-- Admin workspace and controlled learning loop.
create or replace function public.get_admin_medical_taxonomy_v1(
  p_query text default null,
  p_limit integer default 200
)
returns jsonb
language plpgsql
stable
security definer
set search_path = public, pg_temp
as $function$
declare result jsonb;
begin
  if not public.is_admin() then raise exception 'Admin access required' using errcode='42501'; end if;
  select jsonb_build_object(
    'taxonomy_version','medical-taxonomy-v1',
    'nodes',coalesce((select jsonb_agg(to_jsonb(node)||jsonb_build_object(
      'alias_count',(select count(*) from public.medical_product_aliases alias where alias.taxonomy_id=node.id and alias.is_active),
      'product_count',(select count(*) from public.product_taxonomy_mappings mapping where mapping.taxonomy_id=node.id and mapping.status='approved'),
      'interest_count',(select count(*) from public.matchmaking_taxonomy_interests interest where interest.taxonomy_id=node.id)
    ) order by node.hierarchy_level,node.sort_order,node.canonical_name)
      from public.medical_product_taxonomy node
      where nullif(public.normalize_medical_product_term(p_query),'') is null
        or node.normalized_name like '%'||public.normalize_medical_product_term(p_query)||'%'
      limit greatest(1,least(coalesce(p_limit,200),500))), '[]'::jsonb),
    'aliases',coalesce((select jsonb_agg(to_jsonb(alias) order by alias.alias_text)
      from public.medical_product_aliases alias
      where alias.is_active and (nullif(public.normalize_medical_product_term(p_query),'') is null
        or alias.normalized_alias like '%'||public.normalize_medical_product_term(p_query)||'%')),'[]'::jsonb),
    'review_queue',coalesce((select jsonb_agg(to_jsonb(review) order by review.last_seen_at desc)
      from (select * from public.medical_product_taxonomy_review_queue
        where status='pending' order by last_seen_at desc limit 200) review),'[]'::jsonb)
  ) into result;
  return result;
end;
$function$;

create or replace function public.admin_upsert_medical_taxonomy_node_v1(
  p_id bigint,
  p_parent_id bigint,
  p_node_type text,
  p_canonical_name text,
  p_slug text,
  p_description text default null,
  p_is_active boolean default true,
  p_sort_order integer default 0
)
returns bigint
language plpgsql
security definer
set search_path = public, pg_temp
as $function$
declare result_id bigint; level_value smallint;
begin
  if not public.is_admin() then raise exception 'Admin access required' using errcode='42501'; end if;
  level_value:=case p_node_type when 'family' then 1 when 'category' then 2 when 'product_type' then 3 else null end;
  if level_value is null then raise exception 'Invalid taxonomy node type' using errcode='22023'; end if;
  if p_id is null then
    insert into public.medical_product_taxonomy(parent_id,hierarchy_level,node_type,
      canonical_name,slug,description,is_active,sort_order,created_by)
    values(p_parent_id,level_value,p_node_type,trim(p_canonical_name),trim(p_slug),
      nullif(trim(p_description),''),p_is_active,p_sort_order,auth.uid()) returning id into result_id;
  else
    update public.medical_product_taxonomy set parent_id=p_parent_id,
      hierarchy_level=level_value,node_type=p_node_type,canonical_name=trim(p_canonical_name),
      slug=trim(p_slug),description=nullif(trim(p_description),''),is_active=p_is_active,
      sort_order=p_sort_order where id=p_id returning id into result_id;
  end if;
  return result_id;
end;
$function$;

create or replace function public.admin_upsert_medical_product_alias_v1(
  p_id bigint,
  p_taxonomy_id bigint,
  p_alias_text text,
  p_language_code text default 'en',
  p_confidence numeric default 1,
  p_is_active boolean default true
)
returns bigint
language plpgsql
security definer
set search_path = public, pg_temp
as $function$
declare result_id bigint;
begin
  if not public.is_admin() then raise exception 'Admin access required' using errcode='42501'; end if;
  if p_id is null then
    insert into public.medical_product_aliases(taxonomy_id,alias_text,language_code,
      source,confidence,verification_status,is_active,created_by)
    values(p_taxonomy_id,trim(p_alias_text),p_language_code,'admin',p_confidence,
      'approved',p_is_active,auth.uid()) returning id into result_id;
  else
    update public.medical_product_aliases set taxonomy_id=p_taxonomy_id,
      alias_text=trim(p_alias_text),language_code=p_language_code,source='admin',
      confidence=p_confidence,verification_status='approved',is_active=p_is_active
    where id=p_id returning id into result_id;
  end if;
  return result_id;
end;
$function$;

create or replace function public.admin_review_medical_product_term_v1(
  p_review_id bigint,
  p_decision text,
  p_taxonomy_id bigint default null,
  p_create_alias boolean default false
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $function$
declare review public.medical_product_taxonomy_review_queue%rowtype;
begin
  if not public.is_admin() then raise exception 'Admin access required' using errcode='42501'; end if;
  if p_decision not in ('approved','rejected','keep_custom') then
    raise exception 'Invalid review decision' using errcode='22023';
  end if;
  select * into review from public.medical_product_taxonomy_review_queue where id=p_review_id for update;
  if review.id is null then raise exception 'Review item not found' using errcode='P0002'; end if;
  if p_decision='approved' and p_taxonomy_id is null then
    raise exception 'Approved terms require a taxonomy node' using errcode='22023';
  end if;
  if p_decision='approved' and p_create_alias then
    insert into public.medical_product_aliases(taxonomy_id,alias_text,source,
      confidence,verification_status,created_by)
    values(p_taxonomy_id,review.sample_term,'approved_custom',1,'approved',auth.uid())
    on conflict(normalized_alias,language_code) do update set
      taxonomy_id=excluded.taxonomy_id,verification_status='approved',is_active=true,
      confidence=1,updated_at=now();
  end if;
  update public.medical_product_taxonomy_review_queue set status=p_decision,
    suggested_taxonomy_id=p_taxonomy_id,reviewed_by=auth.uid(),reviewed_at=now()
  where id=p_review_id;
  return jsonb_build_object('review_id',p_review_id,'status',p_decision,
    'alias_created',p_decision='approved' and p_create_alias);
end;
$function$;

-- RLS and least-privilege grants.
alter table public.medical_product_taxonomy enable row level security;
alter table public.medical_product_aliases enable row level security;
alter table public.product_taxonomy_mappings enable row level security;
alter table public.matchmaking_taxonomy_interests enable row level security;
alter table public.tender_taxonomy_mappings enable row level security;
alter table public.medical_product_taxonomy_review_queue enable row level security;

create policy "public read active medical taxonomy"
on public.medical_product_taxonomy for select to anon, authenticated
using (is_active);
create policy "admins manage medical taxonomy"
on public.medical_product_taxonomy for all to authenticated
using (public.is_admin()) with check (public.is_admin());

create policy "public read approved medical aliases"
on public.medical_product_aliases for select to anon, authenticated
using (is_active and verification_status='approved');
create policy "admins manage medical aliases"
on public.medical_product_aliases for all to authenticated
using (public.is_admin()) with check (public.is_admin());

create policy "public read approved public product taxonomy mappings"
on public.product_taxonomy_mappings for select to anon, authenticated
using (status='approved' and exists(
  select 1 from public.products product
  where product.id=product_taxonomy_mappings.product_id and product.is_active
));
create policy "owners manage own product taxonomy mappings"
on public.product_taxonomy_mappings for all to authenticated
using (exists(select 1 from public.products product join public.companies company
  on company.id=product.company_id where product.id=product_taxonomy_mappings.product_id and company.owner_id=auth.uid())
  or public.is_admin())
with check (exists(select 1 from public.products product join public.companies company
  on company.id=product.company_id where product.id=product_taxonomy_mappings.product_id and company.owner_id=auth.uid())
  or public.is_admin());

create policy "users manage own matchmaking taxonomy interests"
on public.matchmaking_taxonomy_interests for all to authenticated
using (exists(select 1 from public.matchmaking_profiles profile
  where profile.id=matchmaking_taxonomy_interests.profile_id and profile.user_id=auth.uid()) or public.is_admin())
with check (exists(select 1 from public.matchmaking_profiles profile
  where profile.id=matchmaking_taxonomy_interests.profile_id and profile.user_id=auth.uid()) or public.is_admin());

create policy "owners read relevant tender taxonomy mappings"
on public.tender_taxonomy_mappings for select to authenticated
using (public.is_admin() or exists(
  select 1 from public.opportunity_matches opportunity
  join public.companies company on company.id=opportunity.company_id
  where opportunity.tender_id=tender_taxonomy_mappings.tender_id and company.owner_id=auth.uid()
));
create policy "admins manage tender taxonomy mappings"
on public.tender_taxonomy_mappings for all to authenticated
using (public.is_admin()) with check (public.is_admin());

create policy "admins read taxonomy review queue"
on public.medical_product_taxonomy_review_queue for select to authenticated
using (public.is_admin());
create policy "admins manage taxonomy review queue"
on public.medical_product_taxonomy_review_queue for all to authenticated
using (public.is_admin()) with check (public.is_admin());

revoke all on table public.medical_product_taxonomy,
  public.medical_product_aliases, public.product_taxonomy_mappings,
  public.matchmaking_taxonomy_interests, public.tender_taxonomy_mappings,
  public.medical_product_taxonomy_review_queue from public, anon, authenticated;
grant select on table public.medical_product_taxonomy,
  public.medical_product_aliases, public.product_taxonomy_mappings to anon, authenticated;
grant insert,update,delete on table public.medical_product_taxonomy,
  public.medical_product_aliases, public.product_taxonomy_mappings to authenticated;
grant select,insert,update,delete on table public.matchmaking_taxonomy_interests,
  public.tender_taxonomy_mappings, public.medical_product_taxonomy_review_queue
  to authenticated;
grant all on table public.medical_product_taxonomy,
  public.medical_product_aliases, public.product_taxonomy_mappings,
  public.matchmaking_taxonomy_interests, public.tender_taxonomy_mappings,
  public.medical_product_taxonomy_review_queue to service_role;
grant usage,select on sequence public.medical_product_taxonomy_id_seq,
  public.medical_product_aliases_id_seq,
  public.product_taxonomy_mappings_id_seq,
  public.tender_taxonomy_mappings_id_seq,
  public.medical_product_taxonomy_review_queue_id_seq to service_role;

revoke all on function public.normalize_medical_product_term(text),
  public.medical_product_term_similarity(text,text),
  public.medical_taxonomy_pair_score_v1(bigint,bigint)
  from public, anon;
grant execute on function public.normalize_medical_product_term(text),
  public.medical_product_term_similarity(text,text),
  public.medical_taxonomy_pair_score_v1(bigint,bigint)
  to authenticated, service_role;

-- Compatibility exposes private profile evidence and is an internal scoring
-- primitive. The owner-scoped refresh RPC calls it as the function owner.
revoke all on function public.mm_taxonomy_product_compatibility_v1(uuid,uuid)
  from public, anon, authenticated;
grant execute on function public.mm_taxonomy_product_compatibility_v1(uuid,uuid)
  to service_role;

revoke all on function public.search_medical_product_taxonomy_v1(text,integer),
  public.resolve_medical_product_term_v1(text,integer) from public;
grant execute on function public.search_medical_product_taxonomy_v1(text,integer),
  public.resolve_medical_product_term_v1(text,integer) to anon, authenticated, service_role;

revoke all on function public.save_matchmaking_taxonomy_interests_v1(uuid,jsonb),
  public.get_matchmaking_taxonomy_interests_v1(uuid),
  public.set_product_taxonomy_mapping_v1(bigint,bigint,text),
  public.clear_product_taxonomy_mapping_v1(bigint),
  public.queue_product_taxonomy_review_v1(bigint,text),
  public.refresh_matchmaking_matches(uuid),
  public.get_tender_taxonomy_compatibility_v1(bigint,bigint)
  from public, anon;
grant execute on function public.save_matchmaking_taxonomy_interests_v1(uuid,jsonb),
  public.get_matchmaking_taxonomy_interests_v1(uuid),
  public.set_product_taxonomy_mapping_v1(bigint,bigint,text),
  public.clear_product_taxonomy_mapping_v1(bigint),
  public.queue_product_taxonomy_review_v1(bigint,text),
  public.refresh_matchmaking_matches(uuid),
  public.get_tender_taxonomy_compatibility_v1(bigint,bigint)
  to authenticated, service_role;

revoke all on function public.refresh_tender_taxonomy_mappings_v1(bigint)
  from public, anon;
grant execute on function public.refresh_tender_taxonomy_mappings_v1(bigint)
  to authenticated, service_role;

revoke all on function public.get_admin_medical_taxonomy_v1(text,integer),
  public.admin_upsert_medical_taxonomy_node_v1(bigint,bigint,text,text,text,text,boolean,integer),
  public.admin_upsert_medical_product_alias_v1(bigint,bigint,text,text,numeric,boolean),
  public.admin_review_medical_product_term_v1(bigint,text,bigint,boolean)
  from public, anon;
grant execute on function public.get_admin_medical_taxonomy_v1(text,integer),
  public.admin_upsert_medical_taxonomy_node_v1(bigint,bigint,text,text,text,text,boolean,integer),
  public.admin_upsert_medical_product_alias_v1(bigint,bigint,text,text,numeric,boolean),
  public.admin_review_medical_product_term_v1(bigint,text,bigint,boolean)
  to authenticated, service_role;

comment on table public.medical_product_taxonomy is
  'Canonical, versioned three-level medical-product hierarchy. Only existing admins may mutate it.';
comment on table public.medical_product_aliases is
  'Verified reusable medical/commercial synonyms; unknown terms require admin review.';
comment on table public.product_taxonomy_mappings is
  'Additive mapping that preserves every commercial product name and legacy category.';
comment on table public.matchmaking_taxonomy_interests is
  'Tenant-scoped structured product interests plus auditable custom-term fallback.';
comment on table public.tender_taxonomy_mappings is
  'Deterministic tender and lot term mappings; insufficient evidence remains unmapped.';

commit;
