-- MedicHall core platform baseline.
--
-- The original marketplace, company, buyer, RFQ, media, and notification
-- schema was installed through dashboard-only setup scripts before the
-- ordered migration history began.  Every later migration assumes these
-- objects already exist.  This seed-free migration makes that prerequisite
-- explicit without copying production rows or changing historical migrations.

begin;

create extension if not exists pgcrypto;
create extension if not exists pg_trgm with schema extensions;
create extension if not exists pg_net with schema extensions;
create extension if not exists pg_cron with schema pg_catalog;
create extension if not exists "uuid-ossp" with schema extensions;
create extension if not exists supabase_vault with schema vault;

-- ---------------------------------------------------------------------------
-- Core marketplace and identity-owned business records
-- ---------------------------------------------------------------------------

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  ref text unique not null,
  name text not null,
  category text not null,
  description text,
  image_url text,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.partners (
  id bigint generated by default as identity primary key,
  name text not null,
  type text,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.rfq_requests (
  id bigint generated by default as identity primary key,
  product_ref text,
  product_name text,
  email text not null,
  company text,
  message text,
  created_at timestamptz not null default now()
);

create table if not exists public.admins (
  user_id uuid primary key references auth.users(id) on delete cascade
);

create table if not exists public.companies (
  id bigint generated by default as identity primary key,
  owner_id uuid references auth.users(id) on delete set null,
  name text not null,
  type text,
  description text,
  website text,
  contact_email text,
  phone text,
  country text default 'Türkiye',
  city text,
  certifications text,
  logo_url text,
  is_approved boolean not null default false,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  catalog_url text,
  video_url text,
  plan text not null default 'free',
  plan_expires_at timestamptz,
  slug text,
  is_verified boolean not null default false
);

alter table public.products
  add column if not exists company_id bigint
    references public.companies(id) on delete set null,
  add column if not exists brochure_url text,
  add column if not exists is_featured boolean not null default false;

alter table public.rfq_requests
  add column if not exists company_id bigint
    references public.companies(id) on delete set null,
  add column if not exists user_id uuid
    references auth.users(id) on delete set null,
  add column if not exists quantity text,
  add column if not exists incoterm text,
  add column if not exists destination text,
  add column if not exists target_price text,
  add column if not exists req_certs text,
  add column if not exists group_id uuid;

create table if not exists public.buyer_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  company_name text,
  country text,
  created_at timestamptz not null default now()
);

create table if not exists public.favorites (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (user_id, product_id)
);

create table if not exists public.company_catalogs (
  id bigint generated by default as identity primary key,
  company_id bigint not null
    references public.companies(id) on delete cascade,
  title text not null default 'Product Catalog',
  file_url text not null,
  thumb_url text,
  created_at timestamptz not null default now()
);

-- This production object had no surviving setup or migration source.
create table if not exists public.company_certificates (
  id bigint generated by default as identity primary key,
  company_id bigint not null
    references public.companies(id) on delete cascade,
  title text not null default 'Certificate',
  file_url text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.rfq_offers (
  id bigint generated by default as identity primary key,
  rfq_id bigint not null
    references public.rfq_requests(id) on delete cascade,
  company_id bigint not null
    references public.companies(id) on delete cascade,
  unit_price numeric,
  currency text not null default 'USD',
  moq text,
  lead_time text,
  valid_until date,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (rfq_id, company_id)
);

create table if not exists public.rfq_messages (
  id bigint generated by default as identity primary key,
  rfq_id bigint not null
    references public.rfq_requests(id) on delete cascade,
  sender_id uuid not null references auth.users(id) on delete cascade,
  sender_role text not null default 'buyer',
  body text not null,
  created_at timestamptz not null default now(),
  is_read boolean not null default false
);

create table if not exists public.banners (
  id bigint generated by default as identity primary key,
  title text not null,
  image_url text not null,
  link_url text,
  placement text not null default 'home',
  is_active boolean not null default true,
  ends_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.ai_usage_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  mode text not null default 'general',
  prompt_preview text,
  input_tokens integer default 0,
  output_tokens integer default 0,
  created_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- Foundational helpers and legacy notification compatibility
-- ---------------------------------------------------------------------------

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $function$
  select exists (
    select 1
    from public.admins
    where user_id = auth.uid()
  );
$function$;

create or replace function public.company_is_public(p_company_id bigint)
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $function$
  select exists (
    select 1
    from public.companies company
    where company.id = p_company_id
      and company.is_approved
      and company.is_active
  );
$function$;

create or replace function public.set_company_slug()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $function$
begin
  if new.slug is null or btrim(new.slug) = '' then
    new.slug := regexp_replace(
      regexp_replace(
        translate(lower(new.name), 'çğıöşüâîû', 'cgiosuaiu'),
        '[^a-z0-9]+',
        '-',
        'g'
      ),
      '(^-+|-+$)',
      '',
      'g'
    );
    if new.slug is null or new.slug = '' then
      new.slug := 'company';
    end if;
    while exists (
      select 1
      from public.companies company
      where company.slug = new.slug
        and company.id is distinct from new.id
    )
    loop
      new.slug := new.slug || '-' || (floor(random() * 9000) + 1000)::integer;
    end loop;
  end if;
  return new;
end;
$function$;

drop trigger if exists company_slug on public.companies;
create trigger company_slug
before insert or update on public.companies
for each row execute function public.set_company_slug();

create unique index if not exists companies_slug_idx
on public.companies(slug);

create or replace function public.mh_email_from()
returns text
language sql
immutable
set search_path = public, pg_temp
as $function$
  select 'MedicHall <notifications@medichall.com>';
$function$;

create or replace function public.mh_site_url()
returns text
language sql
immutable
set search_path = public, pg_temp
as $function$
  select 'https://medichall.com';
$function$;

create or replace function public.mh_admin_email()
returns text
language sql
immutable
set search_path = public, pg_temp
as $function$
  select 'info@medichall.co';
$function$;

-- The historical dashboard script embedded a provider credential in the
-- function body.  The reconstructed contract reads a staging/production
-- operator-supplied Vault entry and becomes a safe no-op when it is absent.
create or replace function public.notify_email(
  p_to text,
  p_subject text,
  p_html text
)
returns void
language plpgsql
security definer
set search_path = public, extensions, vault, pg_temp
as $function$
declare
  resend_api_key text;
begin
  if nullif(btrim(p_to), '') is null then
    return;
  end if;

  begin
    select decrypted_secret
    into resend_api_key
    from vault.decrypted_secrets
    where name = 'medichall_resend_api_key'
    limit 1;
  exception
    when undefined_table then
      return;
  end;

  if nullif(resend_api_key, '') is null then
    return;
  end if;

  perform net.http_post(
    url := 'https://api.resend.com/emails',
    headers := jsonb_build_object(
      'Authorization', 'Bearer ' || resend_api_key,
      'Content-Type', 'application/json'
    ),
    body := jsonb_build_object(
      'from', public.mh_email_from(),
      'to', jsonb_build_array(p_to),
      'subject', p_subject,
      'html', p_html
    )
  );
exception
  when undefined_function then
    return;
end;
$function$;

create or replace function public.trg_rfq_created()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $function$
declare
  recipient_email text;
  sender_line text;
begin
  if new.company_id is not null then
    select coalesce(nullif(company.contact_email, ''), owner.email)
    into recipient_email
    from public.companies company
    left join auth.users owner on owner.id = company.owner_id
    where company.id = new.company_id;
  else
    recipient_email := public.mh_admin_email();
  end if;

  if new.user_id is not null then
    sender_line := '<b>Registered buyer</b>'
      || coalesce(' · ' || new.company, '')
      || ' — reply via the chat in your MedicHall portal.';
  else
    sender_line := new.email || coalesce(' · ' || new.company, '');
  end if;

  perform public.notify_email(
    recipient_email,
    'New quotation request — ' ||
      coalesce(new.product_name, 'general inquiry'),
    '<div style="font-family:sans-serif;line-height:1.6">'
      || '<h2 style="color:#003E52">New quotation request</h2>'
      || '<p><b>Product:</b> '
      || coalesce(new.product_name, 'General inquiry') || '</p>'
      || '<p><b>From:</b> ' || sender_line || '</p>'
      || coalesce(
        '<p style="background:#EFF6F9;padding:12px;border-radius:8px">'
        || new.message || '</p>',
        ''
      )
      || '<p><a href="' || public.mh_site_url() || '/portal.html">'
      || 'Open MedicHall Portal</a></p></div>'
  );
  return new;
end;
$function$;

create or replace function public.trg_message_created()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $function$
declare
  request_record public.rfq_requests%rowtype;
  recipient_email text;
begin
  if exists (
    select 1
    from public.rfq_messages message
    where message.rfq_id = new.rfq_id
      and message.sender_id = new.sender_id
      and message.id <> new.id
      and message.created_at > now() - interval '15 minutes'
  ) then
    return new;
  end if;

  select *
  into request_record
  from public.rfq_requests
  where id = new.rfq_id;

  if new.sender_role = 'buyer' then
    select coalesce(nullif(company.contact_email, ''), owner.email)
    into recipient_email
    from public.companies company
    left join auth.users owner on owner.id = company.owner_id
    where company.id = request_record.company_id;
  else
    select email
    into recipient_email
    from auth.users
    where id = request_record.user_id;
    recipient_email := coalesce(recipient_email, request_record.email);
  end if;

  perform public.notify_email(
    recipient_email,
    'New message on MedicHall — ' ||
      coalesce(request_record.product_name, 'your inquiry'),
    '<div style="font-family:sans-serif;line-height:1.6">'
      || '<h2 style="color:#003E52">You have a new message</h2>'
      || '<p>' || new.body || '</p>'
      || '<p><a href="' || public.mh_site_url() || '/portal.html">'
      || 'Reply on MedicHall</a></p></div>'
  );
  return new;
end;
$function$;

create or replace function public.trg_offer_touch()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $function$
begin
  new.updated_at := now();
  return new;
end;
$function$;

create or replace function public.trg_offer_created()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $function$
declare
  recipient_email text;
  product_name text;
  company_name text;
begin
  select owner.email, request.product_name
  into recipient_email, product_name
  from public.rfq_requests request
  left join auth.users owner on owner.id = request.user_id
  where request.id = new.rfq_id;

  if recipient_email is null then
    return new;
  end if;

  select name
  into company_name
  from public.companies
  where id = new.company_id;

  perform public.notify_email(
    recipient_email,
    'You received an offer — ' || coalesce(product_name, 'your inquiry'),
    '<div style="font-family:sans-serif;line-height:1.6">'
      || '<h2 style="color:#003E52">New offer received</h2>'
      || '<p><b>' || coalesce(company_name, 'A manufacturer')
      || '</b> sent an offer.</p>'
      || '<p><a href="' || public.mh_site_url() || '/portal.html#inbox">'
      || 'Compare offers on MedicHall</a></p></div>'
  );
  return new;
end;
$function$;

drop trigger if exists rfq_created_email on public.rfq_requests;
create trigger rfq_created_email
after insert on public.rfq_requests
for each row execute function public.trg_rfq_created();

drop trigger if exists message_created_email on public.rfq_messages;
create trigger message_created_email
after insert on public.rfq_messages
for each row execute function public.trg_message_created();

drop trigger if exists offer_touch on public.rfq_offers;
create trigger offer_touch
before update on public.rfq_offers
for each row execute function public.trg_offer_touch();

drop trigger if exists offer_created_email on public.rfq_offers;
create trigger offer_created_email
after insert on public.rfq_offers
for each row execute function public.trg_offer_created();

-- ---------------------------------------------------------------------------
-- RLS and role privileges
-- ---------------------------------------------------------------------------

alter table public.products enable row level security;
alter table public.partners enable row level security;
alter table public.rfq_requests enable row level security;
alter table public.admins enable row level security;
alter table public.companies enable row level security;
alter table public.buyer_profiles enable row level security;
alter table public.favorites enable row level security;
alter table public.company_catalogs enable row level security;
alter table public.company_certificates enable row level security;
alter table public.rfq_offers enable row level security;
alter table public.rfq_messages enable row level security;
alter table public.banners enable row level security;
alter table public.ai_usage_logs enable row level security;

drop policy if exists "public read products" on public.products;
create policy "public read products"
on public.products for select
using (
  is_active
  and (
    company_id is null
    or public.company_is_public(company_id)
  )
);

drop policy if exists "admin all products" on public.products;
create policy "admin all products"
on public.products for all to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "owner manage own products" on public.products;
create policy "owner manage own products"
on public.products for all to authenticated
using (
  company_id in (
    select id from public.companies where owner_id = auth.uid()
  )
)
with check (
  company_id in (
    select id from public.companies where owner_id = auth.uid()
  )
);

drop policy if exists "public read partners" on public.partners;
create policy "public read partners"
on public.partners for select
using (is_active);

drop policy if exists "admin all partners" on public.partners;
create policy "admin all partners"
on public.partners for all to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "public insert rfq" on public.rfq_requests;
create policy "public insert rfq"
on public.rfq_requests for insert
with check (true);

drop policy if exists "admin read rfq" on public.rfq_requests;
create policy "admin read rfq"
on public.rfq_requests for select to authenticated
using (public.is_admin());

drop policy if exists "admin delete rfq" on public.rfq_requests;
create policy "admin delete rfq"
on public.rfq_requests for delete to authenticated
using (public.is_admin());

drop policy if exists "owner read own rfq" on public.rfq_requests;
create policy "owner read own rfq"
on public.rfq_requests for select to authenticated
using (
  company_id in (
    select id from public.companies where owner_id = auth.uid()
  )
);

drop policy if exists "buyer read own rfq" on public.rfq_requests;
create policy "buyer read own rfq"
on public.rfq_requests for select to authenticated
using (user_id = auth.uid());

drop policy if exists "public read companies" on public.companies;
create policy "public read companies"
on public.companies for select
using (is_approved and is_active);

drop policy if exists "owner read own company" on public.companies;
create policy "owner read own company"
on public.companies for select to authenticated
using (owner_id = auth.uid());

drop policy if exists "owner insert own company" on public.companies;
create policy "owner insert own company"
on public.companies for insert to authenticated
with check (owner_id = auth.uid());

drop policy if exists "owner update own company" on public.companies;
create policy "owner update own company"
on public.companies for update to authenticated
using (owner_id = auth.uid())
with check (owner_id = auth.uid());

drop policy if exists "admin all companies" on public.companies;
create policy "admin all companies"
on public.companies for all to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "buyer manage own profile" on public.buyer_profiles;
create policy "buyer manage own profile"
on public.buyer_profiles for all to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

drop policy if exists "admin read buyer profiles" on public.buyer_profiles;
create policy "admin read buyer profiles"
on public.buyer_profiles for select to authenticated
using (public.is_admin());

drop policy if exists "user manages own favorites" on public.favorites;
create policy "user manages own favorites"
on public.favorites for all to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

drop policy if exists "public read catalogs" on public.company_catalogs;
create policy "public read catalogs"
on public.company_catalogs for select
using (
  exists (
    select 1
    from public.companies company
    where company.id = company_id
      and company.is_approved
      and company.is_active
  )
);

drop policy if exists "owner manage catalogs" on public.company_catalogs;
create policy "owner manage catalogs"
on public.company_catalogs for all to authenticated
using (
  company_id in (
    select id from public.companies where owner_id = auth.uid()
  )
)
with check (
  company_id in (
    select id from public.companies where owner_id = auth.uid()
  )
);

drop policy if exists "admin all catalogs" on public.company_catalogs;
create policy "admin all catalogs"
on public.company_catalogs for all to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "public read certificates"
  on public.company_certificates;
create policy "public read certificates"
on public.company_certificates for select
using (
  exists (
    select 1
    from public.companies company
    where company.id = company_id
      and company.is_approved
      and company.is_active
  )
);

drop policy if exists "owner manage certificates"
  on public.company_certificates;
create policy "owner manage certificates"
on public.company_certificates for all to authenticated
using (
  company_id in (
    select id from public.companies where owner_id = auth.uid()
  )
)
with check (
  company_id in (
    select id from public.companies where owner_id = auth.uid()
  )
);

drop policy if exists "admin all certificates"
  on public.company_certificates;
create policy "admin all certificates"
on public.company_certificates for all to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "buyer read offers" on public.rfq_offers;
create policy "buyer read offers"
on public.rfq_offers for select to authenticated
using (
  exists (
    select 1
    from public.rfq_requests request
    where request.id = rfq_id
      and request.user_id = auth.uid()
  )
);

drop policy if exists "manufacturer manage own offers" on public.rfq_offers;
create policy "manufacturer manage own offers"
on public.rfq_offers for all to authenticated
using (
  company_id in (
    select id from public.companies where owner_id = auth.uid()
  )
)
with check (
  company_id in (
    select id from public.companies where owner_id = auth.uid()
  )
  and exists (
    select 1
    from public.rfq_requests request
    where request.id = rfq_id
      and request.company_id = rfq_offers.company_id
  )
);

drop policy if exists "admin all offers" on public.rfq_offers;
create policy "admin all offers"
on public.rfq_offers for all to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "participants read messages" on public.rfq_messages;
create policy "participants read messages"
on public.rfq_messages for select to authenticated
using (
  exists (
    select 1
    from public.rfq_requests request
    where request.id = rfq_id
      and (
        request.user_id = auth.uid()
        or request.company_id in (
          select id from public.companies where owner_id = auth.uid()
        )
        or public.is_admin()
      )
  )
);

drop policy if exists "participants send messages" on public.rfq_messages;
create policy "participants send messages"
on public.rfq_messages for insert to authenticated
with check (
  sender_id = auth.uid()
  and exists (
    select 1
    from public.rfq_requests request
    where request.id = rfq_id
      and (
        request.user_id = auth.uid()
        or request.company_id in (
          select id from public.companies where owner_id = auth.uid()
        )
        or public.is_admin()
      )
  )
);

drop policy if exists "participants update messages" on public.rfq_messages;
create policy "participants update messages"
on public.rfq_messages for update to authenticated
using (
  exists (
    select 1
    from public.rfq_requests request
    where request.id = rfq_id
      and (
        request.user_id = auth.uid()
        or request.company_id in (
          select id from public.companies where owner_id = auth.uid()
        )
        or public.is_admin()
      )
  )
)
with check (true);

drop policy if exists "public read banners" on public.banners;
create policy "public read banners"
on public.banners for select
using (is_active);

drop policy if exists "admin all banners" on public.banners;
create policy "admin all banners"
on public.banners for all to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "users can view own ai logs"
  on public.ai_usage_logs;
create policy "users can view own ai logs"
on public.ai_usage_logs for select to authenticated
using (auth.uid() = user_id);

grant all privileges on table
  public.products,
  public.partners,
  public.rfq_requests,
  public.admins,
  public.companies,
  public.buyer_profiles,
  public.favorites,
  public.company_catalogs,
  public.company_certificates,
  public.rfq_offers,
  public.rfq_messages,
  public.banners,
  public.ai_usage_logs
to anon, authenticated, service_role;

grant usage on all sequences in schema public
to anon, authenticated, service_role;

revoke select on table public.companies from anon;
grant select (
  id,
  name,
  type,
  description,
  website,
  phone,
  country,
  city,
  certifications,
  logo_url,
  is_approved,
  is_active,
  created_at,
  catalog_url,
  video_url,
  plan,
  plan_expires_at,
  slug,
  is_verified
) on table public.companies to anon;

revoke all on function public.notify_email(text, text, text)
from public, anon, authenticated;
grant execute on function public.notify_email(text, text, text)
to service_role;

revoke all on function public.trg_rfq_created()
from public, anon, authenticated;
revoke all on function public.trg_message_created()
from public, anon, authenticated;
revoke all on function public.trg_offer_created()
from public, anon, authenticated;
revoke all on function public.trg_offer_touch()
from public, anon, authenticated;
revoke all on function public.set_company_slug()
from public, anon, authenticated;

grant execute on function public.is_admin()
to anon, authenticated, service_role;
grant execute on function public.company_is_public(bigint)
to anon, authenticated, service_role;

-- ---------------------------------------------------------------------------
-- Public media Storage compatibility
-- ---------------------------------------------------------------------------

insert into storage.buckets(id, name, public)
values ('media', 'media', true)
on conflict (id) do update
set name = excluded.name,
    public = excluded.public;

drop policy if exists "authenticated upload media" on storage.objects;
create policy "authenticated upload media"
on storage.objects for insert to authenticated
with check (bucket_id = 'media');

drop policy if exists "authenticated update media" on storage.objects;
create policy "authenticated update media"
on storage.objects for update to authenticated
using (bucket_id = 'media')
with check (bucket_id = 'media');

drop policy if exists "authenticated delete media" on storage.objects;
create policy "authenticated delete media"
on storage.objects for delete to authenticated
using (bucket_id = 'media');

drop policy if exists "public read media" on storage.objects;
create policy "public read media"
on storage.objects for select
using (bucket_id = 'media');

notify pgrst, 'reload schema';

commit;
