-- TED canonical lot authority and deterministic document reconciliation.
-- Official TED structured identifiers are the only authoritative lot identity.

begin;

alter table public.tenders
  add column if not exists canonical_lots jsonb not null default '[]'::jsonb,
  add column if not exists canonical_lot_count integer not null default 0,
  add column if not exists lot_structure_status text not null
    default 'LOT_STRUCTURE_PENDING',
  add column if not exists lot_structure_source text,
  add column if not exists lot_structure_snapshot_hash text,
  add column if not exists lot_structure_diagnostics jsonb
    not null default '{}'::jsonb,
  add column if not exists lot_structure_updated_at timestamptz;

alter table public.tenders
  drop constraint if exists tenders_canonical_lots_array_check;
alter table public.tenders
  add constraint tenders_canonical_lots_array_check
  check (
    jsonb_typeof(canonical_lots) = 'array'
    and canonical_lot_count >= 0
    and canonical_lot_count <= 1000
    and canonical_lot_count = jsonb_array_length(canonical_lots)
  );

alter table public.tenders
  drop constraint if exists tenders_lot_structure_status_check;
alter table public.tenders
  add constraint tenders_lot_structure_status_check
  check (
    lot_structure_status in (
      'LOT_STRUCTURE_PENDING',
      'CANONICAL_LOTS_READY',
      'NOT_APPLICABLE'
    )
  );

alter table public.tenders
  drop constraint if exists tenders_lot_structure_snapshot_hash_check;
alter table public.tenders
  add constraint tenders_lot_structure_snapshot_hash_check
  check (
    lot_structure_snapshot_hash is null
    or lot_structure_snapshot_hash ~ '^[a-f0-9]{64}$'
  );

create table if not exists public.tender_canonical_lots (
  id bigint generated by default as identity primary key,
  tender_id bigint not null references public.tenders(id) on delete cascade,
  position integer not null check (position between 1 and 1000),
  publication_number text not null check (
    publication_number ~ '^\d{1,10}-\d{4}$'
  ),
  official_lot_identifier text not null check (
    length(official_lot_identifier) between 1 and 120
  ),
  internal_lot_identifier text,
  official_title text not null,
  official_description text,
  cpv_codes text[] not null default '{}',
  deadline_at date,
  estimated_value numeric,
  currency text check (currency is null or currency ~ '^[A-Z]{3}$'),
  status text not null default 'active' check (
    status in ('active', 'removed', 'cancelled')
  ),
  source_type text not null default 'TED_STRUCTURED' check (
    source_type = 'TED_STRUCTURED'
  ),
  source_url text not null check (source_url ~ '^https://ted\.europa\.eu/'),
  source_payload jsonb not null default '{}'::jsonb,
  source_snapshot_hash text not null check (
    source_snapshot_hash ~ '^[a-f0-9]{64}$'
  ),
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  removed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (tender_id, official_lot_identifier)
);

create index if not exists tender_canonical_lots_tender_position_idx
  on public.tender_canonical_lots(tender_id, status, position);
create index if not exists tender_canonical_lots_publication_idx
  on public.tender_canonical_lots(publication_number, official_lot_identifier);

drop trigger if exists tender_canonical_lots_set_updated_at
  on public.tender_canonical_lots;
create trigger tender_canonical_lots_set_updated_at
before update on public.tender_canonical_lots
for each row execute function public.set_updated_at();

create table if not exists public.tender_canonical_lot_revisions (
  id bigint generated by default as identity primary key,
  canonical_lot_id bigint not null
    references public.tender_canonical_lots(id) on delete cascade,
  tender_id bigint not null references public.tenders(id) on delete cascade,
  official_lot_identifier text not null,
  source_snapshot_hash text not null check (
    source_snapshot_hash ~ '^[a-f0-9]{64}$'
  ),
  lot_snapshot jsonb not null,
  observed_at timestamptz not null default now(),
  unique (canonical_lot_id, source_snapshot_hash)
);

create index if not exists tender_canonical_lot_revisions_tender_idx
  on public.tender_canonical_lot_revisions(tender_id, observed_at desc);

create table if not exists public.tender_document_chunk_lot_mappings (
  id bigint generated by default as identity primary key,
  chunk_id bigint not null
    references public.tender_document_analysis_chunks(id) on delete cascade,
  job_id bigint not null
    references public.tender_document_analysis_jobs(id) on delete cascade,
  tender_id bigint not null references public.tenders(id) on delete cascade,
  mapping_category text not null check (
    mapping_category in (
      'ONE_CANONICAL_LOT',
      'MULTIPLE_CANONICAL_LOTS',
      'NOTICE_LEVEL',
      'UNMAPPED'
    )
  ),
  canonical_lot_identifiers text[] not null default '{}',
  rejected_references text[] not null default '{}',
  mapping_methods text[] not null default '{}',
  mapping_version text not null default 'ted-canonical-lot-map-v1',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (chunk_id, mapping_version),
  check (
    (mapping_category = 'ONE_CANONICAL_LOT'
      and cardinality(canonical_lot_identifiers) = 1)
    or (mapping_category = 'MULTIPLE_CANONICAL_LOTS'
      and cardinality(canonical_lot_identifiers) > 1)
    or (mapping_category in ('NOTICE_LEVEL', 'UNMAPPED')
      and cardinality(canonical_lot_identifiers) = 0)
  )
);

create index if not exists tender_chunk_lot_mappings_tender_idx
  on public.tender_document_chunk_lot_mappings(tender_id, mapping_category);

drop trigger if exists tender_chunk_lot_mappings_set_updated_at
  on public.tender_document_chunk_lot_mappings;
create trigger tender_chunk_lot_mappings_set_updated_at
before update on public.tender_document_chunk_lot_mappings
for each row execute function public.set_updated_at();

alter table public.tender_document_evidence
  add column if not exists lot_scope text not null default 'NOTICE_LEVEL',
  add column if not exists canonical_lot_identifiers text[]
    not null default '{}',
  add column if not exists lot_mapping_method text;

alter table public.tender_document_evidence
  drop constraint if exists tender_document_evidence_lot_scope_check;
alter table public.tender_document_evidence
  add constraint tender_document_evidence_lot_scope_check
  check (
    lot_scope in ('NOTICE_LEVEL', 'LOT_LEVEL', 'MULTI_LOT', 'UNMAPPED')
  );

alter table public.tender_canonical_lots enable row level security;
alter table public.tender_canonical_lot_revisions enable row level security;
alter table public.tender_document_chunk_lot_mappings enable row level security;

revoke all on table
  public.tender_canonical_lots,
  public.tender_canonical_lot_revisions,
  public.tender_document_chunk_lot_mappings
from public, anon, authenticated;

grant all on table
  public.tender_canonical_lots,
  public.tender_canonical_lot_revisions,
  public.tender_document_chunk_lot_mappings
to service_role;

grant usage, select on sequence
  public.tender_canonical_lots_id_seq,
  public.tender_canonical_lot_revisions_id_seq,
  public.tender_document_chunk_lot_mappings_id_seq
to service_role;

create or replace function public.replace_ted_canonical_lots_v1(
  p_tender_id bigint,
  p_publication_number text,
  p_source_url text,
  p_source_snapshot_hash text,
  p_lots jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $function$
declare
  v_tender public.tenders%rowtype;
  v_before integer := 0;
  v_after integer := 0;
  v_removed integer := 0;
  v_changed integer := 0;
  v_now timestamptz := now();
  v_canonical_lots jsonb := '[]'::jsonb;
begin
  if p_tender_id is null
     or p_publication_number !~ '^\d{1,10}-\d{4}$'
     or p_source_url !~ '^https://ted\.europa\.eu/'
     or p_source_snapshot_hash !~ '^[a-f0-9]{64}$'
     or jsonb_typeof(p_lots) <> 'array'
     or jsonb_array_length(p_lots) < 1
     or jsonb_array_length(p_lots) > 1000 then
    raise exception 'Invalid TED canonical lot payload' using errcode = '22023';
  end if;

  select * into v_tender
  from public.tenders
  where id = p_tender_id
  for update;
  if not found then
    raise exception 'Tender not found' using errcode = 'P0002';
  end if;
  if upper(coalesce(v_tender.source, '')) <> 'TED'
     or v_tender.source_notice_id is distinct from p_publication_number then
    raise exception 'Tender is not the requested TED publication'
      using errcode = '22023';
  end if;

  if exists (
    select 1
    from jsonb_array_elements(p_lots) item
    where coalesce(item ->> 'official_lot_identifier', '') = ''
       or coalesce(item ->> 'publication_number', '') <> p_publication_number
       or coalesce(item ->> 'source_type', '') <> 'TED_STRUCTURED'
  ) then
    raise exception 'TED canonical lot payload contains an invalid identity'
      using errcode = '22023';
  end if;
  if exists (
    select 1
    from jsonb_array_elements(p_lots) item
    group by upper(item ->> 'official_lot_identifier')
    having count(*) > 1
  ) then
    raise exception 'TED canonical lot payload contains duplicate identities'
      using errcode = '23505';
  end if;

  select count(*) into v_before
  from public.tender_canonical_lots
  where tender_id = p_tender_id and status = 'active';

  update public.tender_canonical_lots existing
  set status = 'removed',
      removed_at = v_now,
      last_seen_at = v_now,
      updated_at = v_now
  where existing.tender_id = p_tender_id
    and existing.status = 'active'
    and not exists (
      select 1
      from jsonb_array_elements(p_lots) item
      where upper(item ->> 'official_lot_identifier') =
        upper(existing.official_lot_identifier)
    );
  get diagnostics v_removed = row_count;

  insert into public.tender_canonical_lots (
    tender_id,
    position,
    publication_number,
    official_lot_identifier,
    internal_lot_identifier,
    official_title,
    official_description,
    cpv_codes,
    deadline_at,
    estimated_value,
    currency,
    status,
    source_type,
    source_url,
    source_payload,
    source_snapshot_hash,
    first_seen_at,
    last_seen_at,
    removed_at,
    updated_at
  )
  select
    p_tender_id,
    coalesce(nullif(item.value ->> 'position', '')::integer, item.ordinality::integer),
    p_publication_number,
    upper(item.value ->> 'official_lot_identifier'),
    nullif(item.value ->> 'internal_lot_identifier', ''),
    coalesce(nullif(item.value ->> 'lot_title', ''), 'Untitled lot'),
    nullif(item.value ->> 'description', ''),
    coalesce(array(
      select distinct code
      from jsonb_array_elements_text(
        coalesce(item.value -> 'cpv_codes', '[]'::jsonb)
      ) code
      where code ~ '^\d{8}$'
      order by code
    ), '{}'),
    nullif(item.value ->> 'deadline_at', '')::date,
    nullif(item.value ->> 'estimated_value', '')::numeric,
    case
      when item.value ->> 'currency' ~ '^[A-Z]{3}$'
      then item.value ->> 'currency'
      else null
    end,
    'active',
    'TED_STRUCTURED',
    p_source_url,
    coalesce(item.value -> 'source_payload', '{}'::jsonb),
    p_source_snapshot_hash,
    v_now,
    v_now,
    null,
    v_now
  from jsonb_array_elements(p_lots) with ordinality item(value, ordinality)
  on conflict (tender_id, official_lot_identifier) do update
  set position = excluded.position,
      publication_number = excluded.publication_number,
      internal_lot_identifier = excluded.internal_lot_identifier,
      official_title = excluded.official_title,
      official_description = excluded.official_description,
      cpv_codes = excluded.cpv_codes,
      deadline_at = excluded.deadline_at,
      estimated_value = excluded.estimated_value,
      currency = excluded.currency,
      status = 'active',
      source_type = 'TED_STRUCTURED',
      source_url = excluded.source_url,
      source_payload = excluded.source_payload,
      source_snapshot_hash = excluded.source_snapshot_hash,
      last_seen_at = v_now,
      removed_at = null,
      updated_at = v_now
  where (
    public.tender_canonical_lots.position,
    public.tender_canonical_lots.internal_lot_identifier,
    public.tender_canonical_lots.official_title,
    public.tender_canonical_lots.official_description,
    public.tender_canonical_lots.cpv_codes,
    public.tender_canonical_lots.deadline_at,
    public.tender_canonical_lots.estimated_value,
    public.tender_canonical_lots.currency,
    public.tender_canonical_lots.status,
    public.tender_canonical_lots.source_snapshot_hash
  ) is distinct from (
    excluded.position,
    excluded.internal_lot_identifier,
    excluded.official_title,
    excluded.official_description,
    excluded.cpv_codes,
    excluded.deadline_at,
    excluded.estimated_value,
    excluded.currency,
    excluded.status,
    excluded.source_snapshot_hash
  );
  get diagnostics v_changed = row_count;

  insert into public.tender_canonical_lot_revisions (
    canonical_lot_id,
    tender_id,
    official_lot_identifier,
    source_snapshot_hash,
    lot_snapshot
  )
  select
    canonical.id,
    canonical.tender_id,
    canonical.official_lot_identifier,
    p_source_snapshot_hash,
    jsonb_build_object(
      'position', canonical.position,
      'official_lot_identifier', canonical.official_lot_identifier,
      'internal_lot_identifier', canonical.internal_lot_identifier,
      'official_title', canonical.official_title,
      'official_description', canonical.official_description,
      'cpv_codes', canonical.cpv_codes,
      'deadline_at', canonical.deadline_at,
      'estimated_value', canonical.estimated_value,
      'currency', canonical.currency,
      'status', canonical.status,
      'source_type', canonical.source_type,
      'source_url', canonical.source_url
    )
  from public.tender_canonical_lots canonical
  where canonical.tender_id = p_tender_id
    and canonical.source_snapshot_hash = p_source_snapshot_hash
  on conflict (canonical_lot_id, source_snapshot_hash) do nothing;

  select count(*), coalesce(jsonb_agg(
    jsonb_build_object(
      'position', canonical.position,
      'official_lot_identifier', canonical.official_lot_identifier,
      'internal_lot_identifier', canonical.internal_lot_identifier,
      'lot_number', canonical.official_lot_identifier,
      'lot_title', canonical.official_title,
      'description', canonical.official_description,
      'cpv_codes', canonical.cpv_codes,
      'deadline_at', canonical.deadline_at,
      'estimated_value', canonical.estimated_value,
      'currency', canonical.currency,
      'canonical_status', canonical.status,
      'source_type', canonical.source_type,
      'publication_number', canonical.publication_number,
      'source_url', canonical.source_url
    ) order by canonical.position
  ), '[]'::jsonb)
  into v_after, v_canonical_lots
  from public.tender_canonical_lots canonical
  where canonical.tender_id = p_tender_id
    and canonical.status = 'active';

  update public.tenders
  set canonical_lots = v_canonical_lots,
      canonical_lot_count = v_after,
      lot_structure_status = 'CANONICAL_LOTS_READY',
      lot_structure_source = 'TED_STRUCTURED',
      lot_structure_snapshot_hash = p_source_snapshot_hash,
      lot_structure_diagnostics = jsonb_build_object(
        'official_lot_count', v_after,
        'canonical_lot_count', v_after,
        'removed_or_deactivated_count', v_removed,
        'source_precedence', jsonb_build_array(
          'TED_STRUCTURED',
          'TED_DOCUMENTS',
          'DETERMINISTIC_EXTRACTION',
          'AI_ENRICHMENT'
        )
      ),
      lot_structure_updated_at = v_now,
      updated_at = v_now
  where id = p_tender_id;

  return jsonb_build_object(
    'tender_id', p_tender_id,
    'publication_number', p_publication_number,
    'official_lot_count', v_after,
    'canonical_lot_count', v_after,
    'before_count', v_before,
    'after_count', v_after,
    'changed_count', v_changed,
    'removed_or_deactivated_count', v_removed,
    'source_type', 'TED_STRUCTURED',
    'status', 'CANONICAL_LOTS_READY',
    'canonical_lots', v_canonical_lots
  );
end
$function$;

create or replace function public.get_tender_canonical_lots_v1(
  p_company_id bigint,
  p_tender_id bigint
)
returns jsonb
language plpgsql
stable
security definer
set search_path = public, pg_temp
as $function$
declare
  v_tender public.tenders%rowtype;
begin
  if not (
    public.is_admin()
    or coalesce(auth.jwt() ->> 'role', '') = 'service_role'
    or exists (
      select 1 from public.companies company
      where company.id = p_company_id and company.owner_id = auth.uid()
    )
  ) then
    raise exception 'Access denied' using errcode = '42501';
  end if;
  select * into v_tender from public.tenders where id = p_tender_id;
  if not found then
    raise exception 'Tender not found' using errcode = 'P0002';
  end if;
  return jsonb_build_object(
    'tender_id', p_tender_id,
    'publication_number', v_tender.source_notice_id,
    'status', v_tender.lot_structure_status,
    'source_type', v_tender.lot_structure_source,
    'official_lot_count', v_tender.canonical_lot_count,
    'canonical_lot_count', v_tender.canonical_lot_count,
    'lots', v_tender.canonical_lots,
    'diagnostics', v_tender.lot_structure_diagnostics,
    'updated_at', v_tender.lot_structure_updated_at
  );
end
$function$;

revoke all on function public.replace_ted_canonical_lots_v1(
  bigint, text, text, text, jsonb
) from public, anon, authenticated;
grant execute on function public.replace_ted_canonical_lots_v1(
  bigint, text, text, text, jsonb
) to service_role;

revoke all on function public.get_tender_canonical_lots_v1(bigint, bigint)
from public, anon, authenticated;
grant execute on function public.get_tender_canonical_lots_v1(bigint, bigint)
to authenticated, service_role;

comment on table public.tender_canonical_lots is
  'Authoritative TED structured lot identities. Document or AI extraction may enrich but never create these identities.';
comment on table public.tender_document_chunk_lot_mappings is
  'Deterministic chunk-to-canonical-lot reconciliation with explicit notice-level and unmapped states.';
comment on column public.tenders.canonical_lots is
  'Ordered public TED structured lot projection used by Tender Intelligence; independent of chunk-local AI lots.';

notify pgrst, 'reload schema';

commit;

-- Forward-only rollback plan: stop updated Edge Functions/frontends first,
-- then restore the previous RPC/function definitions. Preserve canonical rows
-- and revision history; do not drop them without explicit data-loss approval.
