-- MedicHall Matchmaking Workspace: video provider boundary and automation.

begin;

do $preflight$
begin
  if to_regprocedure('public.respond_matchmaking_meeting(bigint,text,integer,uuid,bigint,jsonb,text,text)')
     is null then
    raise exception
      'Matchmaking video preflight failed: apply 202607280003 first';
  end if;
end
$preflight$;

create table if not exists public.matchmaking_video_access_log (
  id bigint generated by default as identity primary key,
  meeting_id bigint not null
    references public.matchmaking_meeting_requests(id) on delete cascade,
  profile_id uuid not null
    references public.matchmaking_profiles(id) on delete cascade,
  action text not null check (action in ('prepare', 'join', 'revoke')),
  created_at timestamptz not null default now()
);

create index if not exists matchmaking_video_access_rate_idx
  on public.matchmaking_video_access_log(profile_id, meeting_id, action, created_at desc);

alter table public.matchmaking_video_access_log enable row level security;
revoke all on table public.matchmaking_video_access_log from anon, authenticated;

create or replace function public.mm_has_service_role()
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $function$
  select
    coalesce(auth.role(), '') = 'service_role'
    or session_user in ('postgres', 'supabase_admin');
$function$;

create or replace function public.claim_matchmaking_video_room(
  p_meeting_id bigint
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $function$
declare
  meeting_row public.matchmaking_meeting_requests;
  claim_granted boolean := false;
begin
  if not public.mm_has_service_role() then
    raise exception 'Service role required'
      using errcode = '42501';
  end if;

  select *
  into meeting_row
  from public.matchmaking_meeting_requests
  where id = p_meeting_id
  for update;

  if meeting_row.id is null then
    raise exception 'Meeting not found'
      using errcode = '22023';
  end if;
  if meeting_row.status not in ('accepted', 'confirmed') then
    raise exception 'Video can only be prepared for an accepted meeting'
      using errcode = '40001';
  end if;
  if meeting_row.confirmed_start is null
     or meeting_row.confirmed_end is null then
    raise exception 'The accepted proposal does not have a valid time'
      using errcode = '40001';
  end if;

  if meeting_row.video_status in ('ready', 'unconfigured') then
    return jsonb_build_object(
      'claim_granted', false,
      'meeting_id', meeting_row.id,
      'video_status', meeting_row.video_status,
      'room_name', meeting_row.video_room_name,
      'room_url', meeting_row.video_room_url,
      'start_at', meeting_row.confirmed_start,
      'end_at', meeting_row.confirmed_end,
      'room_expires_at', meeting_row.video_room_expires_at
    );
  end if;

  if meeting_row.video_status = 'creating'
     and meeting_row.video_claimed_at > now() - interval '5 minutes' then
    return jsonb_build_object(
      'claim_granted', false,
      'meeting_id', meeting_row.id,
      'video_status', 'creating',
      'room_name', meeting_row.video_room_name,
      'start_at', meeting_row.confirmed_start,
      'end_at', meeting_row.confirmed_end
    );
  end if;

  update public.matchmaking_meeting_requests
  set
    video_status = 'creating',
    video_room_name = coalesce(
      video_room_name,
      'mh-' || id || '-' ||
        left(replace(gen_random_uuid()::text, '-', ''), 16)
    ),
    video_claimed_at = now(),
    video_error_code = null,
    updated_at = now()
  where id = meeting_row.id
  returning * into meeting_row;

  claim_granted := true;
  return jsonb_build_object(
    'claim_granted', claim_granted,
    'meeting_id', meeting_row.id,
    'video_status', meeting_row.video_status,
    'room_name', meeting_row.video_room_name,
    'start_at', meeting_row.confirmed_start,
    'end_at', meeting_row.confirmed_end,
    'room_not_before', meeting_row.confirmed_start - interval '15 minutes',
    'room_expires_at', meeting_row.confirmed_end + interval '1 hour',
    'max_participants', greatest(
      2,
      (
        select count(*)::integer
        from public.matchmaking_meeting_participants participant
        where participant.meeting_id = meeting_row.id
      )
    )
  );
end;
$function$;

create or replace function public.authorize_matchmaking_video_action(
  p_meeting_id bigint,
  p_action text
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $function$
declare
  context jsonb;
  current_profile_id uuid := public.mm_current_profile_id();
  recent_count integer;
  rate_limit integer;
begin
  if p_action not in ('prepare', 'join', 'revoke') then
    raise exception 'Unsupported video action'
      using errcode = '22023';
  end if;

  context := public.get_matchmaking_video_context(p_meeting_id);
  rate_limit := case p_action when 'join' then 10 when 'prepare' then 5 else 3 end;

  select count(*)
  into recent_count
  from public.matchmaking_video_access_log
  where profile_id = current_profile_id
    and meeting_id = p_meeting_id
    and action = p_action
    and created_at > now() - interval '5 minutes';

  if recent_count >= rate_limit then
    raise exception 'Too many video requests. Try again in a few minutes.'
      using errcode = 'P0001';
  end if;

  insert into public.matchmaking_video_access_log (
    meeting_id,
    profile_id,
    action
  )
  values (p_meeting_id, current_profile_id, p_action);

  return context;
end;
$function$;

create or replace function public.complete_matchmaking_video_room(
  p_meeting_id bigint,
  p_provider text,
  p_video_status text,
  p_room_name text,
  p_room_url text,
  p_room_expires_at timestamptz
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $function$
declare
  meeting_row public.matchmaking_meeting_requests;
  previous_status text;
  participant record;
begin
  if not public.mm_has_service_role() then
    raise exception 'Service role required'
      using errcode = '42501';
  end if;
  if p_provider not in ('daily', 'disabled')
     or p_video_status not in ('ready', 'unconfigured') then
    raise exception 'Invalid video provider completion state'
      using errcode = '22023';
  end if;
  if p_video_status = 'ready' and (
    nullif(trim(p_room_name), '') is null
    or nullif(trim(p_room_url), '') is null
    or p_room_url !~ '^https://'
  ) then
    raise exception 'A secure provider room is required for ready state'
      using errcode = '22023';
  end if;

  select *
  into meeting_row
  from public.matchmaking_meeting_requests
  where id = p_meeting_id
  for update;

  if meeting_row.id is null
     or meeting_row.status not in ('accepted', 'confirmed') then
    raise exception 'Meeting is not ready for video confirmation'
      using errcode = '40001';
  end if;
  if meeting_row.video_status in ('ready', 'unconfigured')
     and meeting_row.status = 'confirmed' then
    return public.mm_meeting_snapshot(meeting_row.id);
  end if;
  if p_video_status = 'ready'
     and meeting_row.video_room_name is distinct from p_room_name then
    raise exception 'Video room claim does not match'
      using errcode = '40001';
  end if;

  previous_status := meeting_row.status;

  update public.matchmaking_meeting_requests
  set
    status = 'confirmed',
    confirmed_at = coalesce(confirmed_at, now()),
    video_provider = p_provider,
    video_status = p_video_status,
    video_room_name = case
      when p_video_status = 'ready' then trim(p_room_name)
      else video_room_name
    end,
    video_room_url = case
      when p_video_status = 'ready' then trim(p_room_url)
      else null
    end,
    video_room_expires_at = p_room_expires_at,
    video_created_at = case
      when p_video_status = 'ready' then now()
      else null
    end,
    video_error_code = null,
    state_version = case
      when status = 'accepted' then state_version + 1
      else state_version
    end,
    last_activity_at = now(),
    updated_at = now()
  where id = meeting_row.id
  returning * into meeting_row;

  perform public.mm_add_meeting_event(
    meeting_row.id,
    meeting_row.connection_id,
    null,
    case when p_video_status = 'ready'
      then 'meeting_confirmed'
      else 'meeting_confirmed_video_unconfigured'
    end,
    previous_status,
    'confirmed',
    jsonb_build_object(
      'video_provider', p_provider,
      'video_status', p_video_status,
      'start_at', meeting_row.confirmed_start,
      'end_at', meeting_row.confirmed_end
    )
  );

  perform public.mm_add_system_message(
    meeting_row.connection_id,
    case when p_video_status = 'ready'
      then 'The meeting is confirmed and the secure video room is ready.'
      else 'The meeting is confirmed. Video is unavailable until the provider is configured.'
    end,
    jsonb_build_object(
      'event_type', 'meeting_confirmed',
      'meeting_id', meeting_row.id,
      'video_status', p_video_status
    )
  );

  for participant in
    select profile_id
    from public.matchmaking_meeting_participants
    where meeting_id = meeting_row.id
  loop
    perform public.mm_add_notification(
      participant.profile_id,
      null,
      meeting_row.connection_id,
      meeting_row.id,
      'meeting_confirmed',
      'Meeting confirmed',
      case when p_video_status = 'ready'
        then 'Your meeting time is confirmed and secure video is ready.'
        else 'Your meeting time is confirmed; video is not configured.'
      end,
      'meeting:' || meeting_row.id || ':confirmed:' || p_video_status,
      '#matchmaking-meeting=' || meeting_row.id
    );

    if meeting_row.confirmed_start - interval '24 hours' > now() then
      insert into public.matchmaking_meeting_reminders (
        meeting_id,
        recipient_profile_id,
        reminder_type,
        channel,
        due_at,
        dedupe_key
      )
      values (
        meeting_row.id,
        participant.profile_id,
        'meeting_24h',
        'in_app',
        meeting_row.confirmed_start - interval '24 hours',
        'meeting:' || meeting_row.id || ':24h:' || participant.profile_id
      )
      on conflict (dedupe_key) do nothing;
    end if;

    if meeting_row.confirmed_start - interval '15 minutes' > now() then
      insert into public.matchmaking_meeting_reminders (
        meeting_id,
        recipient_profile_id,
        reminder_type,
        channel,
        due_at,
        dedupe_key
      )
      values (
        meeting_row.id,
        participant.profile_id,
        'meeting_15m',
        'in_app',
        meeting_row.confirmed_start - interval '15 minutes',
        'meeting:' || meeting_row.id || ':15m:' || participant.profile_id
      )
      on conflict (dedupe_key) do nothing;
    end if;

    insert into public.matchmaking_meeting_reminders (
      meeting_id,
      recipient_profile_id,
      reminder_type,
      channel,
      due_at,
      dedupe_key
    )
    values (
      meeting_row.id,
      participant.profile_id,
      'meeting_start',
      'in_app',
      greatest(meeting_row.confirmed_start, now()),
      'meeting:' || meeting_row.id || ':start:' || participant.profile_id
    )
    on conflict (dedupe_key) do nothing;

    insert into public.matchmaking_meeting_reminders (
      meeting_id,
      recipient_profile_id,
      reminder_type,
      channel,
      due_at,
      dedupe_key
    )
    values (
      meeting_row.id,
      participant.profile_id,
      'post_meeting_follow_up',
      'in_app',
      meeting_row.confirmed_end + interval '30 minutes',
      'meeting:' || meeting_row.id || ':post:' || participant.profile_id
    )
    on conflict (dedupe_key) do nothing;
  end loop;

  return public.mm_meeting_snapshot(meeting_row.id);
end;
$function$;

create or replace function public.fail_matchmaking_video_room(
  p_meeting_id bigint,
  p_error_code text
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $function$
declare
  meeting_row public.matchmaking_meeting_requests;
begin
  if not public.mm_has_service_role() then
    raise exception 'Service role required'
      using errcode = '42501';
  end if;

  update public.matchmaking_meeting_requests
  set
    video_status = 'failed',
    video_error_code = left(
      coalesce(nullif(trim(p_error_code), ''), 'provider_error'),
      120
    ),
    video_claimed_at = null,
    updated_at = now()
  where id = p_meeting_id
    and status = 'accepted'
    and video_status = 'creating'
  returning * into meeting_row;

  if meeting_row.id is null then
    raise exception 'Video room claim is no longer active'
      using errcode = '40001';
  end if;

  perform public.mm_add_meeting_event(
    meeting_row.id,
    meeting_row.connection_id,
    null,
    'video_setup_failed',
    meeting_row.status,
    meeting_row.status,
    jsonb_build_object('error_code', meeting_row.video_error_code)
  );

  return public.mm_meeting_snapshot(meeting_row.id);
end;
$function$;

create or replace function public.get_matchmaking_video_context(
  p_meeting_id bigint
)
returns jsonb
language plpgsql
stable
security definer
set search_path = public, pg_temp
as $function$
declare
  current_profile public.matchmaking_profiles;
  meeting_row public.matchmaking_meeting_requests;
  join_window_open boolean;
begin
  select * into current_profile
  from public.matchmaking_profiles
  where user_id = auth.uid();

  select *
  into meeting_row
  from public.matchmaking_meeting_requests meeting
  where meeting.id = p_meeting_id
    and current_profile.id in (
      meeting.requester_profile_id,
      meeting.recipient_profile_id
    );

  if meeting_row.id is null then
    raise exception 'Meeting not found or access denied'
      using errcode = '42501';
  end if;

  join_window_open :=
    meeting_row.status = 'confirmed'
    and meeting_row.video_status = 'ready'
    and now() >= meeting_row.confirmed_start - interval '15 minutes'
    and now() <= meeting_row.confirmed_end + interval '1 hour';

  return jsonb_build_object(
    'meeting_id', meeting_row.id,
    'connection_id', meeting_row.connection_id,
    'status', meeting_row.status,
    'state_version', meeting_row.state_version,
    'video_provider', meeting_row.video_provider,
    'video_status', meeting_row.video_status,
    'room_name', meeting_row.video_room_name,
    'room_url', meeting_row.video_room_url,
    'room_expires_at', meeting_row.video_room_expires_at,
    'start_at', meeting_row.confirmed_start,
    'end_at', meeting_row.confirmed_end,
    'participant_profile_id', current_profile.id,
    'participant_name', current_profile.display_name,
    'participant_role', case
      when meeting_row.requester_profile_id = current_profile.id
        then 'organizer'
      else 'participant'
    end,
    'can_join', join_window_open,
    'can_revoke', meeting_row.status = 'cancelled'
      and meeting_row.video_room_name is not null
  );
end;
$function$;

create or replace function public.record_matchmaking_video_revocation(
  p_meeting_id bigint
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $function$
declare
  meeting_row public.matchmaking_meeting_requests;
begin
  if not public.mm_has_service_role() then
    raise exception 'Service role required'
      using errcode = '42501';
  end if;

  update public.matchmaking_meeting_requests
  set
    video_status = 'revoked',
    video_room_url = null,
    video_room_expires_at = least(video_room_expires_at, now()),
    updated_at = now()
  where id = p_meeting_id
  returning * into meeting_row;

  if meeting_row.id is null then
    raise exception 'Meeting not found'
      using errcode = '22023';
  end if;

  return public.mm_meeting_snapshot(meeting_row.id);
end;
$function$;

create or replace function public.process_matchmaking_automation(
  p_limit integer default 200
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $function$
declare
  safe_limit integer := greatest(1, least(coalesce(p_limit, 200), 1000));
  expired_meeting record;
  due_reminder record;
  expired_count integer := 0;
  reminder_count integer := 0;
  other_profile_id uuid;
  reminder_connection_id bigint;
  reminder_video_status text;
  notification_title text;
  notification_body text;
begin
  if not public.mm_has_service_role() then
    raise exception 'Service role required'
      using errcode = '42501';
  end if;

  for expired_meeting in
    with candidates as (
      select meeting.id, meeting.status as previous_status
      from public.matchmaking_meeting_requests meeting
      where meeting.status in (
        'proposed',
        'awaiting_response',
        'counter_proposed'
      )
        and (
          meeting.expires_at <= now()
          or not exists (
            select 1
            from public.matchmaking_meeting_proposals proposal
            where proposal.meeting_id = meeting.id
              and proposal.proposal_round = meeting.proposal_round
              and proposal.status = 'active'
              and proposal.end_at > now()
          )
        )
      order by meeting.expires_at nulls last, meeting.id
      limit safe_limit
      for update skip locked
    )
    update public.matchmaking_meeting_requests meeting
    set
      status = 'expired',
      state_version = state_version + 1,
      last_activity_at = now(),
      updated_at = now()
    from candidates
    where meeting.id = candidates.id
    returning meeting.*, candidates.previous_status
  loop
    update public.matchmaking_meeting_proposals
    set status = 'withdrawn'
    where meeting_id = expired_meeting.id
      and status = 'active';

    perform public.mm_add_meeting_event(
      expired_meeting.id,
      expired_meeting.connection_id,
      null,
      'meeting_expired',
      expired_meeting.previous_status,
      'expired',
      jsonb_build_object('automation', true)
    );
    perform public.mm_add_system_message(
      expired_meeting.connection_id,
      'The meeting proposal expired without a confirmed time.',
      jsonb_build_object(
        'event_type', 'meeting_expired',
        'meeting_id', expired_meeting.id
      )
    );

    perform public.mm_add_notification(
      expired_meeting.requester_profile_id,
      null,
      expired_meeting.connection_id,
      expired_meeting.id,
      'meeting_expired',
      'Meeting proposal expired',
      'The proposed meeting times expired without confirmation.',
      'meeting:' || expired_meeting.id || ':expired',
      '#matchmaking-meeting=' || expired_meeting.id
    );
    perform public.mm_add_notification(
      expired_meeting.recipient_profile_id,
      null,
      expired_meeting.connection_id,
      expired_meeting.id,
      'meeting_expired',
      'Meeting proposal expired',
      'The proposed meeting times expired without confirmation.',
      'meeting:' || expired_meeting.id || ':expired',
      '#matchmaking-meeting=' || expired_meeting.id
    );
    expired_count := expired_count + 1;
  end loop;

  for due_reminder in
    with candidates as (
      select reminder.id
      from public.matchmaking_meeting_reminders reminder
      where reminder.status = 'scheduled'
        and reminder.due_at <= now()
      order by reminder.due_at, reminder.id
      limit safe_limit
      for update skip locked
    )
    update public.matchmaking_meeting_reminders reminder
    set status = 'processing', claimed_at = now()
    from candidates
    where reminder.id = candidates.id
    returning reminder.*
  loop
    if due_reminder.channel = 'in_app' then
      notification_title := case due_reminder.reminder_type
        when 'meeting_24h' then 'Meeting tomorrow'
        when 'meeting_15m' then 'Meeting starts in 15 minutes'
        when 'meeting_start' then 'Meeting starting now'
        else 'Meeting follow-up'
      end;
      select
        case
          when meeting.requester_profile_id = due_reminder.recipient_profile_id
            then meeting.recipient_profile_id
          else meeting.requester_profile_id
        end,
        meeting.connection_id,
        meeting.video_status
      into
        other_profile_id,
        reminder_connection_id,
        reminder_video_status
      from public.matchmaking_meeting_requests meeting
      where meeting.id = due_reminder.meeting_id;

      notification_body := case due_reminder.reminder_type
        when 'meeting_24h' then 'Review the agenda and confirmed time.'
        when 'meeting_15m' then case
          when reminder_video_status = 'ready'
            then 'Your secure meeting room is now available.'
          else 'Open the meeting workspace; embedded video is not configured.'
        end
        when 'meeting_start' then case
          when reminder_video_status = 'ready'
            then 'Open the meeting workspace to join securely.'
          else 'Your meeting starts now; embedded video is not configured.'
        end
        else 'Record the outcome and next steps from your meeting.'
      end;

      perform public.mm_add_notification(
        due_reminder.recipient_profile_id,
        other_profile_id,
        reminder_connection_id,
        due_reminder.meeting_id,
        due_reminder.reminder_type,
        notification_title,
        notification_body,
        due_reminder.dedupe_key,
        '#matchmaking-meeting=' || due_reminder.meeting_id
      );

      update public.matchmaking_meeting_reminders
      set status = 'sent', sent_at = now(), error_code = null
      where id = due_reminder.id;
      reminder_count := reminder_count + 1;
    else
      update public.matchmaking_meeting_reminders
      set
        status = 'failed',
        error_code = 'email_provider_unconfigured'
      where id = due_reminder.id;
    end if;
  end loop;

  delete from public.matchmaking_idempotency_keys
  where expires_at < now();

  delete from public.matchmaking_video_access_log
  where created_at < now() - interval '30 days';

  return jsonb_build_object(
    'expired_meetings', expired_count,
    'sent_in_app_reminders', reminder_count,
    'processed_at', now()
  );
end;
$function$;

revoke all on function public.mm_has_service_role()
  from public, anon, authenticated;
revoke all on function public.claim_matchmaking_video_room(bigint)
  from public, anon, authenticated;
grant execute on function public.claim_matchmaking_video_room(bigint)
  to service_role;

revoke all on function public.complete_matchmaking_video_room(
  bigint, text, text, text, text, timestamptz
) from public, anon, authenticated;
grant execute on function public.complete_matchmaking_video_room(
  bigint, text, text, text, text, timestamptz
) to service_role;

revoke all on function public.fail_matchmaking_video_room(bigint, text)
  from public, anon, authenticated;
grant execute on function public.fail_matchmaking_video_room(bigint, text)
  to service_role;

revoke all on function public.get_matchmaking_video_context(bigint)
  from public, anon;
grant execute on function public.get_matchmaking_video_context(bigint)
  to authenticated, service_role;

revoke all on function public.authorize_matchmaking_video_action(bigint, text)
  from public, anon;
grant execute on function public.authorize_matchmaking_video_action(bigint, text)
  to authenticated, service_role;

revoke all on function public.record_matchmaking_video_revocation(bigint)
  from public, anon, authenticated;
grant execute on function public.record_matchmaking_video_revocation(bigint)
  to service_role;

revoke all on function public.process_matchmaking_automation(integer)
  from public, anon, authenticated;
grant execute on function public.process_matchmaking_automation(integer)
  to service_role;

do $schedule$
declare
  existing_job bigint;
  scheduled_job bigint;
begin
  if exists (
    select 1
    from pg_extension
    where extname = 'pg_cron'
  ) then
    execute
      'select jobid from cron.job where jobname = $1 limit 1'
      into existing_job
      using 'medichall-matchmaking-automation';
    if existing_job is not null then
      execute 'select cron.unschedule($1)' using existing_job;
    end if;
    execute
      'select cron.schedule($1, $2, $3)'
      into scheduled_job
      using
        'medichall-matchmaking-automation',
        '*/5 * * * *',
        'select public.process_matchmaking_automation(200);';
    raise notice 'Scheduled matchmaking automation job %', scheduled_job;
  else
    raise notice
      'pg_cron is unavailable; process_matchmaking_automation remains callable by service role';
  end if;
exception
  when insufficient_privilege or undefined_table or invalid_schema_name then
    raise notice
      'Matchmaking automation was not scheduled: %',
      sqlerrm;
end
$schedule$;

notify pgrst, 'reload schema';

commit;
